"""Tests for meridian_rig — the canonical bone table (spec ④ §2) and the
committed reference rig .glb it generates."""

import re
import sys
from pathlib import Path

import pytest
import yaml

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools" / "blender" / "meridian_rig"))
import blender_pin  # noqa: E402
import bones  # noqa: E402
import generate_rig  # noqa: E402
import restyle_armor  # noqa: E402
import restyle_body  # noqa: E402
import restyle_hair  # noqa: E402

# The committed reference rig. Generated by generate_rig.py under Blender and
# stored via Git LFS; the structural tests below read it back with pygltflib so
# they run in CI without a Blender install.
RIG_GLB = REPO / "content/core/assets/art/char/sk_ardent_male_skeleton.glb"


def _is_lfs_pointer(path: Path) -> bool:
    """True when `path` is an unsmudged Git-LFS pointer rather than a real .glb.

    CI checks out without `lfs: true`, so the binary is a small text pointer
    there; the structural tests skip in that case and run locally (and on any
    LFS-smudged checkout) against the real geometry.
    """
    try:
        with open(path, "rb") as fh:
            return fh.read(64).startswith(b"version https://git-lfs")
    except FileNotFoundError:
        return False


skip_if_pointer = pytest.mark.skipif(
    _is_lfs_pointer(RIG_GLB),
    reason="rig .glb is an unsmudged LFS pointer (CI checkout without LFS smudge)",
)


def test_bone_count_is_63():
    assert len(bones.ALL_BONES) == 63
    assert len(bones.PROFILE_BONES) == 56
    assert len(bones.SOCKET_BONES) == 7


def test_hierarchy_is_wellformed_single_root():
    h = bones.hierarchy()
    roots = [n for n, p in h.items() if p is None]
    assert roots == ["Root"]
    names = set(h)
    assert all(p in names for p in h.values() if p is not None)


def test_socket_parents_match_spec():
    parents = {b.name: b.parent for b in bones.SOCKET_BONES}
    assert parents == {
        "socket_main_hand": "RightHand",
        "socket_off_hand": "LeftHand",
        "socket_shield": "LeftHand",
        "socket_back": "Chest",
        "socket_ranged": "Chest",
        "socket_hip_l": "Hips",
        "socket_hip_r": "Hips",
    }


def test_skeleton_defs_bones_matches_table():
    """Drift guard: schema/content/skeleton.defs.yaml bones == bones.py names."""
    defs = yaml.safe_load((REPO / "schema/content/skeleton.defs.yaml").read_text())
    assert defs["$defs"]["boneName"]["enum"] == bones.bone_names()


def test_unknown_profile_raises():
    with pytest.raises(ValueError, match="ardent_male"):
        bones.for_profile("dwarf_female")


# ---------------------------------------------------------------------------
# generate_rig — pure argument/path helpers (importable without bpy).
# ---------------------------------------------------------------------------
def test_yup_to_blender_maps_gltf_yup_to_blender_zup():
    # Table/glTF Y-up (x, y, z) -> Blender Z-up (x, -z, y); the exporter's
    # +Y-up conversion maps it back, so table coords round-trip exactly.
    assert generate_rig.yup_to_blender((1.0, 2.0, 3.0)) == (1.0, -3.0, 2.0)
    assert generate_rig.yup_to_blender((0.0, 0.95, 0.0)) == (0.0, 0.0, 0.95)


def test_argv_after_ddash_extracts_generator_args():
    argv = [
        "blender",
        "--background",
        "--python",
        "generate_rig.py",
        "--",
        "--profile",
        "ardent_male",
        "--out",
        "x.glb",
    ]
    assert generate_rig.argv_after_ddash(argv) == [
        "--profile",
        "ardent_male",
        "--out",
        "x.glb",
    ]


def test_argv_after_ddash_empty_when_no_separator():
    assert generate_rig.argv_after_ddash(["blender", "--background"]) == []


def test_parse_args_defaults_to_ardent_male():
    ns = generate_rig.parse_args([])
    assert ns.profile == "ardent_male"
    assert ns.out.endswith("sk_ardent_male_skeleton.glb")


def test_parse_args_reads_profile_and_out():
    ns = generate_rig.parse_args(["--profile", "ardent_male", "--out", "/tmp/r.glb"])
    assert ns.profile == "ardent_male"
    assert ns.out == "/tmp/r.glb"


def test_parse_args_rejects_unknown_profile():
    with pytest.raises(SystemExit):
        generate_rig.parse_args(["--profile", "dwarf_female"])


def test_parse_args_allow_unpinned_blender_defaults_false():
    ns = generate_rig.parse_args([])
    assert ns.allow_unpinned_blender is False


def test_parse_args_allow_unpinned_blender_flag():
    ns = generate_rig.parse_args(["--allow-unpinned-blender"])
    assert ns.allow_unpinned_blender is True


# ---------------------------------------------------------------------------
# blender_pin.check_pin — pure Blender version-pin comparison (spec ④ §9).
# ---------------------------------------------------------------------------
def test_check_pin_matching_version_returns_none():
    assert blender_pin.check_pin((5, 0, 0), "5.0.0") is None


def test_check_pin_uses_module_pinned_version_by_default():
    # blender_pin.PINNED_VERSION is the single source of truth entry points
    # actually enforce (tools/blender/README.md documents it, doesn't define it).
    pinned = tuple(int(p) for p in blender_pin.PINNED_VERSION.split("."))
    assert blender_pin.check_pin(pinned) is None


def test_check_pin_mismatch_names_both_versions():
    error = blender_pin.check_pin((4, 2, 1), "5.0.0")
    assert error is not None
    assert "5.0.0" in error
    assert "4.2.1" in error


def test_check_pin_mismatch_on_patch_version_only():
    error = blender_pin.check_pin((5, 0, 1), "5.0.0")
    assert error is not None
    assert "5.0.0" in error
    assert "5.0.1" in error


def test_check_pin_malformed_pinned_string():
    error = blender_pin.check_pin((5, 0, 0), "not-a-version")
    assert error is not None
    assert "malformed" in error
    assert "not-a-version" in error


def test_check_pin_malformed_pinned_wrong_arity():
    error = blender_pin.check_pin((5, 0, 0), "5.0")
    assert error is not None
    assert "malformed" in error


def test_check_pin_malformed_version_tuple():
    error = blender_pin.check_pin(("a", "b", "c"), "5.0.0")
    assert error is not None
    assert "malformed" in error


def test_check_pin_malformed_version_tuple_wrong_arity():
    error = blender_pin.check_pin((5, 0), "5.0.0")
    assert error is not None
    assert "malformed" in error


# ---------------------------------------------------------------------------
# Structural checks on the committed reference rig .glb (read back, no Blender).
# ---------------------------------------------------------------------------
def _load_rig_gltf():
    from pygltflib import GLTF2

    return GLTF2().load(str(RIG_GLB))


@pytest.mark.integration
@skip_if_pointer
def test_rig_glb_bone_names_match_table():
    g = _load_rig_gltf()
    node_names = {n.name for n in g.nodes}
    missing = set(bones.bone_names()) - node_names
    assert not missing, f"bones absent from exported .glb: {sorted(missing)}"


@pytest.mark.integration
@skip_if_pointer
def test_rig_glb_hierarchy_matches_table():
    g = _load_rig_gltf()
    child_to_parent: dict[str, str] = {}
    for n in g.nodes:
        for c in n.children or []:
            child_to_parent[g.nodes[c].name] = n.name
    for name, parent in bones.hierarchy().items():
        if parent is not None:
            assert child_to_parent.get(name) == parent, name


def _quat_to_mat3(q):
    """glTF quaternion [x, y, z, w] -> 3x3 rotation matrix (row-major)."""
    x, y, z, w = q
    return [
        [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
        [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
        [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
    ]


def _global_positions(g) -> dict[str, tuple[float, float, float]]:
    """Compose each node's TRS down the scene graph -> global joint positions."""

    def local_mat(n):
        r = _quat_to_mat3(n.rotation or [0.0, 0.0, 0.0, 1.0])
        t = n.translation or [0.0, 0.0, 0.0]
        s = n.scale or [1.0, 1.0, 1.0]
        return [[r[i][j] * s[j] for j in range(3)] + [t[i]] for i in range(3)] + [
            [0.0, 0.0, 0.0, 1.0]
        ]

    def matmul(a, b):
        return [
            [sum(a[i][k] * b[k][j] for k in range(4)) for j in range(4)]
            for i in range(4)
        ]

    out: dict[str, tuple[float, float, float]] = {}

    def walk(node_idx: int, parent):
        n = g.nodes[node_idx]
        m = matmul(parent, local_mat(n))
        if n.name:
            out[n.name] = (m[0][3], m[1][3], m[2][3])
        for c in n.children or []:
            walk(c, m)

    identity = [[float(i == j) for j in range(4)] for i in range(4)]
    for root in g.scenes[g.scene].nodes:
        walk(root, identity)
    return out


@pytest.mark.integration
@skip_if_pointer
def test_rig_glb_rest_transforms_match_table():
    """Each joint's composed global rest position == the table's head_m (Y-up).

    Spec ④ §2.2 contract: names/hierarchy/REST TRANSFORMS survive the export.
    glTF stores joints (bone heads); tails are Blender-side authoring detail.
    """
    g = _load_rig_gltf()
    pos = _global_positions(g)
    for spec in bones.ALL_BONES:
        got = pos[spec.name]
        for axis, (a, b) in enumerate(zip(got, spec.head_m)):
            assert abs(a - b) < 1e-4, (
                f"{spec.name} axis {axis}: exported {got} != table {spec.head_m}"
            )


@pytest.mark.integration
@skip_if_pointer
def test_rig_glb_has_single_bone_root():
    """Exactly one table bone (Root) has no bone parent inside the armature."""
    g = _load_rig_gltf()
    child_to_parent: dict[str, str] = {}
    for n in g.nodes:
        for c in n.children or []:
            child_to_parent[g.nodes[c].name] = n.name
    table = set(bones.bone_names())
    unparented = {b for b in table if child_to_parent.get(b) not in table}
    assert unparented == {"Root"}, unparented


# ---------------------------------------------------------------------------
# generate_blockout — pure helpers (importable without bpy) + structural checks
# on the committed greybox blockout body .glb (spec ④ §6 / T5).
# ---------------------------------------------------------------------------
import generate_blockout  # noqa: E402

BODY_GLB = REPO / "content/core/assets/art/char/sk_ardent_male_base.glb"

skip_if_body_pointer = pytest.mark.skipif(
    _is_lfs_pointer(BODY_GLB),
    reason="body .glb is an unsmudged LFS pointer (CI checkout without LFS smudge)",
)

GEOSET_REGIONS = [
    "head",
    "hands",
    "forearms",
    "torso",
    "waist",
    "hips_legs",
    "lower_legs",
    "feet",
]


def test_blockout_region_groups_cover_exactly_the_8_geoset_regions():
    """Drift guard: region keys == skeleton.defs.yaml $defs.geosetRegion.enum."""
    defs = yaml.safe_load((REPO / "schema/content/skeleton.defs.yaml").read_text())
    assert sorted(generate_blockout.region_bone_groups()) == sorted(
        defs["$defs"]["geosetRegion"]["enum"]
    )


def test_blockout_region_groups_use_only_canonical_bones():
    canonical = set(bones.bone_names())
    for region, groups in generate_blockout.region_bone_groups().items():
        for group in groups:
            assert group, f"{region} has an empty bone group"
            unknown = set(group) - canonical
            assert not unknown, f"{region} names unknown bones: {sorted(unknown)}"


def test_blockout_mesh_name_follows_geoset_convention():
    assert generate_blockout.mesh_name("head") == "geo_head_lod0"
    assert generate_blockout.mesh_name("hips_legs") == "geo_hips_legs_lod0"


def test_blockout_group_bbox_encloses_bones_with_min_radius():
    lo, hi = generate_blockout.group_bbox(["Head", "Neck"], radius=0.11)
    # Neck head y=1.44, Head tail y=1.72 — box spans at least that.
    assert lo[1] <= 1.44 and hi[1] >= 1.72
    # X span of the chain is 0 — the radius guarantees >= 0.11 half-extent.
    assert (hi[0] - lo[0]) / 2.0 >= 0.11 - 1e-9


def test_blockout_parse_args_defaults():
    ns = generate_blockout.parse_args([])
    assert ns.profile == "ardent_male"
    assert ns.out.endswith("sk_ardent_male_base.glb")


def test_blockout_parse_args_rejects_unknown_profile():
    with pytest.raises(SystemExit):
        generate_blockout.parse_args(["--profile", "dwarf_female"])


def _load_body_gltf():
    from pygltflib import GLTF2

    return GLTF2().load(str(BODY_GLB))


def _read_accessor_vec4(g, accessor_idx):
    """Decode a VEC4 accessor from the .glb binary blob -> list of 4-tuples."""
    import struct

    acc = g.accessors[accessor_idx]
    bv = g.bufferViews[acc.bufferView]
    blob = g.binary_blob()
    fmt_by_component = {5121: "B", 5123: "H", 5125: "I", 5126: "f"}
    fmt = fmt_by_component[acc.componentType]
    elem_size = struct.calcsize(fmt) * 4
    stride = bv.byteStride or elem_size
    base = (bv.byteOffset or 0) + (acc.byteOffset or 0)
    out = []
    for i in range(acc.count):
        off = base + i * stride
        out.append(struct.unpack_from("<" + fmt * 4, blob, off))
    return out


_GEO_LOD_RE = re.compile(r"^geo_(?P<region>[a-z0-9_]+)_lod(?P<lod>\d+)$")


@pytest.mark.integration
@skip_if_body_pointer
def test_body_glb_lod0_covers_exactly_the_8_geoset_regions():
    """I022: the eight geoset regions are each present at LOD0 (spec ④ §3/§5).

    The real ⑤/S4 body ships an authored LOD chain, so LOD0 is a subset of the
    full mesh list — this asserts the LOD0 coverage specifically, not the whole
    mesh count (which the blockout's `single`-LOD body could).
    """
    g = _load_body_gltf()
    lod0 = set()
    for m in g.meshes:
        mm = _GEO_LOD_RE.match(m.name)
        assert mm, f"body mesh '{m.name}' is not geoset-named (geo_<region>_lod<N>)"
        if int(mm.group("lod")) == 0:
            lod0.add(mm.group("region"))
    assert lod0 == set(GEOSET_REGIONS), (
        f"LOD0 regions {sorted(lod0)} != {sorted(GEOSET_REGIONS)}"
    )


@pytest.mark.integration
@skip_if_body_pointer
def test_body_glb_ships_authored_lod_chain_per_region():
    """I023: every geoset region carries LOD0 + at least one lower LOD.

    The real body is NOT the `single`-LOD blockout — each of the eight regions
    must ship an authored chain (geo_<region>_lod0 plus geo_<region>_lod1+),
    the exact condition validate_imports I023 enforces on the committed .glb.
    """
    g = _load_body_gltf()
    chain: dict[str, set[int]] = {}
    for m in g.meshes:
        mm = _GEO_LOD_RE.match(m.name)
        assert mm, f"body mesh '{m.name}' is not geoset-named"
        chain.setdefault(mm.group("region"), set()).add(int(mm.group("lod")))
    for region in GEOSET_REGIONS:
        lods = chain.get(region, set())
        assert 0 in lods, f"region '{region}' has no LOD0"
        assert any(lod >= 1 for lod in lods), (
            f"region '{region}' has no LOD1+ — a real body ships an authored "
            f"chain, not the blockout's 'single' exemption (I023)"
        )


@pytest.mark.integration
@skip_if_body_pointer
def test_body_glb_skin_joints_are_exactly_the_canonical_bone_set():
    """I020: every skin joint is canonical AND the full 63-bone set is bound."""
    g = _load_body_gltf()
    assert g.skins, "body .glb carries no skin"
    joint_names = set()
    for skin in g.skins:
        for j in skin.joints or []:
            joint_names.add(g.nodes[j].name)
    canonical = set(bones.bone_names())
    assert joint_names - canonical == set(), (
        f"non-canonical joints: {sorted(joint_names - canonical)}"
    )
    assert canonical - joint_names == set(), (
        f"canonical bones missing from skin: {sorted(canonical - joint_names)}"
    )


@pytest.mark.integration
@skip_if_body_pointer
def test_body_glb_vertices_have_at_most_4_influences():
    """E103/spec ④ §6: one JOINTS_0/WEIGHTS_0 set only — no JOINTS_1 spillover."""
    g = _load_body_gltf()
    for mesh in g.meshes:
        for prim in mesh.primitives:
            attrs = prim.attributes
            assert attrs.JOINTS_0 is not None, f"{mesh.name} is not skinned"
            assert attrs.WEIGHTS_0 is not None, f"{mesh.name} has no weights"
            assert getattr(attrs, "JOINTS_1", None) is None, (
                f"{mesh.name} carries a second influence set (>4 influences)"
            )


@pytest.mark.integration
@skip_if_body_pointer
def test_body_glb_weights_are_normalized():
    g = _load_body_gltf()
    for mesh in g.meshes:
        for prim in mesh.primitives:
            weights = _read_accessor_vec4(g, prim.attributes.WEIGHTS_0)
            comp = g.accessors[prim.attributes.WEIGHTS_0].componentType
            scale = 1.0 if comp == 5126 else (255.0 if comp == 5121 else 65535.0)
            for i, w in enumerate(weights):
                total = sum(w) / scale
                assert abs(total - 1.0) < 5e-3, (
                    f"{mesh.name} vertex {i} weight sum {total}"
                )


# --- restyle_body pure helpers (spec ⑤/S4; bpy-free, unit-tested) ------------


def test_restyle_mesh_name_follows_geoset_lod_convention():
    assert restyle_body.mesh_name("head", 0) == "geo_head_lod0"
    assert restyle_body.mesh_name("hips_legs", 3) == "geo_hips_legs_lod3"


def test_restyle_region_anchors_cover_every_geoset_region():
    """One anchor per bone-group; every one of the 8 regions is represented."""
    anchors = restyle_body.region_anchors()
    regions = set(r for r, _ in anchors)
    assert regions == set(GEOSET_REGIONS)
    # Paired limbs contribute two anchors (left/right); central regions one.
    assert len(anchors) == sum(
        len(groups) for groups in generate_blockout.region_bone_groups().values()
    )


def test_restyle_nearest_region_picks_closest_anchor():
    anchors = [("head", (0.0, 0.0, 1.7)), ("feet", (0.0, 0.0, 0.05))]
    assert restyle_body.nearest_region((0.0, 0.0, 1.65), anchors) == "head"
    assert restyle_body.nearest_region((0.0, 0.0, 0.1), anchors) == "feet"


def test_restyle_rig_bounds_z_spans_feet_to_head():
    lo, hi = restyle_body.rig_bounds_z()
    assert lo == pytest.approx(0.0, abs=0.05)  # feet on the floor
    assert hi == pytest.approx(1.72, abs=0.05)  # head crown


def test_restyle_fit_transform_scales_height_and_floors_feet():
    mesh_min, mesh_max = (-1.0, -0.2, -0.95), (1.0, 0.2, 0.95)
    rig_lo, rig_hi = 0.0, 1.72
    scale, offset = restyle_body.fit_transform(mesh_min, mesh_max, rig_lo, rig_hi)
    # Height maps onto the rig span.
    assert (mesh_max[2] - mesh_min[2]) * scale == pytest.approx(rig_hi - rig_lo)
    # Feet floored to the rig floor; scaled bbox top reaches the rig crown.
    assert mesh_min[2] * scale + offset[2] == pytest.approx(rig_lo)
    assert mesh_max[2] * scale + offset[2] == pytest.approx(rig_hi)
    # X/Y centre lands on the rig's vertical axis.
    cx = (mesh_min[0] + mesh_max[0]) / 2.0 * scale + offset[0]
    assert cx == pytest.approx(0.0)


def test_restyle_lod_ratios_are_a_descending_chain_from_full():
    assert restyle_body.LOD_RATIOS[0] == 1.0
    assert all(
        a > b for a, b in zip(restyle_body.LOD_RATIOS, restyle_body.LOD_RATIOS[1:])
    )
    assert len(restyle_body.LOD_RATIOS) >= 2  # lod0 + at least one lower LOD (I023)


def test_restyle_parse_args_requires_input_and_defaults_out():
    ns = restyle_body.parse_args(["--in", "raw.glb"])
    assert ns.in_glb == "raw.glb"
    assert ns.out.endswith("sk_ardent_male_base.glb")
    assert ns.profile == "ardent_male"
    with pytest.raises(SystemExit):
        restyle_body.parse_args([])  # --in is required


# --- restyle_hair pure helpers (spec ⑤/S5; bpy-free, unit-tested) ------------


def test_restyle_hair_bone_is_a_canonical_bone():
    """Hair single-influence skins to Head — which must be a canonical bone."""
    assert restyle_hair.HAIR_BONE in set(bones.bone_names())


def test_restyle_hair_mesh_name_is_not_geoset_named():
    """E104: an armor_model piece must NOT use geo_<region> geoset naming."""
    assert not restyle_hair.HAIR_MESH_NAME.startswith("geo_")


def test_restyle_hair_head_region_box_spans_the_head_geoset():
    """The fit target is the canonical head geoset span (crown ~1.72, base ~1.44)."""
    lo, hi = restyle_hair.head_region_box()
    assert hi[2] == pytest.approx(1.72, abs=0.05)  # crown at the Head bone tail
    assert lo[2] == pytest.approx(1.44, abs=0.05)  # base at the Neck head
    # A head-width box centred on the rig's vertical axis.
    assert lo[0] == pytest.approx(-hi[0], abs=1e-6)
    assert (hi[0] - lo[0]) > 0.0


def test_restyle_hair_fit_transform_scales_footprint_to_head_width():
    head_lo, head_hi = restyle_hair.head_region_box()
    mesh_min, mesh_max = (-0.5, -0.4, -0.3), (0.5, 0.4, 0.6)
    scale, offset = restyle_hair.fit_head_transform(
        mesh_min, mesh_max, head_lo, head_hi
    )
    head_w = max(head_hi[0] - head_lo[0], head_hi[1] - head_lo[1])
    mesh_w = max(mesh_max[0] - mesh_min[0], mesh_max[1] - mesh_min[1])
    assert scale == pytest.approx(head_w / mesh_w)


def test_restyle_hair_fit_transform_centres_volume_on_the_head():
    head_lo, head_hi = restyle_hair.head_region_box()
    mesh_min, mesh_max = (-0.5, -0.4, -0.3), (0.5, 0.4, 0.6)
    scale, offset = restyle_hair.fit_head_transform(
        mesh_min, mesh_max, head_lo, head_hi
    )

    def _c(lo, hi, i):
        return (lo[i] + hi[i]) / 2.0

    for i in range(3):
        placed_centre = _c(mesh_min, mesh_max, i) * scale + offset[i]
        assert placed_centre == pytest.approx(_c(head_lo, head_hi, i), abs=1e-6)
    # The seated hair centre sits within the head geoset's vertical span.
    placed_cz = _c(mesh_min, mesh_max, 2) * scale + offset[2]
    assert head_lo[2] <= placed_cz <= head_hi[2]


def test_restyle_hair_budget_is_low_poly_under_the_armor_ceiling():
    """Hair is a light attachment — target well under the armor_model 8k cap."""
    assert restyle_hair.TARGET_TRIS <= restyle_hair.MAX_TRIS
    assert restyle_hair.MAX_TRIS < 8_000  # armor_model L070 ceiling


def test_restyle_hair_parse_args_requires_input_and_defaults_out():
    ns = restyle_hair.parse_args(["--in", "raw.glb"])
    assert ns.in_glb == "raw.glb"
    assert ns.out.endswith("hair_1.glb")
    assert ns.profile == "ardent_male"
    with pytest.raises(SystemExit):
        restyle_hair.parse_args([])  # --in is required


# --- committed hair .glb structural tests (spec ⑤/S5) ------------------------

HAIR_GLBS = [
    REPO / f"content/core/assets/art/char/ardent/male/hair_{n}.glb" for n in range(1, 5)
]

# armor_model L070 ceiling (Art PRD §2.1 armor set piece 3-8k) — a hair mesh
# must sit comfortably under it (it is a light attachment, not a full plate).
_ARMOR_TRI_CEILING = 8_000


def _hair_present_and_smudged(path: Path) -> bool:
    return path.is_file() and not _is_lfs_pointer(path)


@pytest.mark.integration
@pytest.mark.parametrize("hair_glb", HAIR_GLBS, ids=lambda p: p.stem)
def test_hair_glb_binds_only_the_canonical_head_bone(hair_glb):
    """I021/E100: the hair skin binds only canonical bones, and Head is among them."""
    if not _hair_present_and_smudged(hair_glb):
        pytest.skip(f"{hair_glb.name} missing or an unsmudged LFS pointer")
    from pygltflib import GLTF2

    g = GLTF2().load(str(hair_glb))
    assert g.skins, f"{hair_glb.name} carries no skin"
    joints = set()
    for skin in g.skins:
        for j in skin.joints or []:
            joints.add(g.nodes[j].name)
    canonical = set(bones.bone_names())
    assert joints - canonical == set(), (
        f"{hair_glb.name} binds non-canonical joints: {sorted(joints - canonical)}"
    )
    assert restyle_hair.HAIR_BONE in joints, (
        f"{hair_glb.name} skin does not bind the {restyle_hair.HAIR_BONE} bone"
    )


@pytest.mark.integration
@pytest.mark.parametrize("hair_glb", HAIR_GLBS, ids=lambda p: p.stem)
def test_hair_glb_is_single_influence(hair_glb):
    """E103/spec ⑤/S5: hair uses one influence per vertex (no JOINTS_1 spillover)."""
    if not _hair_present_and_smudged(hair_glb):
        pytest.skip(f"{hair_glb.name} missing or an unsmudged LFS pointer")
    from pygltflib import GLTF2

    g = GLTF2().load(str(hair_glb))
    for mesh in g.meshes:
        for prim in mesh.primitives:
            attrs = prim.attributes
            assert attrs.JOINTS_0 is not None, f"{mesh.name} is not skinned"
            assert getattr(attrs, "JOINTS_1", None) is None, (
                f"{mesh.name} carries a second influence set (>4 influences)"
            )
            weights = _read_accessor_vec4(g, attrs.WEIGHTS_0)
            comp = g.accessors[attrs.WEIGHTS_0].componentType
            scale = 1.0 if comp == 5126 else (255.0 if comp == 5121 else 65535.0)
            for i, w in enumerate(weights):
                nonzero = [c for c in w if c / scale > 1e-3]
                assert len(nonzero) == 1, (
                    f"{mesh.name} vertex {i} has {len(nonzero)} influences "
                    f"(hair is single-influence)"
                )
                assert abs(nonzero[0] / scale - 1.0) < 5e-3, (
                    f"{mesh.name} vertex {i} single weight {nonzero[0] / scale} != 1"
                )


@pytest.mark.integration
@pytest.mark.parametrize("hair_glb", HAIR_GLBS, ids=lambda p: p.stem)
def test_hair_glb_is_low_poly_within_budget(hair_glb):
    """L070: the committed hair mesh is under the armor_model tri ceiling."""
    if not _hair_present_and_smudged(hair_glb):
        pytest.skip(f"{hair_glb.name} missing or an unsmudged LFS pointer")
    from pygltflib import GLTF2

    g = GLTF2().load(str(hair_glb))
    tris = 0
    for mesh in g.meshes:
        for prim in mesh.primitives:
            if prim.indices is not None:
                tris += g.accessors[prim.indices].count // 3
            else:
                tris += g.accessors[prim.attributes.POSITION].count // 3
    assert 0 < tris <= _ARMOR_TRI_CEILING, (
        f"{hair_glb.name} has {tris} tris (must be 1..{_ARMOR_TRI_CEILING})"
    )


@pytest.mark.integration
@pytest.mark.parametrize("hair_glb", HAIR_GLBS, ids=lambda p: p.stem)
def test_hair_glb_mesh_is_not_geoset_named(hair_glb):
    """E104: an armor_model hair mesh must not use geo_<region> geoset naming."""
    if not _hair_present_and_smudged(hair_glb):
        pytest.skip(f"{hair_glb.name} missing or an unsmudged LFS pointer")
    from pygltflib import GLTF2

    g = GLTF2().load(str(hair_glb))
    for mesh in g.meshes:
        assert not (mesh.name or "").startswith("geo_"), (
            f"{hair_glb.name} mesh '{mesh.name}' is geoset-named (forbidden for gear)"
        )


# --- restyle_armor pure helpers (spec ⑤/S4, #595; bpy-free, unit-tested) ------


def test_restyle_armor_regions_bind_only_canonical_bones():
    """Every region's bind set names only canonical bones (I021/E100)."""
    canonical = set(bones.bone_names())
    for region, cfg in restyle_armor.REGION_BIND.items():
        assert cfg.bind, f"{region} has an empty bind set"
        assert set(cfg.bind) <= canonical, (
            f"{region} binds non-canonical bones: {sorted(set(cfg.bind) - canonical)}"
        )


def test_restyle_armor_chest_binds_the_spine_column():
    """The chest cuirass rides Spine/Chest/UpperChest (the torso column)."""
    chest = restyle_armor.REGION_BIND["chest"]
    assert chest.region == "torso"
    assert set(chest.bind) == {"Spine", "Chest", "UpperChest"}


def test_restyle_armor_mesh_name_is_not_geoset_named():
    """E104: the exported armor mesh must not use geo_<region> geoset naming."""
    assert not restyle_armor.ARMOR_MESH_NAME.startswith("geo_")


def test_restyle_armor_budget_band_is_within_the_armor_ceiling():
    """Art PRD §2.1: 3–8k tris/slot, under the 8k armor_model L070 ceiling."""
    assert restyle_armor.MIN_TRIS >= 3_000
    assert restyle_armor.MIN_TRIS <= restyle_armor.TARGET_TRIS <= restyle_armor.MAX_TRIS
    assert restyle_armor.MAX_TRIS < 8_000


def test_restyle_armor_torso_region_box_spans_spine_to_shoulders():
    """The torso region box covers the spine column up to the shoulder girdle.

    Blender Z-up: Z (index 2) is height. The torso bones run Spine.head (Y=1.05)
    → UpperChest.tail (Y=1.44), so the box's Z span must bracket that range — the
    span a chest cuirass covers and reaches up from.
    """
    lo, hi = restyle_armor.region_box("torso")
    assert lo[2] <= 1.06, f"torso box floor {lo[2]} is above the spine base"
    assert hi[2] >= 1.43, f"torso box ceiling {hi[2]} is below the upper chest"


def test_restyle_armor_fit_spans_region_plus_inflation_no_void():
    """The fitted plate AABB provably spans the region inflated outward + up.

    A raw sculpt AABB mapped through the fit transform must land exactly on the
    region box grown by ``inflate`` on every axis and by ``up_extend`` on the top
    of the up-axis — so the plate covers the torso with no gap (no void) and
    reaches up to bridge the shoulder seam, independent of the sculpt's shape.
    """
    lo, hi = restyle_armor.region_box("torso")
    mesh_min = (-2.0, -3.0, 5.0)  # deliberately arbitrary raw-sculpt AABB
    mesh_max = (4.0, 1.0, 9.0)
    inflate, up_extend, up_axis = 0.06, 0.07, 2
    scale, offset = restyle_armor.fit_region_transform(
        mesh_min,
        mesh_max,
        lo,
        hi,
        inflate=inflate,
        up_extend=up_extend,
        up_axis=up_axis,
    )
    fitted_min = tuple(mesh_min[i] * scale[i] + offset[i] for i in range(3))
    fitted_max = tuple(mesh_max[i] * scale[i] + offset[i] for i in range(3))
    for i in range(3):
        assert fitted_min[i] == pytest.approx(lo[i] - inflate, abs=1e-6)
        exp_hi = hi[i] + inflate + (up_extend if i == up_axis else 0.0)
        assert fitted_max[i] == pytest.approx(exp_hi, abs=1e-6)
    # The top of the plate reaches above the bare region ceiling (bridges the seam).
    assert fitted_max[up_axis] > hi[up_axis]


def test_restyle_armor_cylindrical_uv_wraps_and_climbs():
    """u wraps [0,1) around the vertical axis; v climbs 0→1 with height."""
    lo, hi = restyle_armor.region_box("torso")
    cx = (lo[0] + hi[0]) / 2.0
    cy = (lo[1] + hi[1]) / 2.0
    bottom = restyle_armor.cylindrical_uv((cx + 0.1, cy, lo[2]), lo, hi, up_axis=2)
    top = restyle_armor.cylindrical_uv((cx + 0.1, cy, hi[2]), lo, hi, up_axis=2)
    assert bottom[1] == pytest.approx(0.0, abs=1e-6)
    assert top[1] == pytest.approx(1.0, abs=1e-6)
    # A half-turn around the axis moves u by ~0.5.
    front = restyle_armor.cylindrical_uv((cx + 0.1, cy, hi[2]), lo, hi, up_axis=2)
    back = restyle_armor.cylindrical_uv((cx - 0.1, cy, hi[2]), lo, hi, up_axis=2)
    assert abs(front[0] - back[0]) == pytest.approx(0.5, abs=1e-6)
    for uv in (bottom, top, front, back):
        assert 0.0 <= uv[0] < 1.0 and 0.0 <= uv[1] <= 1.0


def test_restyle_armor_uv_normalized_against_fitted_bounds_not_prefit_box():
    """v must be normalized against the mesh's fitted bounds, not the pre-fit box.

    The mesh occupies the region grown by inflate (all axes) + up_extend (top of the
    up-axis). Normalizing v against the PRE-FIT box sends the margin + shoulder-bridge
    geometry outside [0,1] where it CLAMPS (the shipped regression: >50% at v=0). This
    guards the pure invariant: over the FITTED span, v climbs 0→1 with no clamped bulk.
    """
    lo, hi = restyle_armor.region_box("torso")
    inflate, up_extend, up_axis = 0.06, 0.07, 2
    fit_lo = tuple(lo[i] - inflate for i in range(3))
    fit_hi = tuple(
        hi[i] + inflate + (up_extend if i == up_axis else 0.0) for i in range(3)
    )
    cx = (fit_lo[0] + fit_hi[0]) / 2.0
    cy = (fit_lo[1] + fit_hi[1]) / 2.0

    # WRONG (pre-fit box): the fitted bottom + top land outside [0,1] → clamp.
    wrong_bottom = restyle_armor.cylindrical_uv((cx, cy, fit_lo[2]), lo, hi, up_axis)
    wrong_top = restyle_armor.cylindrical_uv((cx, cy, fit_hi[2]), lo, hi, up_axis)
    assert wrong_bottom[1] == 0.0 and wrong_top[1] == 1.0  # both clamp (info lost)

    # RIGHT (fitted bounds): the same physical extremes map to exactly 0 and 1, and
    # every interior height maps strictly inside — no bulk clamping.
    right_bottom = restyle_armor.cylindrical_uv(
        (cx, cy, fit_lo[2]), fit_lo, fit_hi, up_axis
    )
    right_top = restyle_armor.cylindrical_uv(
        (cx, cy, fit_hi[2]), fit_lo, fit_hi, up_axis
    )
    assert right_bottom[1] == pytest.approx(0.0, abs=1e-6)
    assert right_top[1] == pytest.approx(1.0, abs=1e-6)
    for frac in (0.1, 0.25, 0.5, 0.75, 0.9):  # interior heights are unclamped
        z = fit_lo[2] + frac * (fit_hi[2] - fit_lo[2])
        v = restyle_armor.cylindrical_uv((cx, cy, z), fit_lo, fit_hi, up_axis)[1]
        assert v == pytest.approx(frac, abs=1e-6)


@pytest.mark.integration
def test_chest_glb_dye_uv_v_spans_full_range_without_bulk_clamp():
    """The shipped cuirass dye UV v spans ~[0,1] with <5% clamped at either extreme.

    Regression guard for the fit→UV integration bug (#595 review): v was normalized
    against the pre-fit region box while the mesh occupies the inflated + up-extended
    envelope, so 52.3% of verts (concentrated in the shoulder-bridge geometry) clamped
    to v=0 and the height-banded dye mask degenerated to flat colour over half the
    plate. Normalizing against the mesh's real fitted bounds fixes it — the whole mesh
    maps across the mask's full 0..1 range.
    """
    if not _chest_present_and_smudged():
        pytest.skip(f"{CHEST_GLB.name} missing or an unsmudged LFS pointer")
    import struct

    from pygltflib import GLTF2

    g = GLTF2().load(str(CHEST_GLB))
    blob = g.binary_blob()
    prim = g.meshes[0].primitives[0]
    acc = g.accessors[prim.attributes.TEXCOORD_0]
    bv = g.bufferViews[acc.bufferView]
    base = (bv.byteOffset or 0) + (acc.byteOffset or 0)
    stride = bv.byteStride or 8
    vs = [
        struct.unpack_from("<2f", blob, base + i * stride)[1] for i in range(acc.count)
    ]
    n = len(vs)
    clamp_lo = sum(1 for v in vs if v <= 1e-6) / n
    clamp_hi = sum(1 for v in vs if v >= 1.0 - 1e-6) / n
    assert min(vs) < 0.05 and max(vs) > 0.95, (
        f"dye UV v does not span [0,1]: min={min(vs):.3f} max={max(vs):.3f}"
    )
    assert clamp_lo < 0.05, (
        f"{clamp_lo:.1%} of verts clamp at v=0 (was 52.3% before the fix)"
    )
    assert clamp_hi < 0.05, f"{clamp_hi:.1%} of verts clamp at v=1"


def test_restyle_armor_nearest_bind_bone_picks_by_height():
    """A point near the spine base binds Spine; near the top binds UpperChest."""
    bind = ("Spine", "Chest", "UpperChest")
    # Blender Z-up; spine base ~Z 1.11 (Spine mid), upper chest ~Z 1.38.
    assert restyle_armor.nearest_bind_bone((0.0, 0.0, 1.10), bind) == "Spine"
    assert restyle_armor.nearest_bind_bone((0.0, 0.0, 1.40), bind) == "UpperChest"


def test_restyle_armor_parse_args_defaults_to_chest():
    ns = restyle_armor.parse_args(["--in", "raw.glb"])
    assert ns.in_glb == "raw.glb"
    assert ns.region == "chest"
    assert ns.out == restyle_armor.DEFAULT_OUT
    assert ns.body_glb == restyle_armor.DEFAULT_BODY_GLB
    with pytest.raises(SystemExit):
        restyle_armor.parse_args([])  # --in is required


def test_restyle_armor_read_glb_aabb_missing_mesh_returns_none():
    """A missing file or absent mesh yields None (caller falls back to the nominal box)."""
    assert (
        restyle_armor._read_glb_mesh_aabb("/nonexistent.glb", "geo_torso_lod0") is None
    )


BODY_BASE_GLB = REPO / "content/core/assets/art/char/sk_ardent_male_base.glb"


@pytest.mark.integration
def test_restyle_armor_body_region_box_is_wider_than_nominal():
    """The real torso surface is WIDER (X) than the bone-group box — so fitting to
    it (not the nominal box) makes the cuirass sit outside the body with no void."""
    if BODY_BASE_GLB.is_file() and _is_lfs_pointer(BODY_BASE_GLB):
        pytest.skip("body base .glb is an unsmudged LFS pointer")
    body = restyle_armor.body_region_box(str(BODY_BASE_GLB), "torso")
    if body is None:
        pytest.skip("body torso geoset unavailable")
    nom_lo, nom_hi = restyle_armor.region_box("torso")
    b_lo, b_hi = body
    # X half-width from the real surface exceeds the nominal shoulder-bone span.
    assert (b_hi[0] - b_lo[0]) > (nom_hi[0] - nom_lo[0]), (
        "body torso surface should be wider in X than the nominal bone-group box"
    )
    # Height (Blender Z) brackets the spine column.
    assert b_lo[2] <= 1.12 and b_hi[2] >= 1.42


# --- committed warden_chest .glb structural tests (spec ⑤/S4, #595) -----------

CHEST_GLB = REPO / "content/core/assets/art/item/armor/warden_chest.glb"


def _chest_present_and_smudged() -> bool:
    return CHEST_GLB.is_file() and not _is_lfs_pointer(CHEST_GLB)


@pytest.mark.integration
def test_chest_glb_binds_only_canonical_torso_bones():
    """I021/E100: the cuirass skin binds only canonical bones, incl. the spine column."""
    if not _chest_present_and_smudged():
        pytest.skip(f"{CHEST_GLB.name} missing or an unsmudged LFS pointer")
    from pygltflib import GLTF2

    g = GLTF2().load(str(CHEST_GLB))
    assert g.skins, f"{CHEST_GLB.name} carries no skin"
    joints = set()
    for skin in g.skins:
        for j in skin.joints or []:
            joints.add(g.nodes[j].name)
    canonical = set(bones.bone_names())
    assert joints - canonical == set(), (
        f"{CHEST_GLB.name} binds non-canonical joints: {sorted(joints - canonical)}"
    )
    # At least one bound joint is a torso-column bone the cuirass rides.
    assert joints & {"Spine", "Chest", "UpperChest"}, (
        f"{CHEST_GLB.name} does not bind any torso-column bone"
    )


@pytest.mark.integration
def test_chest_glb_is_within_the_armor_budget_band():
    """L070 / Art PRD §2.1: the cuirass is 3–8k tris (real plate, not a blockout)."""
    if not _chest_present_and_smudged():
        pytest.skip(f"{CHEST_GLB.name} missing or an unsmudged LFS pointer")
    from pygltflib import GLTF2

    g = GLTF2().load(str(CHEST_GLB))
    tris = 0
    for mesh in g.meshes:
        for prim in mesh.primitives:
            if prim.indices is not None:
                tris += g.accessors[prim.indices].count // 3
            else:
                tris += g.accessors[prim.attributes.POSITION].count // 3
    assert 3_000 <= tris <= 8_000, (
        f"{CHEST_GLB.name} has {tris} tris (must be 3,000..8,000)"
    )


@pytest.mark.integration
def test_chest_glb_mesh_is_not_geoset_named():
    """E104: the cuirass mesh must not use geo_<region> geoset naming (it is gear)."""
    if not _chest_present_and_smudged():
        pytest.skip(f"{CHEST_GLB.name} missing or an unsmudged LFS pointer")
    from pygltflib import GLTF2

    g = GLTF2().load(str(CHEST_GLB))
    for mesh in g.meshes:
        assert not (mesh.name or "").startswith("geo_"), (
            f"{CHEST_GLB.name} mesh '{mesh.name}' is geoset-named (forbidden for gear)"
        )
