"""Tests for meridian_rig — the canonical bone table (spec ④ §2) and the
committed reference rig .glb it generates."""
import sys
from pathlib import Path

import pytest
import yaml

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools" / "blender" / "meridian_rig"))
import blender_pin  # noqa: E402
import bones  # noqa: E402
import generate_rig  # noqa: E402

# The committed reference rig. Generated by generate_rig.py under Blender and
# stored via Git LFS; the structural tests below read it back with pygltflib so
# they run in CI without a Blender install.
RIG_GLB = REPO / "content/core/assets/art/char/sk_ardent_male_skeleton.glb"


def _is_lfs_pointer(path: Path) -> bool:
    """True when `path` is an unsmudged Git-LFS pointer rather than a real .glb.

    CI checks out without `lfs: true`, so the binary is a small text pointer
    there; the structural tests skip in that case and run locally (and on any
    LFS-smudged checkout) against the real geometry.
    """
    try:
        with open(path, "rb") as fh:
            return fh.read(64).startswith(b"version https://git-lfs")
    except FileNotFoundError:
        return False


skip_if_pointer = pytest.mark.skipif(
    _is_lfs_pointer(RIG_GLB),
    reason="rig .glb is an unsmudged LFS pointer (CI checkout without LFS smudge)",
)


def test_bone_count_is_63():
    assert len(bones.ALL_BONES) == 63
    assert len(bones.PROFILE_BONES) == 56
    assert len(bones.SOCKET_BONES) == 7

def test_hierarchy_is_wellformed_single_root():
    h = bones.hierarchy()
    roots = [n for n, p in h.items() if p is None]
    assert roots == ["Root"]
    names = set(h)
    assert all(p in names for p in h.values() if p is not None)

def test_socket_parents_match_spec():
    parents = {b.name: b.parent for b in bones.SOCKET_BONES}
    assert parents == {
        "socket_main_hand": "RightHand", "socket_off_hand": "LeftHand",
        "socket_shield": "LeftHand", "socket_back": "Chest",
        "socket_ranged": "Chest", "socket_hip_l": "Hips", "socket_hip_r": "Hips"}

def test_skeleton_defs_bones_matches_table():
    """Drift guard: schema/content/skeleton.defs.yaml bones == bones.py names."""
    defs = yaml.safe_load((REPO / "schema/content/skeleton.defs.yaml").read_text())
    assert defs["$defs"]["boneName"]["enum"] == bones.bone_names()

def test_unknown_profile_raises():
    with pytest.raises(ValueError, match="ardent_male"):
        bones.for_profile("dwarf_female")


# ---------------------------------------------------------------------------
# generate_rig — pure argument/path helpers (importable without bpy).
# ---------------------------------------------------------------------------
def test_yup_to_blender_maps_gltf_yup_to_blender_zup():
    # Table/glTF Y-up (x, y, z) -> Blender Z-up (x, -z, y); the exporter's
    # +Y-up conversion maps it back, so table coords round-trip exactly.
    assert generate_rig.yup_to_blender((1.0, 2.0, 3.0)) == (1.0, -3.0, 2.0)
    assert generate_rig.yup_to_blender((0.0, 0.95, 0.0)) == (0.0, 0.0, 0.95)


def test_argv_after_ddash_extracts_generator_args():
    argv = ["blender", "--background", "--python", "generate_rig.py",
            "--", "--profile", "ardent_male", "--out", "x.glb"]
    assert generate_rig.argv_after_ddash(argv) == [
        "--profile", "ardent_male", "--out", "x.glb"]


def test_argv_after_ddash_empty_when_no_separator():
    assert generate_rig.argv_after_ddash(["blender", "--background"]) == []


def test_parse_args_defaults_to_ardent_male():
    ns = generate_rig.parse_args([])
    assert ns.profile == "ardent_male"
    assert ns.out.endswith("sk_ardent_male_skeleton.glb")


def test_parse_args_reads_profile_and_out():
    ns = generate_rig.parse_args(["--profile", "ardent_male", "--out", "/tmp/r.glb"])
    assert ns.profile == "ardent_male"
    assert ns.out == "/tmp/r.glb"


def test_parse_args_rejects_unknown_profile():
    with pytest.raises(SystemExit):
        generate_rig.parse_args(["--profile", "dwarf_female"])


def test_parse_args_allow_unpinned_blender_defaults_false():
    ns = generate_rig.parse_args([])
    assert ns.allow_unpinned_blender is False


def test_parse_args_allow_unpinned_blender_flag():
    ns = generate_rig.parse_args(["--allow-unpinned-blender"])
    assert ns.allow_unpinned_blender is True


# ---------------------------------------------------------------------------
# blender_pin.check_pin — pure Blender version-pin comparison (spec ④ §9).
# ---------------------------------------------------------------------------
def test_check_pin_matching_version_returns_none():
    assert blender_pin.check_pin((5, 0, 0), "5.0.0") is None


def test_check_pin_uses_module_pinned_version_by_default():
    # blender_pin.PINNED_VERSION is the single source of truth entry points
    # actually enforce (tools/blender/README.md documents it, doesn't define it).
    pinned = tuple(int(p) for p in blender_pin.PINNED_VERSION.split("."))
    assert blender_pin.check_pin(pinned) is None


def test_check_pin_mismatch_names_both_versions():
    error = blender_pin.check_pin((4, 2, 1), "5.0.0")
    assert error is not None
    assert "5.0.0" in error
    assert "4.2.1" in error


def test_check_pin_mismatch_on_patch_version_only():
    error = blender_pin.check_pin((5, 0, 1), "5.0.0")
    assert error is not None
    assert "5.0.0" in error
    assert "5.0.1" in error


def test_check_pin_malformed_pinned_string():
    error = blender_pin.check_pin((5, 0, 0), "not-a-version")
    assert error is not None
    assert "malformed" in error
    assert "not-a-version" in error


def test_check_pin_malformed_pinned_wrong_arity():
    error = blender_pin.check_pin((5, 0, 0), "5.0")
    assert error is not None
    assert "malformed" in error


def test_check_pin_malformed_version_tuple():
    error = blender_pin.check_pin(("a", "b", "c"), "5.0.0")
    assert error is not None
    assert "malformed" in error


def test_check_pin_malformed_version_tuple_wrong_arity():
    error = blender_pin.check_pin((5, 0), "5.0.0")
    assert error is not None
    assert "malformed" in error


# ---------------------------------------------------------------------------
# Structural checks on the committed reference rig .glb (read back, no Blender).
# ---------------------------------------------------------------------------
def _load_rig_gltf():
    from pygltflib import GLTF2

    return GLTF2().load(str(RIG_GLB))


@pytest.mark.integration
@skip_if_pointer
def test_rig_glb_bone_names_match_table():
    g = _load_rig_gltf()
    node_names = {n.name for n in g.nodes}
    missing = set(bones.bone_names()) - node_names
    assert not missing, f"bones absent from exported .glb: {sorted(missing)}"


@pytest.mark.integration
@skip_if_pointer
def test_rig_glb_hierarchy_matches_table():
    g = _load_rig_gltf()
    child_to_parent: dict[str, str] = {}
    for n in g.nodes:
        for c in n.children or []:
            child_to_parent[g.nodes[c].name] = n.name
    for name, parent in bones.hierarchy().items():
        if parent is not None:
            assert child_to_parent.get(name) == parent, name


def _quat_to_mat3(q):
    """glTF quaternion [x, y, z, w] -> 3x3 rotation matrix (row-major)."""
    x, y, z, w = q
    return [
        [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
        [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
        [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
    ]


def _global_positions(g) -> dict[str, tuple[float, float, float]]:
    """Compose each node's TRS down the scene graph -> global joint positions."""
    def local_mat(n):
        r = _quat_to_mat3(n.rotation or [0.0, 0.0, 0.0, 1.0])
        t = n.translation or [0.0, 0.0, 0.0]
        s = n.scale or [1.0, 1.0, 1.0]
        return [[r[i][j] * s[j] for j in range(3)] + [t[i]] for i in range(3)] + [
            [0.0, 0.0, 0.0, 1.0]]

    def matmul(a, b):
        return [[sum(a[i][k] * b[k][j] for k in range(4)) for j in range(4)]
                for i in range(4)]

    out: dict[str, tuple[float, float, float]] = {}

    def walk(node_idx: int, parent):
        n = g.nodes[node_idx]
        m = matmul(parent, local_mat(n))
        if n.name:
            out[n.name] = (m[0][3], m[1][3], m[2][3])
        for c in n.children or []:
            walk(c, m)

    identity = [[float(i == j) for j in range(4)] for i in range(4)]
    for root in g.scenes[g.scene].nodes:
        walk(root, identity)
    return out


@pytest.mark.integration
@skip_if_pointer
def test_rig_glb_rest_transforms_match_table():
    """Each joint's composed global rest position == the table's head_m (Y-up).

    Spec ④ §2.2 contract: names/hierarchy/REST TRANSFORMS survive the export.
    glTF stores joints (bone heads); tails are Blender-side authoring detail.
    """
    g = _load_rig_gltf()
    pos = _global_positions(g)
    for spec in bones.ALL_BONES:
        got = pos[spec.name]
        for axis, (a, b) in enumerate(zip(got, spec.head_m)):
            assert abs(a - b) < 1e-4, (
                f"{spec.name} axis {axis}: exported {got} != table {spec.head_m}")


@pytest.mark.integration
@skip_if_pointer
def test_rig_glb_has_single_bone_root():
    """Exactly one table bone (Root) has no bone parent inside the armature."""
    g = _load_rig_gltf()
    child_to_parent: dict[str, str] = {}
    for n in g.nodes:
        for c in n.children or []:
            child_to_parent[g.nodes[c].name] = n.name
    table = set(bones.bone_names())
    unparented = {b for b in table if child_to_parent.get(b) not in table}
    assert unparented == {"Root"}, unparented


# ---------------------------------------------------------------------------
# generate_blockout — pure helpers (importable without bpy) + structural checks
# on the committed greybox blockout body .glb (spec ④ §6 / T5).
# ---------------------------------------------------------------------------
import generate_blockout  # noqa: E402

BODY_GLB = REPO / "content/core/assets/art/char/sk_ardent_male_base.glb"

skip_if_body_pointer = pytest.mark.skipif(
    _is_lfs_pointer(BODY_GLB),
    reason="body .glb is an unsmudged LFS pointer (CI checkout without LFS smudge)",
)

GEOSET_REGIONS = ["head", "hands", "forearms", "torso", "waist", "hips_legs",
                  "lower_legs", "feet"]


def test_blockout_region_groups_cover_exactly_the_8_geoset_regions():
    """Drift guard: region keys == skeleton.defs.yaml $defs.geosetRegion.enum."""
    defs = yaml.safe_load((REPO / "schema/content/skeleton.defs.yaml").read_text())
    assert sorted(generate_blockout.region_bone_groups()) == sorted(
        defs["$defs"]["geosetRegion"]["enum"])


def test_blockout_region_groups_use_only_canonical_bones():
    canonical = set(bones.bone_names())
    for region, groups in generate_blockout.region_bone_groups().items():
        for group in groups:
            assert group, f"{region} has an empty bone group"
            unknown = set(group) - canonical
            assert not unknown, f"{region} names unknown bones: {sorted(unknown)}"


def test_blockout_mesh_name_follows_geoset_convention():
    assert generate_blockout.mesh_name("head") == "geo_head_lod0"
    assert generate_blockout.mesh_name("hips_legs") == "geo_hips_legs_lod0"


def test_blockout_group_bbox_encloses_bones_with_min_radius():
    lo, hi = generate_blockout.group_bbox(["Head", "Neck"], radius=0.11)
    # Neck head y=1.44, Head tail y=1.72 — box spans at least that.
    assert lo[1] <= 1.44 and hi[1] >= 1.72
    # X span of the chain is 0 — the radius guarantees >= 0.11 half-extent.
    assert (hi[0] - lo[0]) / 2.0 >= 0.11 - 1e-9


def test_blockout_parse_args_defaults():
    ns = generate_blockout.parse_args([])
    assert ns.profile == "ardent_male"
    assert ns.out.endswith("sk_ardent_male_base.glb")


def test_blockout_parse_args_rejects_unknown_profile():
    with pytest.raises(SystemExit):
        generate_blockout.parse_args(["--profile", "dwarf_female"])


def _load_body_gltf():
    from pygltflib import GLTF2

    return GLTF2().load(str(BODY_GLB))


def _read_accessor_vec4(g, accessor_idx):
    """Decode a VEC4 accessor from the .glb binary blob -> list of 4-tuples."""
    import struct

    acc = g.accessors[accessor_idx]
    bv = g.bufferViews[acc.bufferView]
    blob = g.binary_blob()
    fmt_by_component = {5121: "B", 5123: "H", 5125: "I", 5126: "f"}
    fmt = fmt_by_component[acc.componentType]
    elem_size = struct.calcsize(fmt) * 4
    stride = bv.byteStride or elem_size
    base = (bv.byteOffset or 0) + (acc.byteOffset or 0)
    out = []
    for i in range(acc.count):
        off = base + i * stride
        out.append(struct.unpack_from("<" + fmt * 4, blob, off))
    return out


@pytest.mark.integration
@skip_if_body_pointer
def test_body_glb_mesh_names_are_exactly_the_8_lod0_geosets():
    g = _load_body_gltf()
    got = sorted(m.name for m in g.meshes)
    want = sorted(f"geo_{r}_lod0" for r in GEOSET_REGIONS)
    assert got == want, f"mesh names {got} != expected geosets {want}"


@pytest.mark.integration
@skip_if_body_pointer
def test_body_glb_skin_joints_are_exactly_the_canonical_bone_set():
    """I020: every skin joint is canonical AND the full 63-bone set is bound."""
    g = _load_body_gltf()
    assert g.skins, "body .glb carries no skin"
    joint_names = set()
    for skin in g.skins:
        for j in skin.joints or []:
            joint_names.add(g.nodes[j].name)
    canonical = set(bones.bone_names())
    assert joint_names - canonical == set(), (
        f"non-canonical joints: {sorted(joint_names - canonical)}")
    assert canonical - joint_names == set(), (
        f"canonical bones missing from skin: {sorted(canonical - joint_names)}")


@pytest.mark.integration
@skip_if_body_pointer
def test_body_glb_vertices_have_at_most_4_influences():
    """E103/spec ④ §6: one JOINTS_0/WEIGHTS_0 set only — no JOINTS_1 spillover."""
    g = _load_body_gltf()
    for mesh in g.meshes:
        for prim in mesh.primitives:
            attrs = prim.attributes
            assert attrs.JOINTS_0 is not None, f"{mesh.name} is not skinned"
            assert attrs.WEIGHTS_0 is not None, f"{mesh.name} has no weights"
            assert getattr(attrs, "JOINTS_1", None) is None, (
                f"{mesh.name} carries a second influence set (>4 influences)")


@pytest.mark.integration
@skip_if_body_pointer
def test_body_glb_weights_are_normalized():
    g = _load_body_gltf()
    for mesh in g.meshes:
        for prim in mesh.primitives:
            weights = _read_accessor_vec4(g, prim.attributes.WEIGHTS_0)
            comp = g.accessors[prim.attributes.WEIGHTS_0].componentType
            scale = 1.0 if comp == 5126 else (255.0 if comp == 5121 else 65535.0)
            for i, w in enumerate(weights):
                total = sum(w) / scale
                assert abs(total - 1.0) < 5e-3, (
                    f"{mesh.name} vertex {i} weight sum {total}")
