"""Tests for meridian_rig — the canonical bone table (spec ④ §2) and the
committed reference rig .glb it generates."""

import re
import sys
from pathlib import Path

import pytest
import yaml

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools" / "blender" / "meridian_rig"))
import blender_pin  # noqa: E402
import bones  # noqa: E402
import generate_rig  # noqa: E402
import retarget_clip  # noqa: E402
import restyle_armor  # noqa: E402
import restyle_body  # noqa: E402
import restyle_hair  # noqa: E402
import restyle_weapon  # noqa: E402

# The committed reference rig. Generated by generate_rig.py under Blender and
# stored via Git LFS; the structural tests below read it back with pygltflib so
# they run in CI without a Blender install.
RIG_GLB = REPO / "content/core/assets/art/char/sk_ardent_male_skeleton.glb"


def _is_lfs_pointer(path: Path) -> bool:
    """True when `path` is an unsmudged Git-LFS pointer rather than a real .glb.

    CI checks out without `lfs: true`, so the binary is a small text pointer
    there; the structural tests skip in that case and run locally (and on any
    LFS-smudged checkout) against the real geometry.
    """
    try:
        with open(path, "rb") as fh:
            return fh.read(64).startswith(b"version https://git-lfs")
    except FileNotFoundError:
        return False


skip_if_pointer = pytest.mark.skipif(
    _is_lfs_pointer(RIG_GLB),
    reason="rig .glb is an unsmudged LFS pointer (CI checkout without LFS smudge)",
)


def test_bone_count_is_63():
    assert len(bones.ALL_BONES) == 63
    assert len(bones.PROFILE_BONES) == 56
    assert len(bones.SOCKET_BONES) == 7


def test_hierarchy_is_wellformed_single_root():
    h = bones.hierarchy()
    roots = [n for n, p in h.items() if p is None]
    assert roots == ["Root"]
    names = set(h)
    assert all(p in names for p in h.values() if p is not None)


def test_socket_parents_match_spec():
    parents = {b.name: b.parent for b in bones.SOCKET_BONES}
    assert parents == {
        "socket_main_hand": "RightHand",
        "socket_off_hand": "LeftHand",
        "socket_shield": "LeftHand",
        "socket_back": "Chest",
        "socket_ranged": "Chest",
        "socket_hip_l": "Hips",
        "socket_hip_r": "Hips",
    }


def test_skeleton_defs_bones_matches_table():
    """Drift guard: schema/content/skeleton.defs.yaml bones == bones.py names."""
    defs = yaml.safe_load((REPO / "schema/content/skeleton.defs.yaml").read_text())
    assert defs["$defs"]["boneName"]["enum"] == bones.bone_names()


def test_unknown_profile_raises():
    with pytest.raises(ValueError, match="ardent_male"):
        bones.for_profile("dwarf_female")


# ---------------------------------------------------------------------------
# Proportion profiles (spec ④ "proportions are parameters"; Race #2 / Dolmen).
# The shared-skeleton contract: every profile carries the IDENTICAL 63 bone
# names + parent hierarchy and differs only in rest transforms, so gear authored
# on one race binds to another by bone name.
# ---------------------------------------------------------------------------
def _max_height(profile: str) -> float:
    """Crown height = the tallest head/tail Y across a profile's bones."""
    specs = bones.for_profile(profile)
    return max(max(b.head_m[1], b.tail_m[1]) for b in specs)


def _max_half_width(profile: str) -> float:
    """Broadest reach from the centre line = the largest |X| across a profile."""
    specs = bones.for_profile(profile)
    return max(max(abs(b.head_m[0]), abs(b.tail_m[0])) for b in specs)


def test_valid_profiles_includes_ardent_and_dolmen():
    assert "ardent_male" in bones.VALID_PROFILES
    assert "dolmen_male" in bones.VALID_PROFILES


def test_dolmen_profile_returns_full_63_bone_table():
    """for_profile now yields all 63 bones (56 profile + 7 sockets) per profile."""
    assert len(bones.for_profile("dolmen_male")) == 63
    assert len(bones.for_profile("ardent_male")) == 63


def test_dolmen_bone_names_identical_to_ardent():
    """Shared-skeleton invariant: bone NAMES (and order) match ardent exactly."""
    assert bones.bone_names("dolmen_male") == bones.bone_names("ardent_male")


def test_dolmen_hierarchy_identical_to_ardent():
    """Shared-skeleton invariant: every bone's parent matches ardent exactly."""
    assert bones.hierarchy("dolmen_male") == bones.hierarchy("ardent_male")


def test_dolmen_rest_transforms_actually_differ_from_ardent():
    """Proportions really changed: at least one joint sits at a new position."""
    ardent = {b.name: b for b in bones.for_profile("ardent_male")}
    dolmen = {b.name: b for b in bones.for_profile("dolmen_male")}
    assert any(
        dolmen[name].head_m != ardent[name].head_m
        or dolmen[name].tail_m != ardent[name].tail_m
        for name in ardent
    )


def test_dolmen_is_shorter_than_ardent():
    """Dolmen = "mountain/stone folk": lower total height (~0.86–0.90x)."""
    ratio = _max_height("dolmen_male") / _max_height("ardent_male")
    assert ratio < 1.0, "Dolmen must be shorter than Ardent"
    assert 0.86 <= ratio <= 0.90, f"Dolmen height ratio {ratio:.3f} outside 0.86–0.90x"


def test_dolmen_is_broader_than_ardent():
    """Dolmen is stockier: wider shoulder/hip span than Ardent."""
    assert _max_half_width("dolmen_male") > _max_half_width("ardent_male")


def test_dolmen_legs_shortened_more_than_torso():
    """Legs compress harder than the torso — the stocky, low-slung stance."""
    ardent = {b.name: b for b in bones.for_profile("ardent_male")}
    dolmen = {b.name: b for b in bones.for_profile("dolmen_male")}
    # Leg span (hip joint -> ankle) shrinks more than the spine column.
    ard_leg = ardent["RightUpperLeg"].head_m[1] - ardent["RightFoot"].head_m[1]
    dol_leg = dolmen["RightUpperLeg"].head_m[1] - dolmen["RightFoot"].head_m[1]
    ard_torso = ardent["Neck"].head_m[1] - ardent["Hips"].head_m[1]
    dol_torso = dolmen["Neck"].head_m[1] - dolmen["Hips"].head_m[1]
    assert (dol_leg / ard_leg) < (dol_torso / ard_torso)


def test_dolmen_stays_a_valid_humanoid_tpose():
    """Feet stay on/above the floor and the +/-X mirror survives the transform."""
    dolmen = {b.name: b for b in bones.for_profile("dolmen_male")}
    # No joint sinks below the ground plane.
    assert min(b.head_m[1] for b in dolmen.values()) >= 0.0
    # Left/right mirror preserved: paired bones are exact +/-X reflections.
    for right, left in (("RightHand", "LeftHand"), ("RightUpperLeg", "LeftUpperLeg")):
        rh, lh = dolmen[right].head_m, dolmen[left].head_m
        assert rh[0] == pytest.approx(-lh[0]) and rh[1:] == lh[1:]


def test_dolmen_sockets_ride_the_profiles_hand():
    """D4 mechanism: socket mounts scale with the profile (not stuck at Ardent).

    socket_main_hand's head equals RightHand's tail in every profile, so a
    weapon socketed to the Dolmen hand sits on the Dolmen hand — the shared
    sockets follow the proportions automatically.
    """
    for profile in ("ardent_male", "dolmen_male"):
        specs = {b.name: b for b in bones.for_profile(profile)}
        assert specs["socket_main_hand"].head_m == specs["RightHand"].tail_m
    # And the Dolmen socket is genuinely relocated vs Ardent (broader/shorter).
    ard = {b.name: b for b in bones.for_profile("ardent_male")}
    dol = {b.name: b for b in bones.for_profile("dolmen_male")}
    assert dol["socket_main_hand"].head_m != ard["socket_main_hand"].head_m


# ---------------------------------------------------------------------------
# Chibi profile (spec ⑤ chibi theme, epic #722 / story #745). The keystone body
# is a compact rounded PILL: the reference ardent_male arm span reaches far
# outside that little volume, leaving the arm/hand geosets uncovered and forcing
# floating proxy-box fallbacks. The chibi map pulls every limb joint inside the
# pill. It is still just one more per-profile point transform, so the same
# shared-skeleton invariants (identical 63 names + hierarchy) must hold.
# ---------------------------------------------------------------------------
def test_valid_profiles_includes_chibi():
    assert "chibi" in bones.VALID_PROFILES


def test_chibi_profile_returns_full_63_bone_table():
    assert len(bones.for_profile("chibi")) == 63


def test_chibi_bone_names_identical_to_ardent():
    """Shared-skeleton invariant: bone NAMES (and order) match ardent exactly."""
    assert bones.bone_names("chibi") == bones.bone_names("ardent_male")


def test_chibi_hierarchy_identical_to_ardent():
    """Shared-skeleton invariant: every bone's parent matches ardent exactly."""
    assert bones.hierarchy("chibi") == bones.hierarchy("ardent_male")


def test_chibi_rest_transforms_actually_differ_from_ardent():
    """Proportions really changed: at least one joint sits at a new position."""
    ardent = {b.name: b for b in bones.for_profile("ardent_male")}
    chibi = {b.name: b for b in bones.for_profile("chibi")}
    assert any(
        chibi[name].head_m != ardent[name].head_m
        or chibi[name].tail_m != ardent[name].tail_m
        for name in ardent
    )


def test_chibi_arm_span_materially_smaller_than_ardent():
    """The bug + the fix: ardent's hands reach out near a full human arm-span, far
    outside the pill; chibi tucks them in. The hand-bone |X| must shrink a lot --
    the whole reason the arm/hand geosets stop falling back to floating proxy
    boxes."""
    ardent = {b.name: b for b in bones.for_profile("ardent_male")}
    chibi = {b.name: b for b in bones.for_profile("chibi")}
    ard_hand_x = abs(ardent["RightHand"].tail_m[0])
    chi_hand_x = abs(chibi["RightHand"].tail_m[0])
    assert chi_hand_x < ard_hand_x
    # "Materially" smaller: well under half ardent's full human reach — the chibi
    # hand reaches only out to the pill's little stubby T-pose arms, not human
    # arm-span, which is what keeps the arm/hand geosets off the proxy fallback.
    assert chi_hand_x < 0.45 * ard_hand_x


def test_chibi_is_much_more_compact_than_ardent():
    """Compact all round: shorter overall AND far narrower total span than ardent."""
    assert _max_height("chibi") < _max_height("ardent_male")
    assert _max_half_width("chibi") < 0.5 * _max_half_width("ardent_male")


def test_chibi_stays_a_valid_rest_pose():
    """No joint sinks below the floor, and the +/-X mirror survives the transform."""
    chibi = {b.name: b for b in bones.for_profile("chibi")}
    assert min(b.head_m[1] for b in chibi.values()) >= 0.0
    for right, left in (("RightHand", "LeftHand"), ("RightUpperLeg", "LeftUpperLeg")):
        rh, lh = chibi[right].head_m, chibi[left].head_m
        assert rh[0] == pytest.approx(-lh[0]) and rh[1:] == lh[1:]


def test_chibi_arm_and_leg_chains_stay_monotonic():
    """No kinked/crossed joints: the arm still runs outward in X and the leg still
    runs downward in Y, monotonically, after the compaction transform."""
    chibi = {b.name: b for b in bones.for_profile("chibi")}
    arm = ["RightShoulder", "RightUpperArm", "RightLowerArm", "RightHand"]
    arm_x = [chibi[n].head_m[0] for n in arm] + [chibi[arm[-1]].tail_m[0]]
    assert all(b >= a for a, b in zip(arm_x, arm_x[1:])), arm_x
    leg = ["RightUpperLeg", "RightLowerLeg", "RightFoot", "RightToes"]
    leg_y = [chibi[n].head_m[1] for n in leg] + [chibi[leg[-1]].tail_m[1]]
    assert all(b <= a for a, b in zip(leg_y, leg_y[1:])), leg_y


def test_chibi_sockets_ride_the_profiles_hand():
    """Shared sockets follow the compacted proportions (not stuck at ardent reach)."""
    specs = {b.name: b for b in bones.for_profile("chibi")}
    assert specs["socket_main_hand"].head_m == specs["RightHand"].tail_m
    ard = {b.name: b for b in bones.for_profile("ardent_male")}
    assert specs["socket_main_hand"].head_m != ard["socket_main_hand"].head_m


# ---------------------------------------------------------------------------
# generate_rig — pure argument/path helpers (importable without bpy).
# ---------------------------------------------------------------------------
def test_yup_to_blender_maps_gltf_yup_to_blender_zup():
    # Table/glTF Y-up (x, y, z) -> Blender Z-up (x, -z, y); the exporter's
    # +Y-up conversion maps it back, so table coords round-trip exactly.
    assert generate_rig.yup_to_blender((1.0, 2.0, 3.0)) == (1.0, -3.0, 2.0)
    assert generate_rig.yup_to_blender((0.0, 0.95, 0.0)) == (0.0, 0.0, 0.95)


def test_argv_after_ddash_extracts_generator_args():
    argv = [
        "blender",
        "--background",
        "--python",
        "generate_rig.py",
        "--",
        "--profile",
        "ardent_male",
        "--out",
        "x.glb",
    ]
    assert generate_rig.argv_after_ddash(argv) == [
        "--profile",
        "ardent_male",
        "--out",
        "x.glb",
    ]


def test_argv_after_ddash_empty_when_no_separator():
    assert generate_rig.argv_after_ddash(["blender", "--background"]) == []


def test_parse_args_defaults_to_ardent_male():
    ns = generate_rig.parse_args([])
    assert ns.profile == "ardent_male"
    assert ns.out.endswith("sk_ardent_male_skeleton.glb")


def test_parse_args_reads_profile_and_out():
    ns = generate_rig.parse_args(["--profile", "ardent_male", "--out", "/tmp/r.glb"])
    assert ns.profile == "ardent_male"
    assert ns.out == "/tmp/r.glb"


def test_parse_args_rejects_unknown_profile():
    with pytest.raises(SystemExit):
        generate_rig.parse_args(["--profile", "dwarf_female"])


def test_parse_args_allow_unpinned_blender_defaults_false():
    ns = generate_rig.parse_args([])
    assert ns.allow_unpinned_blender is False


def test_parse_args_allow_unpinned_blender_flag():
    ns = generate_rig.parse_args(["--allow-unpinned-blender"])
    assert ns.allow_unpinned_blender is True


# ---------------------------------------------------------------------------
# blender_pin.check_pin — pure Blender version-pin comparison (spec ④ §9).
# ---------------------------------------------------------------------------
def test_check_pin_matching_version_returns_none():
    assert blender_pin.check_pin((5, 0, 0), "5.0.0") is None


def test_check_pin_uses_module_pinned_version_by_default():
    # blender_pin.PINNED_VERSION is the single source of truth entry points
    # actually enforce (tools/blender/README.md documents it, doesn't define it).
    pinned = tuple(int(p) for p in blender_pin.PINNED_VERSION.split("."))
    assert blender_pin.check_pin(pinned) is None


def test_check_pin_mismatch_names_both_versions():
    error = blender_pin.check_pin((4, 2, 1), "5.0.0")
    assert error is not None
    assert "5.0.0" in error
    assert "4.2.1" in error


def test_check_pin_mismatch_on_patch_version_only():
    error = blender_pin.check_pin((5, 0, 1), "5.0.0")
    assert error is not None
    assert "5.0.0" in error
    assert "5.0.1" in error


def test_check_pin_malformed_pinned_string():
    error = blender_pin.check_pin((5, 0, 0), "not-a-version")
    assert error is not None
    assert "malformed" in error
    assert "not-a-version" in error


def test_check_pin_malformed_pinned_wrong_arity():
    error = blender_pin.check_pin((5, 0, 0), "5.0")
    assert error is not None
    assert "malformed" in error


def test_check_pin_malformed_version_tuple():
    error = blender_pin.check_pin(("a", "b", "c"), "5.0.0")
    assert error is not None
    assert "malformed" in error


def test_check_pin_malformed_version_tuple_wrong_arity():
    error = blender_pin.check_pin((5, 0), "5.0.0")
    assert error is not None
    assert "malformed" in error


# ---------------------------------------------------------------------------
# Structural checks on the committed reference rig .glb (read back, no Blender).
# ---------------------------------------------------------------------------
def _load_rig_gltf():
    from pygltflib import GLTF2

    return GLTF2().load(str(RIG_GLB))


@pytest.mark.integration
@skip_if_pointer
def test_rig_glb_bone_names_match_table():
    g = _load_rig_gltf()
    node_names = {n.name for n in g.nodes}
    missing = set(bones.bone_names()) - node_names
    assert not missing, f"bones absent from exported .glb: {sorted(missing)}"


@pytest.mark.integration
@skip_if_pointer
def test_rig_glb_hierarchy_matches_table():
    g = _load_rig_gltf()
    child_to_parent: dict[str, str] = {}
    for n in g.nodes:
        for c in n.children or []:
            child_to_parent[g.nodes[c].name] = n.name
    for name, parent in bones.hierarchy().items():
        if parent is not None:
            assert child_to_parent.get(name) == parent, name


def _quat_to_mat3(q):
    """glTF quaternion [x, y, z, w] -> 3x3 rotation matrix (row-major)."""
    x, y, z, w = q
    return [
        [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
        [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
        [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
    ]


def _global_positions(g) -> dict[str, tuple[float, float, float]]:
    """Compose each node's TRS down the scene graph -> global joint positions."""

    def local_mat(n):
        r = _quat_to_mat3(n.rotation or [0.0, 0.0, 0.0, 1.0])
        t = n.translation or [0.0, 0.0, 0.0]
        s = n.scale or [1.0, 1.0, 1.0]
        return [[r[i][j] * s[j] for j in range(3)] + [t[i]] for i in range(3)] + [
            [0.0, 0.0, 0.0, 1.0]
        ]

    def matmul(a, b):
        return [
            [sum(a[i][k] * b[k][j] for k in range(4)) for j in range(4)]
            for i in range(4)
        ]

    out: dict[str, tuple[float, float, float]] = {}

    def walk(node_idx: int, parent):
        n = g.nodes[node_idx]
        m = matmul(parent, local_mat(n))
        if n.name:
            out[n.name] = (m[0][3], m[1][3], m[2][3])
        for c in n.children or []:
            walk(c, m)

    identity = [[float(i == j) for j in range(4)] for i in range(4)]
    for root in g.scenes[g.scene].nodes:
        walk(root, identity)
    return out


@pytest.mark.integration
@skip_if_pointer
def test_rig_glb_rest_transforms_match_table():
    """Each joint's composed global rest position == the table's head_m (Y-up).

    Spec ④ §2.2 contract: names/hierarchy/REST TRANSFORMS survive the export.
    glTF stores joints (bone heads); tails are Blender-side authoring detail.
    """
    g = _load_rig_gltf()
    pos = _global_positions(g)
    for spec in bones.ALL_BONES:
        got = pos[spec.name]
        for axis, (a, b) in enumerate(zip(got, spec.head_m)):
            assert abs(a - b) < 1e-4, (
                f"{spec.name} axis {axis}: exported {got} != table {spec.head_m}"
            )


@pytest.mark.integration
@skip_if_pointer
def test_rig_glb_has_single_bone_root():
    """Exactly one table bone (Root) has no bone parent inside the armature."""
    g = _load_rig_gltf()
    child_to_parent: dict[str, str] = {}
    for n in g.nodes:
        for c in n.children or []:
            child_to_parent[g.nodes[c].name] = n.name
    table = set(bones.bone_names())
    unparented = {b for b in table if child_to_parent.get(b) not in table}
    assert unparented == {"Root"}, unparented


# ---------------------------------------------------------------------------
# Structural checks on the committed DOLMEN reference rig .glb (Race #2 D1).
# The same read-back-with-pygltflib pattern as ardent: proves the committed
# artifact carries exactly the 63 canonical joints and the shared hierarchy,
# and that its rest transforms are the Dolmen (shorter/broader) proportions —
# the shared-skeleton contract as it ships in a binary, not just in the table.
# ---------------------------------------------------------------------------
DOLMEN_RIG_GLB = REPO / "content/core/assets/art/char/sk_dolmen_male_skeleton.glb"

skip_if_dolmen_pointer = pytest.mark.skipif(
    _is_lfs_pointer(DOLMEN_RIG_GLB),
    reason="dolmen rig .glb is an unsmudged LFS pointer (CI checkout without LFS smudge)",
)


def _load_dolmen_rig_gltf():
    from pygltflib import GLTF2

    return GLTF2().load(str(DOLMEN_RIG_GLB))


@pytest.mark.integration
@skip_if_dolmen_pointer
def test_dolmen_rig_glb_joints_are_exactly_the_canonical_63():
    """I020: the committed dolmen skeleton's skin joints == the canonical 63 bones."""
    g = _load_dolmen_rig_gltf()
    joints: set[str] = set()
    for skin in g.skins or []:
        for j in skin.joints or []:
            joints.add(g.nodes[j].name)
    canonical = set(bones.bone_names("dolmen_male"))
    assert joints == canonical, {
        "missing": sorted(canonical - joints),
        "extra": sorted(joints - canonical),
    }


@pytest.mark.integration
@skip_if_dolmen_pointer
def test_dolmen_rig_glb_hierarchy_matches_table():
    """The committed dolmen skeleton's parent wiring matches the shared hierarchy."""
    g = _load_dolmen_rig_gltf()
    child_to_parent: dict[str, str] = {}
    for n in g.nodes:
        for c in n.children or []:
            child_to_parent[g.nodes[c].name] = n.name
    for name, parent in bones.hierarchy("dolmen_male").items():
        if parent is not None:
            assert child_to_parent.get(name) == parent, name


@pytest.mark.integration
@skip_if_dolmen_pointer
def test_dolmen_rig_glb_rest_transforms_match_dolmen_table():
    """Each joint's composed global rest position == the Dolmen table's head_m.

    Same round-trip contract the ardent rig asserts, but against the Dolmen
    profile — proving the committed .glb is the stockier build, not a copy of
    the ardent skeleton under a different filename.
    """
    g = _load_dolmen_rig_gltf()
    pos = _global_positions(g)
    for spec in bones.for_profile("dolmen_male"):
        got = pos[spec.name]
        for axis, (a, b) in enumerate(zip(got, spec.head_m)):
            assert abs(a - b) < 1e-4, (
                f"{spec.name} axis {axis}: exported {got} != table {spec.head_m}"
            )


@pytest.mark.integration
@skip_if_dolmen_pointer
def test_dolmen_rig_glb_is_shorter_than_ardent_rig():
    """The committed dolmen skeleton is measurably shorter than the ardent table."""
    dolmen_crown = max(p[1] for p in _global_positions(_load_dolmen_rig_gltf()).values())
    ardent_crown = max(b.head_m[1] for b in bones.for_profile("ardent_male"))
    assert dolmen_crown < ardent_crown


# ---------------------------------------------------------------------------
# generate_blockout — pure helpers (importable without bpy) + structural checks
# on the committed greybox blockout body .glb (spec ④ §6 / T5).
# ---------------------------------------------------------------------------
import generate_blockout  # noqa: E402

BODY_GLB = REPO / "content/core/assets/art/char/sk_ardent_male_base.glb"

skip_if_body_pointer = pytest.mark.skipif(
    _is_lfs_pointer(BODY_GLB),
    reason="body .glb is an unsmudged LFS pointer (CI checkout without LFS smudge)",
)

GEOSET_REGIONS = [
    "head",
    "hands",
    "forearms",
    "torso",
    "waist",
    "hips_legs",
    "lower_legs",
    "feet",
]


def test_blockout_region_groups_cover_exactly_the_8_geoset_regions():
    """Drift guard: region keys == skeleton.defs.yaml $defs.geosetRegion.enum."""
    defs = yaml.safe_load((REPO / "schema/content/skeleton.defs.yaml").read_text())
    assert sorted(generate_blockout.region_bone_groups()) == sorted(
        defs["$defs"]["geosetRegion"]["enum"]
    )


def test_blockout_region_groups_use_only_canonical_bones():
    canonical = set(bones.bone_names())
    for region, groups in generate_blockout.region_bone_groups().items():
        for group in groups:
            assert group, f"{region} has an empty bone group"
            unknown = set(group) - canonical
            assert not unknown, f"{region} names unknown bones: {sorted(unknown)}"


def test_blockout_mesh_name_follows_geoset_convention():
    assert generate_blockout.mesh_name("head") == "geo_head_lod0"
    assert generate_blockout.mesh_name("hips_legs") == "geo_hips_legs_lod0"


def test_blockout_group_bbox_encloses_bones_with_min_radius():
    lo, hi = generate_blockout.group_bbox(["Head", "Neck"], radius=0.11)
    # Neck head y=1.44, Head tail y=1.72 — box spans at least that.
    assert lo[1] <= 1.44 and hi[1] >= 1.72
    # X span of the chain is 0 — the radius guarantees >= 0.11 half-extent.
    assert (hi[0] - lo[0]) / 2.0 >= 0.11 - 1e-9


def test_blockout_parse_args_defaults():
    ns = generate_blockout.parse_args([])
    assert ns.profile == "ardent_male"
    assert ns.out.endswith("sk_ardent_male_base.glb")


def test_blockout_parse_args_rejects_unknown_profile():
    with pytest.raises(SystemExit):
        generate_blockout.parse_args(["--profile", "dwarf_female"])


def _load_body_gltf():
    from pygltflib import GLTF2

    return GLTF2().load(str(BODY_GLB))


def _read_accessor_vec4(g, accessor_idx):
    """Decode a VEC4 accessor from the .glb binary blob -> list of 4-tuples."""
    import struct

    acc = g.accessors[accessor_idx]
    bv = g.bufferViews[acc.bufferView]
    blob = g.binary_blob()
    fmt_by_component = {5121: "B", 5123: "H", 5125: "I", 5126: "f"}
    fmt = fmt_by_component[acc.componentType]
    elem_size = struct.calcsize(fmt) * 4
    stride = bv.byteStride or elem_size
    base = (bv.byteOffset or 0) + (acc.byteOffset or 0)
    out = []
    for i in range(acc.count):
        off = base + i * stride
        out.append(struct.unpack_from("<" + fmt * 4, blob, off))
    return out


_GEO_LOD_RE = re.compile(r"^geo_(?P<region>[a-z0-9_]+)_lod(?P<lod>\d+)$")


@pytest.mark.integration
@skip_if_body_pointer
def test_body_glb_lod0_covers_exactly_the_8_geoset_regions():
    """I022: the eight geoset regions are each present at LOD0 (spec ④ §3/§5).

    The real ⑤/S4 body ships an authored LOD chain, so LOD0 is a subset of the
    full mesh list — this asserts the LOD0 coverage specifically, not the whole
    mesh count (which the blockout's `single`-LOD body could).
    """
    g = _load_body_gltf()
    lod0 = set()
    for m in g.meshes:
        mm = _GEO_LOD_RE.match(m.name)
        assert mm, f"body mesh '{m.name}' is not geoset-named (geo_<region>_lod<N>)"
        if int(mm.group("lod")) == 0:
            lod0.add(mm.group("region"))
    assert lod0 == set(GEOSET_REGIONS), (
        f"LOD0 regions {sorted(lod0)} != {sorted(GEOSET_REGIONS)}"
    )


@pytest.mark.integration
@skip_if_body_pointer
def test_body_glb_ships_authored_lod_chain_per_region():
    """I023: every geoset region carries LOD0 + at least one lower LOD.

    The real body is NOT the `single`-LOD blockout — each of the eight regions
    must ship an authored chain (geo_<region>_lod0 plus geo_<region>_lod1+),
    the exact condition validate_imports I023 enforces on the committed .glb.
    """
    g = _load_body_gltf()
    chain: dict[str, set[int]] = {}
    for m in g.meshes:
        mm = _GEO_LOD_RE.match(m.name)
        assert mm, f"body mesh '{m.name}' is not geoset-named"
        chain.setdefault(mm.group("region"), set()).add(int(mm.group("lod")))
    for region in GEOSET_REGIONS:
        lods = chain.get(region, set())
        assert 0 in lods, f"region '{region}' has no LOD0"
        assert any(lod >= 1 for lod in lods), (
            f"region '{region}' has no LOD1+ — a real body ships an authored "
            f"chain, not the blockout's 'single' exemption (I023)"
        )


@pytest.mark.integration
@skip_if_body_pointer
def test_body_glb_skin_joints_are_exactly_the_canonical_bone_set():
    """I020: every skin joint is canonical AND the full 63-bone set is bound."""
    g = _load_body_gltf()
    assert g.skins, "body .glb carries no skin"
    joint_names = set()
    for skin in g.skins:
        for j in skin.joints or []:
            joint_names.add(g.nodes[j].name)
    canonical = set(bones.bone_names())
    assert joint_names - canonical == set(), (
        f"non-canonical joints: {sorted(joint_names - canonical)}"
    )
    assert canonical - joint_names == set(), (
        f"canonical bones missing from skin: {sorted(canonical - joint_names)}"
    )


@pytest.mark.integration
@skip_if_body_pointer
def test_body_glb_vertices_have_at_most_4_influences():
    """E103/spec ④ §6: one JOINTS_0/WEIGHTS_0 set only — no JOINTS_1 spillover."""
    g = _load_body_gltf()
    for mesh in g.meshes:
        for prim in mesh.primitives:
            attrs = prim.attributes
            assert attrs.JOINTS_0 is not None, f"{mesh.name} is not skinned"
            assert attrs.WEIGHTS_0 is not None, f"{mesh.name} has no weights"
            assert getattr(attrs, "JOINTS_1", None) is None, (
                f"{mesh.name} carries a second influence set (>4 influences)"
            )


@pytest.mark.integration
@skip_if_body_pointer
def test_body_glb_weights_are_normalized():
    g = _load_body_gltf()
    for mesh in g.meshes:
        for prim in mesh.primitives:
            weights = _read_accessor_vec4(g, prim.attributes.WEIGHTS_0)
            comp = g.accessors[prim.attributes.WEIGHTS_0].componentType
            scale = 1.0 if comp == 5126 else (255.0 if comp == 5121 else 65535.0)
            for i, w in enumerate(weights):
                total = sum(w) / scale
                assert abs(total - 1.0) < 5e-3, (
                    f"{mesh.name} vertex {i} weight sum {total}"
                )


# ---------------------------------------------------------------------------
# Structural checks on the committed DOLMEN body .glb (Race #2 D2). Same
# read-back-with-pygltflib pattern as the ardent body: the second race's body
# must ship the identical geoset/LOD/skin structure (8 regions, authored LOD
# chain, <=4 influences, normalized) skinned to the SAME 63 canonical bone
# names — only its rest geometry (the dolmen skeleton it was fit to) differs.
# I020/I022/I023 as they ship in a binary, not just in the pipeline.
# ---------------------------------------------------------------------------
DOLMEN_BODY_GLB = REPO / "content/core/assets/art/char/sk_dolmen_male_base.glb"

skip_if_dolmen_body_pointer = pytest.mark.skipif(
    _is_lfs_pointer(DOLMEN_BODY_GLB),
    reason="dolmen body .glb is an unsmudged LFS pointer (CI checkout without LFS smudge)",
)


def _load_dolmen_body_gltf():
    from pygltflib import GLTF2

    return GLTF2().load(str(DOLMEN_BODY_GLB))


@pytest.mark.integration
@skip_if_dolmen_body_pointer
def test_dolmen_body_glb_lod0_covers_exactly_the_8_geoset_regions():
    """I022: the eight geoset regions are each present at LOD0 on the dolmen body."""
    g = _load_dolmen_body_gltf()
    lod0 = set()
    for m in g.meshes:
        mm = _GEO_LOD_RE.match(m.name)
        assert mm, f"dolmen body mesh '{m.name}' is not geoset-named (geo_<region>_lod<N>)"
        if int(mm.group("lod")) == 0:
            lod0.add(mm.group("region"))
    assert lod0 == set(GEOSET_REGIONS), (
        f"LOD0 regions {sorted(lod0)} != {sorted(GEOSET_REGIONS)}"
    )


@pytest.mark.integration
@skip_if_dolmen_body_pointer
def test_dolmen_body_glb_ships_authored_lod_chain_per_region():
    """I023: every geoset region carries LOD0 + at least one lower LOD (no 'single')."""
    g = _load_dolmen_body_gltf()
    chain: dict[str, set[int]] = {}
    for m in g.meshes:
        mm = _GEO_LOD_RE.match(m.name)
        assert mm, f"dolmen body mesh '{m.name}' is not geoset-named"
        chain.setdefault(mm.group("region"), set()).add(int(mm.group("lod")))
    for region in GEOSET_REGIONS:
        lods = chain.get(region, set())
        assert 0 in lods, f"region '{region}' has no LOD0"
        assert any(lod >= 1 for lod in lods), (
            f"region '{region}' has no LOD1+ — a real body ships an authored chain (I023)"
        )


@pytest.mark.integration
@skip_if_dolmen_body_pointer
def test_dolmen_body_glb_skin_joints_are_exactly_the_canonical_bone_set():
    """I020: the dolmen body's skin joints == the canonical 63 bone names."""
    g = _load_dolmen_body_gltf()
    assert g.skins, "dolmen body .glb carries no skin"
    joint_names = set()
    for skin in g.skins:
        for j in skin.joints or []:
            joint_names.add(g.nodes[j].name)
    canonical = set(bones.bone_names("dolmen_male"))
    assert joint_names - canonical == set(), (
        f"non-canonical joints: {sorted(joint_names - canonical)}"
    )
    assert canonical - joint_names == set(), (
        f"canonical bones missing from skin: {sorted(canonical - joint_names)}"
    )


@pytest.mark.integration
@skip_if_dolmen_body_pointer
def test_dolmen_body_glb_vertices_have_at_most_4_influences():
    """E103: one JOINTS_0/WEIGHTS_0 set only — no JOINTS_1 spillover (>4 influences)."""
    g = _load_dolmen_body_gltf()
    for mesh in g.meshes:
        for prim in mesh.primitives:
            attrs = prim.attributes
            assert attrs.JOINTS_0 is not None, f"{mesh.name} is not skinned"
            assert attrs.WEIGHTS_0 is not None, f"{mesh.name} has no weights"
            assert getattr(attrs, "JOINTS_1", None) is None, (
                f"{mesh.name} carries a second influence set (>4 influences)"
            )


@pytest.mark.integration
@skip_if_dolmen_body_pointer
def test_dolmen_body_glb_weights_are_normalized():
    g = _load_dolmen_body_gltf()
    for mesh in g.meshes:
        for prim in mesh.primitives:
            weights = _read_accessor_vec4(g, prim.attributes.WEIGHTS_0)
            comp = g.accessors[prim.attributes.WEIGHTS_0].componentType
            scale = 1.0 if comp == 5126 else (255.0 if comp == 5121 else 65535.0)
            for i, w in enumerate(weights):
                total = sum(w) / scale
                assert abs(total - 1.0) < 5e-3, f"{mesh.name} vertex {i} weight sum {total}"


# --- restyle_body pure helpers (spec ⑤/S4; bpy-free, unit-tested) ------------


def test_restyle_mesh_name_follows_geoset_lod_convention():
    assert restyle_body.mesh_name("head", 0) == "geo_head_lod0"
    assert restyle_body.mesh_name("hips_legs", 3) == "geo_hips_legs_lod3"


def test_restyle_region_anchors_cover_every_geoset_region():
    """One anchor per bone-group; every one of the 8 regions is represented."""
    anchors = restyle_body.region_anchors()
    regions = set(r for r, _ in anchors)
    assert regions == set(GEOSET_REGIONS)
    # Paired limbs contribute two anchors (left/right); central regions one.
    assert len(anchors) == sum(
        len(groups) for groups in generate_blockout.region_bone_groups().values()
    )


def test_restyle_nearest_region_picks_closest_anchor():
    anchors = [("head", (0.0, 0.0, 1.7)), ("feet", (0.0, 0.0, 0.05))]
    assert restyle_body.nearest_region((0.0, 0.0, 1.65), anchors) == "head"
    assert restyle_body.nearest_region((0.0, 0.0, 0.1), anchors) == "feet"


def test_restyle_upper_arm_belongs_to_forearms_not_torso():
    """#587 regression: the whole upper arm (shoulder joint -> elbow) cuts into
    the `forearms` geoset, not `torso`.

    RightUpperArm spans x 0.17 -> 0.47 at the shoulder line (y=1.42, bones.py).
    Before the geoset re-cut the only per-arm anchor sat near the elbow, so the
    shoulder-line upper-arm surface fell to the nearer central `torso` anchor and
    was erased whenever a torso-hiding chest was worn, orphaning the forearm.
    Every sample along the upper arm must now resolve to `forearms` so hiding
    `torso` can never touch arm geometry. Points are Y-up (table/glTF space) and
    mapped to the Blender space the partition runs in, exactly as the cut does.
    """
    anchors = restyle_body.region_anchors()

    def region_of(point_yup):
        return restyle_body.nearest_region(
            generate_rig.yup_to_blender(point_yup), anchors
        )

    # Upper arm, shoulder joint (0.17) through the elbow (0.47), both sides.
    for x in (0.18, 0.25, 0.30, 0.40, 0.46):
        assert region_of((x, 1.42, 0.0)) == "forearms", f"right upper arm x={x}"
        assert region_of((-x, 1.42, 0.0)) == "forearms", f"left upper arm x={x}"
    # The central chest stays torso — the fix must not pull the body core out.
    assert region_of((0.0, 1.30, 0.05)) == "torso"


def test_restyle_rig_bounds_z_spans_feet_to_head():
    lo, hi = restyle_body.rig_bounds_z()
    assert lo == pytest.approx(0.0, abs=0.05)  # feet on the floor
    assert hi == pytest.approx(1.72, abs=0.05)  # head crown


def test_restyle_fit_transform_scales_height_and_floors_feet():
    mesh_min, mesh_max = (-1.0, -0.2, -0.95), (1.0, 0.2, 0.95)
    rig_lo, rig_hi = 0.0, 1.72
    scale, offset = restyle_body.fit_transform(mesh_min, mesh_max, rig_lo, rig_hi)
    # Height maps onto the rig span.
    assert (mesh_max[2] - mesh_min[2]) * scale == pytest.approx(rig_hi - rig_lo)
    # Feet floored to the rig floor; scaled bbox top reaches the rig crown.
    assert mesh_min[2] * scale + offset[2] == pytest.approx(rig_lo)
    assert mesh_max[2] * scale + offset[2] == pytest.approx(rig_hi)
    # X/Y centre lands on the rig's vertical axis.
    cx = (mesh_min[0] + mesh_max[0]) / 2.0 * scale + offset[0]
    assert cx == pytest.approx(0.0)


def test_restyle_lod_ratios_are_a_descending_chain_from_full():
    assert restyle_body.LOD_RATIOS[0] == 1.0
    assert all(
        a > b for a, b in zip(restyle_body.LOD_RATIOS, restyle_body.LOD_RATIOS[1:])
    )
    assert len(restyle_body.LOD_RATIOS) >= 2  # lod0 + at least one lower LOD (I023)


def test_restyle_parse_args_requires_input_and_defaults_out():
    ns = restyle_body.parse_args(["--in", "raw.glb"])
    assert ns.in_glb == "raw.glb"
    assert ns.out.endswith("sk_ardent_male_base.glb")
    assert ns.profile == "ardent_male"
    with pytest.raises(SystemExit):
        restyle_body.parse_args([])  # --in is required


# --- Profile-aware fit + geoset partition (Race #2 / Dolmen D2). The restyle
# fit height and the Voronoi region anchors must follow the TARGET profile's
# rest geometry, not the ardent reference, or a --profile dolmen_male run would
# fit a body to ardent's 1.72 m height while skinning it to the 1.51 m dolmen
# skeleton — a height mismatch. The ardent default stays byte-identical.
# ---------------------------------------------------------------------------
def test_group_bbox_profile_defaults_to_ardent():
    """Omitting the profile is exactly the ardent reference geometry."""
    assert generate_blockout.group_bbox(["Head", "Neck"], 0.11) == (
        generate_blockout.group_bbox(["Head", "Neck"], 0.11, profile="ardent_male")
    )


def test_group_bbox_dolmen_head_sits_lower_than_ardent():
    """Dolmen is shorter, so the head/neck box's crown is below ardent's."""
    _, hi_ard = generate_blockout.group_bbox(["Head", "Neck"], 0.11, profile="ardent_male")
    _, hi_dol = generate_blockout.group_bbox(["Head", "Neck"], 0.11, profile="dolmen_male")
    assert hi_dol[1] < hi_ard[1] - 0.1  # crown Y (table Y-up) clearly lower


def test_restyle_rig_bounds_z_defaults_to_ardent():
    assert restyle_body.rig_bounds_z() == restyle_body.rig_bounds_z("ardent_male")


def test_restyle_rig_bounds_z_dolmen_is_shorter_than_ardent():
    """The dolmen fit target tops out well below ardent's ~1.72 m crown."""
    _, hi_ard = restyle_body.rig_bounds_z("ardent_male")
    _, hi_dol = restyle_body.rig_bounds_z("dolmen_male")
    assert hi_dol < hi_ard - 0.1
    assert hi_dol == pytest.approx(1.51, abs=0.06)  # dolmen crown ~1.51 m


def test_restyle_region_anchors_default_matches_ardent():
    assert restyle_body.region_anchors() == restyle_body.region_anchors("ardent_male")


def test_restyle_region_anchors_dolmen_is_broader_than_ardent():
    """Dolmen widens every X (1.10x), so its anchors reach further off-centre."""
    max_x_ard = max(abs(c[0]) for _, c in restyle_body.region_anchors("ardent_male"))
    max_x_dol = max(abs(c[0]) for _, c in restyle_body.region_anchors("dolmen_male"))
    assert max_x_dol > max_x_ard


# --- restyle_hair pure helpers (spec ⑤/S5; bpy-free, unit-tested) ------------


def test_restyle_hair_bone_is_a_canonical_bone():
    """Hair single-influence skins to Head — which must be a canonical bone."""
    assert restyle_hair.HAIR_BONE in set(bones.bone_names())


def test_restyle_hair_mesh_name_is_not_geoset_named():
    """E104: an armor_model piece must NOT use geo_<region> geoset naming."""
    assert not restyle_hair.HAIR_MESH_NAME.startswith("geo_")


def test_restyle_hair_head_region_box_spans_the_head_geoset():
    """The fit target is the canonical head geoset span (crown ~1.72, base ~1.44)."""
    lo, hi = restyle_hair.head_region_box()
    assert hi[2] == pytest.approx(1.72, abs=0.05)  # crown at the Head bone tail
    assert lo[2] == pytest.approx(1.44, abs=0.05)  # base at the Neck head
    # A head-width box centred on the rig's vertical axis.
    assert lo[0] == pytest.approx(-hi[0], abs=1e-6)
    assert (hi[0] - lo[0]) > 0.0


def test_restyle_hair_fit_transform_scales_footprint_to_head_width():
    head_lo, head_hi = restyle_hair.head_region_box()
    mesh_min, mesh_max = (-0.5, -0.4, -0.3), (0.5, 0.4, 0.6)
    scale, offset = restyle_hair.fit_head_transform(
        mesh_min, mesh_max, head_lo, head_hi
    )
    head_w = max(head_hi[0] - head_lo[0], head_hi[1] - head_lo[1])
    mesh_w = max(mesh_max[0] - mesh_min[0], mesh_max[1] - mesh_min[1])
    assert scale == pytest.approx(head_w / mesh_w)


def test_restyle_hair_fit_transform_centres_volume_on_the_head():
    head_lo, head_hi = restyle_hair.head_region_box()
    mesh_min, mesh_max = (-0.5, -0.4, -0.3), (0.5, 0.4, 0.6)
    scale, offset = restyle_hair.fit_head_transform(
        mesh_min, mesh_max, head_lo, head_hi
    )

    def _c(lo, hi, i):
        return (lo[i] + hi[i]) / 2.0

    for i in range(3):
        placed_centre = _c(mesh_min, mesh_max, i) * scale + offset[i]
        assert placed_centre == pytest.approx(_c(head_lo, head_hi, i), abs=1e-6)
    # The seated hair centre sits within the head geoset's vertical span.
    placed_cz = _c(mesh_min, mesh_max, 2) * scale + offset[2]
    assert head_lo[2] <= placed_cz <= head_hi[2]


def test_restyle_hair_budget_is_low_poly_under_the_armor_ceiling():
    """Hair is a light attachment — target well under the armor_model 8k cap."""
    assert restyle_hair.TARGET_TRIS <= restyle_hair.MAX_TRIS
    assert restyle_hair.MAX_TRIS < 8_000  # armor_model L070 ceiling


def test_restyle_hair_parse_args_requires_input_and_defaults_out():
    ns = restyle_hair.parse_args(["--in", "raw.glb"])
    assert ns.in_glb == "raw.glb"
    assert ns.out.endswith("hair_1.glb")
    assert ns.profile == "ardent_male"
    with pytest.raises(SystemExit):
        restyle_hair.parse_args([])  # --in is required


# --- committed hair .glb structural tests (spec ⑤/S5) ------------------------

HAIR_GLBS = [
    REPO / f"content/core/assets/art/char/ardent/male/hair_{n}.glb" for n in range(1, 5)
]

# armor_model L070 ceiling (Art PRD §2.1 armor set piece 3-8k) — a hair mesh
# must sit comfortably under it (it is a light attachment, not a full plate).
_ARMOR_TRI_CEILING = 8_000


def _hair_present_and_smudged(path: Path) -> bool:
    return path.is_file() and not _is_lfs_pointer(path)


@pytest.mark.integration
@pytest.mark.parametrize("hair_glb", HAIR_GLBS, ids=lambda p: p.stem)
def test_hair_glb_binds_only_the_canonical_head_bone(hair_glb):
    """I021/E100: the hair skin binds only canonical bones, and Head is among them."""
    if not _hair_present_and_smudged(hair_glb):
        pytest.skip(f"{hair_glb.name} missing or an unsmudged LFS pointer")
    from pygltflib import GLTF2

    g = GLTF2().load(str(hair_glb))
    assert g.skins, f"{hair_glb.name} carries no skin"
    joints = set()
    for skin in g.skins:
        for j in skin.joints or []:
            joints.add(g.nodes[j].name)
    canonical = set(bones.bone_names())
    assert joints - canonical == set(), (
        f"{hair_glb.name} binds non-canonical joints: {sorted(joints - canonical)}"
    )
    assert restyle_hair.HAIR_BONE in joints, (
        f"{hair_glb.name} skin does not bind the {restyle_hair.HAIR_BONE} bone"
    )


@pytest.mark.integration
@pytest.mark.parametrize("hair_glb", HAIR_GLBS, ids=lambda p: p.stem)
def test_hair_glb_is_single_influence(hair_glb):
    """E103/spec ⑤/S5: hair uses one influence per vertex (no JOINTS_1 spillover)."""
    if not _hair_present_and_smudged(hair_glb):
        pytest.skip(f"{hair_glb.name} missing or an unsmudged LFS pointer")
    from pygltflib import GLTF2

    g = GLTF2().load(str(hair_glb))
    for mesh in g.meshes:
        for prim in mesh.primitives:
            attrs = prim.attributes
            assert attrs.JOINTS_0 is not None, f"{mesh.name} is not skinned"
            assert getattr(attrs, "JOINTS_1", None) is None, (
                f"{mesh.name} carries a second influence set (>4 influences)"
            )
            weights = _read_accessor_vec4(g, attrs.WEIGHTS_0)
            comp = g.accessors[attrs.WEIGHTS_0].componentType
            scale = 1.0 if comp == 5126 else (255.0 if comp == 5121 else 65535.0)
            for i, w in enumerate(weights):
                nonzero = [c for c in w if c / scale > 1e-3]
                assert len(nonzero) == 1, (
                    f"{mesh.name} vertex {i} has {len(nonzero)} influences "
                    f"(hair is single-influence)"
                )
                assert abs(nonzero[0] / scale - 1.0) < 5e-3, (
                    f"{mesh.name} vertex {i} single weight {nonzero[0] / scale} != 1"
                )


@pytest.mark.integration
@pytest.mark.parametrize("hair_glb", HAIR_GLBS, ids=lambda p: p.stem)
def test_hair_glb_is_low_poly_within_budget(hair_glb):
    """L070: the committed hair mesh is under the armor_model tri ceiling."""
    if not _hair_present_and_smudged(hair_glb):
        pytest.skip(f"{hair_glb.name} missing or an unsmudged LFS pointer")
    from pygltflib import GLTF2

    g = GLTF2().load(str(hair_glb))
    tris = 0
    for mesh in g.meshes:
        for prim in mesh.primitives:
            if prim.indices is not None:
                tris += g.accessors[prim.indices].count // 3
            else:
                tris += g.accessors[prim.attributes.POSITION].count // 3
    assert 0 < tris <= _ARMOR_TRI_CEILING, (
        f"{hair_glb.name} has {tris} tris (must be 1..{_ARMOR_TRI_CEILING})"
    )


@pytest.mark.integration
@pytest.mark.parametrize("hair_glb", HAIR_GLBS, ids=lambda p: p.stem)
def test_hair_glb_mesh_is_not_geoset_named(hair_glb):
    """E104: an armor_model hair mesh must not use geo_<region> geoset naming."""
    if not _hair_present_and_smudged(hair_glb):
        pytest.skip(f"{hair_glb.name} missing or an unsmudged LFS pointer")
    from pygltflib import GLTF2

    g = GLTF2().load(str(hair_glb))
    for mesh in g.meshes:
        assert not (mesh.name or "").startswith("geo_"), (
            f"{hair_glb.name} mesh '{mesh.name}' is geoset-named (forbidden for gear)"
        )


# --- restyle_armor pure helpers (spec ⑤/S4, #595; bpy-free, unit-tested) ------


def test_restyle_armor_regions_bind_only_canonical_bones():
    """Every region's bind set names only canonical bones (I021/E100)."""
    canonical = set(bones.bone_names())
    for region, cfg in restyle_armor.REGION_BIND.items():
        assert cfg.bind, f"{region} has an empty bind set"
        assert set(cfg.bind) <= canonical, (
            f"{region} binds non-canonical bones: {sorted(set(cfg.bind) - canonical)}"
        )


def test_restyle_armor_chest_binds_the_spine_column():
    """The chest cuirass rides Spine/Chest/UpperChest (the torso column)."""
    chest = restyle_armor.REGION_BIND["chest"]
    assert chest.region == "torso"
    assert set(chest.bind) == {"Spine", "Chest", "UpperChest"}


def test_restyle_armor_mesh_name_is_not_geoset_named():
    """E104: the exported armor mesh must not use geo_<region> geoset naming."""
    assert not restyle_armor.ARMOR_MESH_NAME.startswith("geo_")


def test_restyle_armor_budget_band_is_within_the_armor_ceiling():
    """Art PRD §2.1: 3–8k tris/slot, under the 8k armor_model L070 ceiling."""
    assert restyle_armor.MIN_TRIS >= 3_000
    assert restyle_armor.MIN_TRIS <= restyle_armor.TARGET_TRIS <= restyle_armor.MAX_TRIS
    assert restyle_armor.MAX_TRIS < 8_000


def test_restyle_armor_only_feet_are_floored_to_the_ground():
    """Feet are the sole ground-contact slot, so only feet set ``floor`` (#599).

    Every other slot sits mid-body and must NOT be floored (flooring shifts a
    plate up so its bottom rests at the ground plane — meaningless for a cuirass
    or gauntlet). Guards the config so a future slot does not inherit flooring.
    """
    assert restyle_armor.REGION_BIND["feet"].floor is True
    for region, cfg in restyle_armor.REGION_BIND.items():
        if region != "feet":
            assert cfg.floor is False, f"{region} must not be floored"


def test_restyle_armor_feet_fit_rests_the_sabaton_on_the_floor_not_below():
    """The feet fit shifts the fitted sabaton so its sole rests AT the floor (#599).

    Regression for the lead full-kit GPU render: the sabatons floated BELOW the
    legs because the fit inflated the bottom BELOW the ground plane (region_lo −
    inflate < 0), so the boot bulk sank through the floor (27% of verts below
    Z=0). With ``floor_z=0.0`` the transform lifts the whole piece so its lowest
    point sits exactly on the ground — nothing below the floor — while preserving
    the fitted shape (scale unchanged; it is a rigid lift, not a squash).
    """
    lo, hi = restyle_armor.region_box("feet")
    mesh_min = (-1.0, -2.0, -3.0)  # arbitrary raw-sculpt AABB
    mesh_max = (2.0, 1.0, 4.0)
    inflate, up_axis = 0.03, 2
    # Without flooring: the bottom lands below the ground (region_lo − inflate < 0).
    scale0, off0 = restyle_armor.fit_region_transform(
        mesh_min, mesh_max, lo, hi, inflate=inflate, up_extend=0.0, up_axis=up_axis
    )
    unfloored_bottom = mesh_min[up_axis] * scale0[up_axis] + off0[up_axis]
    assert unfloored_bottom < 0.0  # the shipped defect: boot sinks below the floor

    # With flooring: the bottom rests exactly at Z=0, the shape (scale) is intact,
    # and the whole piece is lifted by exactly the sub-floor amount.
    scale1, off1 = restyle_armor.fit_region_transform(
        mesh_min,
        mesh_max,
        lo,
        hi,
        inflate=inflate,
        up_extend=0.0,
        up_axis=up_axis,
        floor_z=0.0,
    )
    fitted_bottom = mesh_min[up_axis] * scale1[up_axis] + off1[up_axis]
    fitted_top = mesh_max[up_axis] * scale1[up_axis] + off1[up_axis]
    assert fitted_bottom == pytest.approx(0.0, abs=1e-6)  # rests ON the floor
    assert scale1 == scale0  # rigid lift — no squash, shape preserved
    assert fitted_top == pytest.approx(
        mesh_max[up_axis] * scale0[up_axis] + off0[up_axis] - unfloored_bottom,
        abs=1e-6,
    )
    # Off-axis (X/Y) placement is untouched by flooring — only the up-axis lifts.
    for i in range(3):
        if i != up_axis:
            assert off1[i] == pytest.approx(off0[i], abs=1e-6)


def test_restyle_armor_floor_only_lifts_never_lowers():
    """``floor_z`` never pulls a piece DOWN — it only lifts a sub-floor bottom up.

    If the fitted bottom is already at or above the floor, the transform is
    unchanged (a mid-body slot passing ``floor_z`` by accident is a no-op, and a
    boot whose inflated bottom already clears the ground is left alone).
    """
    lo, hi = restyle_armor.region_box("torso")  # high off the ground
    mesh_min, mesh_max = (0.0, 0.0, 0.0), (1.0, 1.0, 1.0)
    plain = restyle_armor.fit_region_transform(mesh_min, mesh_max, lo, hi, up_axis=2)
    floored = restyle_armor.fit_region_transform(
        mesh_min, mesh_max, lo, hi, up_axis=2, floor_z=0.0
    )
    assert floored == plain  # already well above the floor → no change


def test_restyle_armor_torso_region_box_spans_spine_to_shoulders():
    """The torso region box covers the spine column up to the shoulder girdle.

    Blender Z-up: Z (index 2) is height. The torso bones run Spine.head (Y=1.05)
    → UpperChest.tail (Y=1.44), so the box's Z span must bracket that range — the
    span a chest cuirass covers and reaches up from.
    """
    lo, hi = restyle_armor.region_box("torso")
    assert lo[2] <= 1.06, f"torso box floor {lo[2]} is above the spine base"
    assert hi[2] >= 1.43, f"torso box ceiling {hi[2]} is below the upper chest"


def test_restyle_armor_fit_spans_region_plus_inflation_no_void():
    """The fitted plate AABB provably spans the region inflated outward + up.

    A raw sculpt AABB mapped through the fit transform must land exactly on the
    region box grown by ``inflate`` on every axis and by ``up_extend`` on the top
    of the up-axis — so the plate covers the torso with no gap (no void) and
    reaches up to bridge the shoulder seam, independent of the sculpt's shape.
    """
    lo, hi = restyle_armor.region_box("torso")
    mesh_min = (-2.0, -3.0, 5.0)  # deliberately arbitrary raw-sculpt AABB
    mesh_max = (4.0, 1.0, 9.0)
    inflate, up_extend, up_axis = 0.06, 0.07, 2
    scale, offset = restyle_armor.fit_region_transform(
        mesh_min,
        mesh_max,
        lo,
        hi,
        inflate=inflate,
        up_extend=up_extend,
        up_axis=up_axis,
    )
    fitted_min = tuple(mesh_min[i] * scale[i] + offset[i] for i in range(3))
    fitted_max = tuple(mesh_max[i] * scale[i] + offset[i] for i in range(3))
    for i in range(3):
        assert fitted_min[i] == pytest.approx(lo[i] - inflate, abs=1e-6)
        exp_hi = hi[i] + inflate + (up_extend if i == up_axis else 0.0)
        assert fitted_max[i] == pytest.approx(exp_hi, abs=1e-6)
    # The top of the plate reaches above the bare region ceiling (bridges the seam).
    assert fitted_max[up_axis] > hi[up_axis]


def test_restyle_armor_cylindrical_uv_wraps_and_climbs():
    """u wraps [0,1) around the vertical axis; v climbs 0→1 with height."""
    lo, hi = restyle_armor.region_box("torso")
    cx = (lo[0] + hi[0]) / 2.0
    cy = (lo[1] + hi[1]) / 2.0
    bottom = restyle_armor.cylindrical_uv((cx + 0.1, cy, lo[2]), lo, hi, up_axis=2)
    top = restyle_armor.cylindrical_uv((cx + 0.1, cy, hi[2]), lo, hi, up_axis=2)
    assert bottom[1] == pytest.approx(0.0, abs=1e-6)
    assert top[1] == pytest.approx(1.0, abs=1e-6)
    # A half-turn around the axis moves u by ~0.5.
    front = restyle_armor.cylindrical_uv((cx + 0.1, cy, hi[2]), lo, hi, up_axis=2)
    back = restyle_armor.cylindrical_uv((cx - 0.1, cy, hi[2]), lo, hi, up_axis=2)
    assert abs(front[0] - back[0]) == pytest.approx(0.5, abs=1e-6)
    for uv in (bottom, top, front, back):
        assert 0.0 <= uv[0] < 1.0 and 0.0 <= uv[1] <= 1.0


def test_restyle_armor_uv_normalized_against_fitted_bounds_not_prefit_box():
    """v must be normalized against the mesh's fitted bounds, not the pre-fit box.

    The mesh occupies the region grown by inflate (all axes) + up_extend (top of the
    up-axis). Normalizing v against the PRE-FIT box sends the margin + shoulder-bridge
    geometry outside [0,1] where it CLAMPS (the shipped regression: >50% at v=0). This
    guards the pure invariant: over the FITTED span, v climbs 0→1 with no clamped bulk.
    """
    lo, hi = restyle_armor.region_box("torso")
    inflate, up_extend, up_axis = 0.06, 0.07, 2
    fit_lo = tuple(lo[i] - inflate for i in range(3))
    fit_hi = tuple(
        hi[i] + inflate + (up_extend if i == up_axis else 0.0) for i in range(3)
    )
    cx = (fit_lo[0] + fit_hi[0]) / 2.0
    cy = (fit_lo[1] + fit_hi[1]) / 2.0

    # WRONG (pre-fit box): the fitted bottom + top land outside [0,1] → clamp.
    wrong_bottom = restyle_armor.cylindrical_uv((cx, cy, fit_lo[2]), lo, hi, up_axis)
    wrong_top = restyle_armor.cylindrical_uv((cx, cy, fit_hi[2]), lo, hi, up_axis)
    assert wrong_bottom[1] == 0.0 and wrong_top[1] == 1.0  # both clamp (info lost)

    # RIGHT (fitted bounds): the same physical extremes map to exactly 0 and 1, and
    # every interior height maps strictly inside — no bulk clamping.
    right_bottom = restyle_armor.cylindrical_uv(
        (cx, cy, fit_lo[2]), fit_lo, fit_hi, up_axis
    )
    right_top = restyle_armor.cylindrical_uv(
        (cx, cy, fit_hi[2]), fit_lo, fit_hi, up_axis
    )
    assert right_bottom[1] == pytest.approx(0.0, abs=1e-6)
    assert right_top[1] == pytest.approx(1.0, abs=1e-6)
    for frac in (0.1, 0.25, 0.5, 0.75, 0.9):  # interior heights are unclamped
        z = fit_lo[2] + frac * (fit_hi[2] - fit_lo[2])
        v = restyle_armor.cylindrical_uv((cx, cy, z), fit_lo, fit_hi, up_axis)[1]
        assert v == pytest.approx(frac, abs=1e-6)


@pytest.mark.integration
def test_chest_glb_dye_uv_v_spans_full_range_without_bulk_clamp():
    """The shipped cuirass dye UV v spans ~[0,1] with <5% clamped at either extreme.

    Regression guard for the fit→UV integration bug (#595 review): v was normalized
    against the pre-fit region box while the mesh occupies the inflated + up-extended
    envelope, so 52.3% of verts (concentrated in the shoulder-bridge geometry) clamped
    to v=0 and the height-banded dye mask degenerated to flat colour over half the
    plate. Normalizing against the mesh's real fitted bounds fixes it — the whole mesh
    maps across the mask's full 0..1 range.
    """
    if not _chest_present_and_smudged():
        pytest.skip(f"{CHEST_GLB.name} missing or an unsmudged LFS pointer")
    import struct

    from pygltflib import GLTF2

    g = GLTF2().load(str(CHEST_GLB))
    blob = g.binary_blob()
    prim = g.meshes[0].primitives[0]
    acc = g.accessors[prim.attributes.TEXCOORD_0]
    bv = g.bufferViews[acc.bufferView]
    base = (bv.byteOffset or 0) + (acc.byteOffset or 0)
    stride = bv.byteStride or 8
    vs = [
        struct.unpack_from("<2f", blob, base + i * stride)[1] for i in range(acc.count)
    ]
    n = len(vs)
    clamp_lo = sum(1 for v in vs if v <= 1e-6) / n
    clamp_hi = sum(1 for v in vs if v >= 1.0 - 1e-6) / n
    assert min(vs) < 0.05 and max(vs) > 0.95, (
        f"dye UV v does not span [0,1]: min={min(vs):.3f} max={max(vs):.3f}"
    )
    assert clamp_lo < 0.05, (
        f"{clamp_lo:.1%} of verts clamp at v=0 (was 52.3% before the fix)"
    )
    assert clamp_hi < 0.05, f"{clamp_hi:.1%} of verts clamp at v=1"


def test_restyle_armor_nearest_bind_bone_picks_by_height():
    """A point near the spine base binds Spine; near the top binds UpperChest."""
    bind = ("Spine", "Chest", "UpperChest")
    # Blender Z-up; spine base ~Z 1.11 (Spine mid), upper chest ~Z 1.38.
    assert restyle_armor.nearest_bind_bone((0.0, 0.0, 1.10), bind) == "Spine"
    assert restyle_armor.nearest_bind_bone((0.0, 0.0, 1.40), bind) == "UpperChest"


def test_restyle_armor_parse_args_defaults_to_chest():
    ns = restyle_armor.parse_args(["--in", "raw.glb"])
    assert ns.in_glb == "raw.glb"
    assert ns.region == "chest"
    assert ns.out == restyle_armor.DEFAULT_OUT
    assert ns.body_glb == restyle_armor.DEFAULT_BODY_GLB
    with pytest.raises(SystemExit):
        restyle_armor.parse_args([])  # --in is required


def test_restyle_armor_read_glb_aabb_missing_mesh_returns_none():
    """A missing file or absent mesh yields None (caller falls back to the nominal box)."""
    assert (
        restyle_armor._read_glb_mesh_aabb("/nonexistent.glb", "geo_torso_lod0") is None
    )


BODY_BASE_GLB = REPO / "content/core/assets/art/char/sk_ardent_male_base.glb"


@pytest.mark.integration
def test_restyle_armor_body_region_box_is_wider_than_nominal():
    """The real torso surface is WIDER (X) than the bone-group box — so fitting to
    it (not the nominal box) makes the cuirass sit outside the body with no void."""
    if BODY_BASE_GLB.is_file() and _is_lfs_pointer(BODY_BASE_GLB):
        pytest.skip("body base .glb is an unsmudged LFS pointer")
    body = restyle_armor.body_region_box(str(BODY_BASE_GLB), "torso")
    if body is None:
        pytest.skip("body torso geoset unavailable")
    nom_lo, nom_hi = restyle_armor.region_box("torso")
    b_lo, b_hi = body
    # X half-width from the real surface exceeds the nominal shoulder-bone span.
    assert (b_hi[0] - b_lo[0]) > (nom_hi[0] - nom_lo[0]), (
        "body torso surface should be wider in X than the nominal bone-group box"
    )
    # Height (Blender Z) brackets the spine column.
    assert b_lo[2] <= 1.12 and b_hi[2] >= 1.42


# --- committed warden_chest .glb structural tests (spec ⑤/S4, #595) -----------

CHEST_GLB = REPO / "content/core/assets/art/item/armor/warden_chest.glb"


def _chest_present_and_smudged() -> bool:
    return CHEST_GLB.is_file() and not _is_lfs_pointer(CHEST_GLB)


@pytest.mark.integration
def test_chest_glb_binds_only_canonical_torso_bones():
    """I021/E100: the cuirass skin binds only canonical bones, incl. the spine column."""
    if not _chest_present_and_smudged():
        pytest.skip(f"{CHEST_GLB.name} missing or an unsmudged LFS pointer")
    from pygltflib import GLTF2

    g = GLTF2().load(str(CHEST_GLB))
    assert g.skins, f"{CHEST_GLB.name} carries no skin"
    joints = set()
    for skin in g.skins:
        for j in skin.joints or []:
            joints.add(g.nodes[j].name)
    canonical = set(bones.bone_names())
    assert joints - canonical == set(), (
        f"{CHEST_GLB.name} binds non-canonical joints: {sorted(joints - canonical)}"
    )
    # At least one bound joint is a torso-column bone the cuirass rides.
    assert joints & {"Spine", "Chest", "UpperChest"}, (
        f"{CHEST_GLB.name} does not bind any torso-column bone"
    )


@pytest.mark.integration
def test_chest_glb_is_within_the_armor_budget_band():
    """L070 / Art PRD §2.1: the cuirass is 3–8k tris (real plate, not a blockout)."""
    if not _chest_present_and_smudged():
        pytest.skip(f"{CHEST_GLB.name} missing or an unsmudged LFS pointer")
    from pygltflib import GLTF2

    g = GLTF2().load(str(CHEST_GLB))
    tris = 0
    for mesh in g.meshes:
        for prim in mesh.primitives:
            if prim.indices is not None:
                tris += g.accessors[prim.indices].count // 3
            else:
                tris += g.accessors[prim.attributes.POSITION].count // 3
    assert 3_000 <= tris <= 8_000, (
        f"{CHEST_GLB.name} has {tris} tris (must be 3,000..8,000)"
    )


@pytest.mark.integration
def test_chest_glb_mesh_is_not_geoset_named():
    """E104: the cuirass mesh must not use geo_<region> geoset naming (it is gear)."""
    if not _chest_present_and_smudged():
        pytest.skip(f"{CHEST_GLB.name} missing or an unsmudged LFS pointer")
    from pygltflib import GLTF2

    g = GLTF2().load(str(CHEST_GLB))
    for mesh in g.meshes:
        assert not (mesh.name or "").startswith("geo_"), (
            f"{CHEST_GLB.name} mesh '{mesh.name}' is geoset-named (forbidden for gear)"
        )


def _glb_mesh0_positions_and_indices(glb_path: Path):
    """(positions, indices) of a glTF's first mesh primitive — pure pygltflib read."""
    import struct

    from pygltflib import GLTF2

    g = GLTF2().load(str(glb_path))
    blob = g.binary_blob()
    prim = g.meshes[0].primitives[0]

    def _read(acc_i, fmt, elem_size):
        acc = g.accessors[acc_i]
        bv = g.bufferViews[acc.bufferView]
        base = (bv.byteOffset or 0) + (acc.byteOffset or 0)
        stride = bv.byteStride or elem_size
        return [
            struct.unpack_from(fmt, blob, base + i * stride) for i in range(acc.count)
        ]

    pos = _read(prim.attributes.POSITION, "<3f", 12)
    iacc = g.accessors[prim.indices]
    ifmt = {5121: "<B", 5123: "<H", 5125: "<I"}[iacc.componentType]
    isz = {5121: 1, 5123: 2, 5125: 4}[iacc.componentType]
    ibv = g.bufferViews[iacc.bufferView]
    ibase = (ibv.byteOffset or 0) + (iacc.byteOffset or 0)
    idx = [
        struct.unpack_from(ifmt, blob, ibase + i * isz)[0] for i in range(iacc.count)
    ]
    return pos, idx


def _count_boundary_loops(idx: list[int]) -> tuple[int, int]:
    """(boundary_edge_count, boundary_loop_count) of a triangle index list.

    A boundary edge is used by exactly one triangle; boundary loops are the
    connected components of the boundary-edge graph. A watertight (closed) surface
    has zero of both — a Meshy sculpt riddled with holes has many.
    """
    from collections import Counter, defaultdict

    ec: Counter = Counter()
    for t in range(0, len(idx), 3):
        a, b, c = idx[t], idx[t + 1], idx[t + 2]
        for e in ((a, b), (b, c), (c, a)):
            ec[tuple(sorted(e))] += 1
    bnd = [e for e, n in ec.items() if n == 1]
    adj: defaultdict = defaultdict(list)
    for a, b in bnd:
        adj[a].append(b)
        adj[b].append(a)
    seen: set = set()
    loops = 0
    for a, _b in bnd:
        if a in seen:
            continue
        loops += 1
        stack = [a]
        while stack:
            x = stack.pop()
            if x in seen:
                continue
            seen.add(x)
            stack.extend(adj[x])
    return len(bnd), loops


@pytest.mark.integration
def test_chest_glb_is_watertight_no_center_topology_hole():
    """The restyled cuirass is a closed shell — the #599 centre hole is gone.

    The raw Meshy sculpt (and the pre-#599 shipped plate) was riddled with open
    boundary loops — 141 of them, a topology hole punched through the cuirass
    centre in the lead's full-kit GPU render. The restyle heal pass (weld
    export-split seams + fill open holes + recalc normals) closes them: the
    committed plate reads as a near-watertight closed surface (a couple of
    negligible residual slivers at most, vs the gaping centre hole).
    """
    if not _chest_present_and_smudged():
        pytest.skip(f"{CHEST_GLB.name} missing or an unsmudged LFS pointer")
    _pos, idx = _glb_mesh0_positions_and_indices(CHEST_GLB)
    edges, loops = _count_boundary_loops(idx)
    assert loops <= 20, f"{CHEST_GLB.name} has {loops} open boundary loops (holey)"
    assert edges <= 200, f"{CHEST_GLB.name} has {edges} boundary edges (holey)"


# --- committed warden_feet .glb structural tests (sabaton fit, #599) ----------

FEET_GLB = REPO / "content/core/assets/art/item/armor/warden_feet.glb"


def _feet_present_and_smudged() -> bool:
    return FEET_GLB.is_file() and not _is_lfs_pointer(FEET_GLB)


@pytest.mark.integration
def test_feet_glb_binds_only_canonical_foot_bones():
    """I021/E100: the sabaton skin binds only canonical bones, incl. the foot bones."""
    if not _feet_present_and_smudged():
        pytest.skip(f"{FEET_GLB.name} missing or an unsmudged LFS pointer")
    from pygltflib import GLTF2

    g = GLTF2().load(str(FEET_GLB))
    assert g.skins, f"{FEET_GLB.name} carries no skin"
    joints = {g.nodes[j].name for skin in g.skins for j in (skin.joints or [])}
    canonical = set(bones.bone_names())
    assert joints - canonical == set(), (
        f"{FEET_GLB.name} binds non-canonical joints: {sorted(joints - canonical)}"
    )
    assert joints & {"LeftFoot", "RightFoot"}, (
        f"{FEET_GLB.name} does not bind any foot bone"
    )


@pytest.mark.integration
def test_feet_glb_is_within_the_armor_budget_band():
    """L070 / Art PRD §2.1: the sabatons are 3–8k tris."""
    if not _feet_present_and_smudged():
        pytest.skip(f"{FEET_GLB.name} missing or an unsmudged LFS pointer")
    _pos, idx = _glb_mesh0_positions_and_indices(FEET_GLB)
    tris = len(idx) // 3
    assert 3_000 <= tris <= 8_000, f"{FEET_GLB.name} has {tris} tris (must be 3k..8k)"


@pytest.mark.integration
def test_feet_glb_rests_on_the_floor_at_the_foot_bone_not_below():
    """#599: the sabatons sit ON the feet at the foot bone, NOT floating below.

    The lead's full-kit GPU render showed the sabatons floating BELOW the legs:
    the fit inflated the boot bottom through the ground plane (27% of verts below
    Y=0). The floor-clamped fit rests the sole AT the floor and centres the piece
    on the Foot bone. Exported Y-up, so POSITION Y is height; the canonical Foot
    bone head sits at Y≈0.1 (bones.py, Y-up table space).
    """
    if not _feet_present_and_smudged():
        pytest.skip(f"{FEET_GLB.name} missing or an unsmudged LFS pointer")
    pos, _idx = _glb_mesh0_positions_and_indices(FEET_GLB)
    ys = [p[1] for p in pos]
    lo, hi = min(ys), max(ys)
    center = (lo + hi) / 2.0
    below_floor = sum(1 for y in ys if y < -1e-3) / len(ys)
    foot_head_y = {b.name: b for b in bones.ALL_BONES}["LeftFoot"].head_m[1]
    assert lo >= -1e-3, f"{FEET_GLB.name} dips below the floor: min Y={lo:.3f}"
    assert below_floor < 0.02, f"{below_floor:.1%} of verts are below the floor"
    assert abs(center - foot_head_y) < 0.06, (
        f"{FEET_GLB.name} centre Y={center:.3f} is not near the Foot bone "
        f"({foot_head_y:.3f}) — sabaton not seated on the foot"
    )


@pytest.mark.integration
def test_feet_glb_dye_uv_v_spans_full_range_without_bulk_clamp():
    """The sabaton dye UV v spans ~[0,1] with <5% clamped — the height-banded mask tints."""
    if not _feet_present_and_smudged():
        pytest.skip(f"{FEET_GLB.name} missing or an unsmudged LFS pointer")
    import struct

    from pygltflib import GLTF2

    g = GLTF2().load(str(FEET_GLB))
    blob = g.binary_blob()
    prim = g.meshes[0].primitives[0]
    acc = g.accessors[prim.attributes.TEXCOORD_0]
    bv = g.bufferViews[acc.bufferView]
    base = (bv.byteOffset or 0) + (acc.byteOffset or 0)
    stride = bv.byteStride or 8
    vs = [
        struct.unpack_from("<2f", blob, base + i * stride)[1] for i in range(acc.count)
    ]
    n = len(vs)
    assert min(vs) < 0.05 and max(vs) > 0.95, (
        f"feet dye UV v does not span [0,1]: min={min(vs):.3f} max={max(vs):.3f}"
    )
    assert sum(1 for v in vs if v <= 1e-6) / n < 0.05
    assert sum(1 for v in vs if v >= 1.0 - 1e-6) / n < 0.05


# --- restyle_weapon pure helpers (#605; bpy-free, unit-tested) -----------------
#
# The raw Meshy sword sculpt used to derive these expectations (task
# 019f58ca-b832-7e99-8fcc-97d8813b5a64): blade along glTF +Y (extent 2.0), the
# crossguard along X (0.73), the blade flat along Z (0.165), and the guard/grip/
# pommel mass concentrated on the −Y (grip) end (vertex centroid well below the
# AABB centre). Blender imports Y-up→Z-up, so the sculpt arrives with the blade on
# Z; the restyle proves the pose is canonical regardless of the raw axis order.


def test_restyle_weapon_canonical_pose_matches_the_pickaxe_convention():
    """Blade→Z (up out of the fist), crossguard→X, flat→Y — the pickaxe's pose."""
    assert restyle_weapon.UP_AXIS == 2  # Blender Z → glTF +Y under export_yup
    assert restyle_weapon.GUARD_AXIS == 0  # crossguard along X
    assert restyle_weapon.FLAT_AXIS == 1  # blade flat along Y
    assert {
        restyle_weapon.UP_AXIS,
        restyle_weapon.GUARD_AXIS,
        restyle_weapon.FLAT_AXIS,
    } == {
        0,
        1,
        2,
    }


def test_restyle_weapon_longest_axis_is_the_blade():
    """The blade is the longest AABB extent; guard next; flat shortest."""
    # Raw sword extents (X guard, Y blade, Z flat).
    axes = restyle_weapon.sorted_axes_by_extent((0.73, 2.0, 0.165))
    assert axes == (1, 0, 2)  # blade=Y, guard=X, flat=Z
    # Ties break deterministically by axis index.
    assert restyle_weapon.sorted_axes_by_extent((1.0, 1.0, 1.0)) == (0, 1, 2)


def test_restyle_weapon_grip_side_from_centroid():
    """The guard/grip/pommel mass puts the centroid toward the grip end."""
    # Grip mass on −blade side → centroid below centre → not on the positive side.
    assert (
        restyle_weapon.grip_on_positive_side(
            centroid=(0.0, -0.4, 0.0), aabb_center=(0.0, 0.0, 0.0), blade_axis=1
        )
        is False
    )
    # Mirror case: grip mass on +blade side.
    assert (
        restyle_weapon.grip_on_positive_side(
            centroid=(0.0, 0.4, 0.0), aabb_center=(0.0, 0.0, 0.0), blade_axis=1
        )
        is True
    )


def _apply_perm(perm, p):
    """Reference application of a signed permutation: new[t] = sign * old[src]."""
    out = [0.0, 0.0, 0.0]
    for target in range(3):
        source, sign = perm[target]
        out[target] = sign * p[source]
    return tuple(out)


def test_restyle_weapon_permutation_lands_the_blade_up_and_grip_down():
    """The raw sword pose maps to blade→+Z with the grip seated on −Z."""
    axes = restyle_weapon.sorted_axes_by_extent((0.73, 2.0, 0.165))  # (1,0,2)
    perm = restyle_weapon.signed_permutation(axes, grip_positive=False)
    # Blade tip (raw +Y) lands on +Z (up); the crossguard (raw ±X) lands on X.
    tip = _apply_perm(perm, (0.0, 1.0, 0.0))
    assert tip[restyle_weapon.UP_AXIS] > 0.9
    guard = _apply_perm(perm, (0.365, 0.0, 0.0))
    assert abs(guard[restyle_weapon.GUARD_AXIS]) > 0.3
    # Grip end (raw −Y) lands on −Z (down, into the fist).
    grip = _apply_perm(perm, (0.0, -1.0, 0.0))
    assert grip[restyle_weapon.UP_AXIS] < -0.9


def test_restyle_weapon_permutation_flips_grip_when_on_positive_side():
    """When the grip mass is on the +blade side, the blade is flipped so grip→−Z."""
    axes = (1, 0, 2)
    perm = restyle_weapon.signed_permutation(axes, grip_positive=True)
    # Raw +Y is now the GRIP → it must land DOWN (−Z).
    grip = _apply_perm(perm, (0.0, 1.0, 0.0))
    assert grip[restyle_weapon.UP_AXIS] < -0.9


def test_restyle_weapon_permutation_is_a_proper_rotation_not_a_mirror():
    """Every permutation is a proper rotation (det +1) — never mirrors the mesh."""
    for extents in [(0.73, 2.0, 0.165), (2.0, 0.5, 0.4), (0.3, 0.4, 1.7)]:
        axes = restyle_weapon.sorted_axes_by_extent(extents)
        for grip_positive in (True, False):
            perm = restyle_weapon.signed_permutation(axes, grip_positive)
            rows = {t: perm[t] for t in range(3)}
            assert restyle_weapon._perm_determinant(rows) == 1


def test_restyle_weapon_scale_maps_blade_to_target_length():
    """Uniform scale maps the raw blade extent to the target one-handed length."""
    s = restyle_weapon.uniform_scale(2.0, target_len=0.9)
    assert s == pytest.approx(0.45)
    # Applied to the blade extent, it yields exactly the target length.
    assert 2.0 * s == pytest.approx(0.9)


def test_restyle_weapon_pommel_seats_just_below_the_socket_origin():
    """The scaled pommel (min on the up axis) seats at POMMEL_SEAT_M (like pickaxe)."""
    # Raw pommel min on the up axis, after scale.
    scaled_min = -1.0 * restyle_weapon.uniform_scale(2.0, 0.9)  # −0.45
    off = restyle_weapon.pommel_offset(scaled_min)
    # After the offset the pommel sits exactly at the seat height.
    assert scaled_min + off == pytest.approx(restyle_weapon.POMMEL_SEAT_M)
    assert restyle_weapon.POMMEL_SEAT_M < 0.0  # just below the fist origin


def test_restyle_weapon_budget_stays_within_the_one_handed_band():
    """Art PRD §2.1: 1h weapon ≤12k, under the 15k weapon_model L070 ceiling."""
    assert restyle_weapon.TARGET_TRIS <= restyle_weapon.MAX_TRIS
    assert restyle_weapon.MAX_TRIS <= 12_000
    assert restyle_weapon.MAX_TRIS < 15_000


def test_restyle_weapon_mesh_name_is_not_geoset_named():
    """The exported weapon mesh must not use geo_<region> geoset naming."""
    assert not restyle_weapon.DEFAULT_MESH_NAME.startswith("geo_")


def test_restyle_weapon_parse_args_requires_input_and_defaults_out():
    """--in is required; --out defaults to the committed iron_sword path."""
    args = restyle_weapon.parse_args(["--in", "raw.glb"])
    assert args.in_glb == "raw.glb"
    assert args.out == restyle_weapon.DEFAULT_OUT
    assert args.mesh_name == restyle_weapon.DEFAULT_MESH_NAME
    with pytest.raises(SystemExit):
        restyle_weapon.parse_args([])


# ---------------------------------------------------------------------------
# retarget_clip — pure helpers (importable without bpy). Story #914 (W2a),
# generalized to an arbitrary source→canonical map in story #918 (W3 Meshy).
# ---------------------------------------------------------------------------
# The spike's captured live Meshy rig bone names (story #916, PR #917). 24 bones;
# 22 reconcile to canonical, the two head tips (head_end/headfront) are dropped.
_MESHY_LIVE_BONES = [
    "Hips", "LeftUpLeg", "LeftLeg", "LeftFoot", "LeftToeBase",
    "RightUpLeg", "RightLeg", "RightFoot", "RightToeBase",
    "Spine02", "Spine01", "Spine",
    "LeftShoulder", "LeftArm", "LeftForeArm", "LeftHand",
    "RightShoulder", "RightArm", "RightForeArm", "RightHand",
    "neck", "Head", "head_end", "headfront",
]


def test_retarget_source_name_prefixes_mixamorig():
    assert retarget_clip.source_name("LeftUpperArm") == "mixamorig:LeftUpperArm"


def test_retarget_fixture_source_map_covers_every_canonical_bone():
    # The W2a authored fixture is the "mixamorig:" map case: every canonical bone
    # keyed by its prefixed source name.
    fixture_map = retarget_clip.fixture_source_map()
    for bone in bones.bone_names():
        assert fixture_map[retarget_clip.source_name(bone)] == bone
    assert len(fixture_map) == len(bones.bone_names())


def test_retarget_canonical_name_maps_source_via_fixture_map():
    # The generalized name-remap: consumes a source→canonical map. A no-op path
    # that skipped it leaves the source name in the output track paths.
    fixture_map = retarget_clip.fixture_source_map()
    assert retarget_clip.canonical_name("mixamorig:LeftUpperArm", fixture_map) \
        == "LeftUpperArm"


def test_retarget_canonical_name_unmapped_returns_none():
    # A source bone with no canonical target (an unmapped tip/helper) yields None
    # so the caller drops its track rather than keying a non-existent bone.
    fixture_map = retarget_clip.fixture_source_map()
    assert retarget_clip.canonical_name("mixamorig:NotABone", fixture_map) is None
    assert retarget_clip.canonical_name("whatever", {}) is None


def test_retarget_name_roundtrip_through_fixture_map():
    fixture_map = retarget_clip.fixture_source_map()
    for bone in bones.bone_names():
        source = retarget_clip.source_name(bone)
        assert retarget_clip.canonical_name(source, fixture_map) == bone


def test_retarget_invert_map_roundtrips():
    # canonical→source (retarget drives from the target's animated bones) is the
    # exact inverse of the source→canonical map.
    fixture_map = retarget_clip.fixture_source_map()
    inverse = retarget_clip.invert_map(fixture_map)
    for source, canonical in fixture_map.items():
        assert inverse[canonical] == source


# --- Meshy map path (story #918): the reconciled live names map to canonical ---
def test_retarget_load_meshy_map_reconciles_the_five_divergent_names():
    meshy_map = retarget_clip.load_meshy_map("meshy-5")
    # The 3 divergent names that DO have a canonical target, reconciled to the
    # live spellings (zero-padded spine, lowercase neck).
    assert meshy_map["Spine01"] == "Chest"
    assert meshy_map["Spine02"] == "UpperChest"
    assert meshy_map["neck"] == "Neck"
    # The pre-reconciliation (Mixamo-assumed) spellings are gone.
    assert "Spine1" not in meshy_map
    assert "Spine2" not in meshy_map
    assert "Neck" not in meshy_map


def test_retarget_canonical_name_maps_all_22_mappable_live_meshy_bones():
    meshy_map = retarget_clip.load_meshy_map("meshy-5")
    canonical = set(bones.bone_names())
    mapped = {
        b: retarget_clip.canonical_name(b, meshy_map) for b in _MESHY_LIVE_BONES
    }
    # 22 of 24 live bones map to a real canonical bone; the two head tips drop.
    resolved = {b: c for b, c in mapped.items() if c is not None}
    assert len(resolved) == 22
    for meshy_bone, target in resolved.items():
        assert target in canonical, f"{meshy_bone} → {target} not canonical"


def test_retarget_meshy_map_drops_the_two_head_tip_bones():
    meshy_map = retarget_clip.load_meshy_map("meshy-5")
    # head_end (head tip) + headfront (Meshy-specific extra) have no canonical
    # equivalent — dropped (unmapped), not merged, per the #918 disposition.
    assert retarget_clip.canonical_name("head_end", meshy_map) is None
    assert retarget_clip.canonical_name("headfront", meshy_map) is None


def test_retarget_arm_subtree_contains_the_arm_chain_both_sides():
    sub = set(retarget_clip.arm_subtree())
    # Both upper arms and their descendants; never a leg or the spine.
    assert {"LeftUpperArm", "RightUpperArm", "LeftLowerArm", "RightLowerArm"} <= sub
    assert "LeftHand" in sub and "RightHand" in sub
    assert "LeftUpperLeg" not in sub
    assert "Spine" not in sub


def test_retarget_arm_subtree_every_member_descends_from_an_upper_arm():
    hierarchy = bones.hierarchy()
    for name in retarget_clip.arm_subtree():
        cur = name
        roots = set()
        while cur is not None:
            roots.add(cur)
            cur = hierarchy.get(cur)
        assert roots & {"LeftUpperArm", "RightUpperArm"}, name


def test_retarget_yup_to_blender_matches_generate_rig():
    # Same Y-up -> Z-up mapping as the skeleton exporter, so the retarget bakes
    # onto a rest byte-identical to the chibi rig.
    assert retarget_clip.yup_to_blender((1.0, 2.0, 3.0)) == (1.0, -3.0, 2.0)


def test_retarget_clip_names_are_the_four_locomotion_keys():
    assert retarget_clip.CLIP_NAMES == ("idle", "walk", "run", "jump")


def test_retarget_parse_args_defaults_to_chibi_and_staged_fixture():
    ns = retarget_clip.parse_args([])
    assert ns.profile == "chibi"
    assert ns.out.endswith("meridian_locomotion_retarget.glb")
    assert ns.allow_unpinned_blender is False


def test_retarget_parse_args_reads_profile_and_out():
    ns = retarget_clip.parse_args(["--profile", "ardent_male", "--out", "/tmp/a.glb"])
    assert ns.profile == "ardent_male"
    assert ns.out == "/tmp/a.glb"


def test_retarget_parse_args_rejects_unknown_profile():
    with pytest.raises(SystemExit):
        retarget_clip.parse_args(["--profile", "dwarf_female"])


def test_retarget_argv_after_ddash_extracts_args():
    argv = ["blender", "--background", "--python", "retarget_clip.py", "--",
            "--profile", "chibi", "--out", "x.glb"]
    assert retarget_clip.argv_after_ddash(argv) == [
        "--profile", "chibi", "--out", "x.glb"]
