-- world DB DML — generated by mcc emit-sql (IF-4, Tools SAD §2.6).
-- Deterministic full dump: tables in DDL order, rows by primary key.
-- DO NOT EDIT — rebuild with `mcc emit-sql`.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- world_manifest (boot handshake; worldd reads + verifies this).
INSERT INTO world_manifest
  (pack_namespace, pack_version, id_band, content_hash, schema_version, mcc_version, built_at)
VALUES
  ('core', '0.1.0', 0, '3866e1af351061e11b918637b92c882ba2141b1feff8e2cbfb4326378f4ed3b8', 1, '0.0.0', '1970-01-01 00:00:00');

-- npc_template (3 rows)
INSERT INTO npc_template (id, name, subtitle, level_min, level_max, creature_type, `rank`, faction, stat_health, stat_mana, stat_armor, stat_damage_min, stat_damage_max, stat_attack_speed_ms, ai_behavior, ai_aggro_radius_m, ai_leash_radius_m, ai_call_for_help_radius_m, ai_flee_at_health_pct, move_walk_speed_mps, move_run_speed_mps, vendor_ref_id, loot_table_ref_id, loot_money_min, loot_money_max, visual_model_id, visual_scale, visual_sound_set_id) VALUES
  (25, 'Kobold Digmaster', 'Mining Supervisor', 5, 5, 'humanoid', 'elite', 'hostile', 420, NULL, 90, 11, 16, 2200, 'aggressive', 22, 70, NULL, NULL, NULL, NULL, NULL, 21, 60, 140, 5, 1.15, 31),
  (26, 'Kobold Miner', NULL, 3, 4, 'humanoid', 'normal', 'hostile', 120, NULL, 45, 6, 9, 2000, 'aggressive', 18, 55, 12, 15, NULL, NULL, NULL, 21, 12, 38, 6, NULL, 31),
  (27, 'Quartermaster Bren', 'Emberfall Supplies', 10, 10, 'humanoid', 'normal', 'friendly', 800, NULL, 200, 15, 22, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 36, NULL, NULL, NULL, 4, NULL, 30);

-- npc_ability (2 rows)
INSERT INTO npc_ability (npc_id, ability_id, priority, cooldown_override_ms, use_at_health_below_pct) VALUES
  (25, 2, 0, 6000, NULL),
  (26, 2, 0, NULL, 80);

-- item_template (5 rows)
INSERT INTO item_template (id, name, flavor_text, item_class, subclass, slot, rarity, required_level, item_level, is_unique, binding, stack_size, weapon_damage_min, weapon_damage_max, weapon_speed_ms, weapon_school, armor, effect_on_use_id, price_sell, price_buy, visual_icon_id, visual_model_id) VALUES
  (16, 'Bren''s Signet', 'The quartermaster''s seal, good for a discount he''ll deny offering.', 'armor', 'misc', 'finger', 'uncommon', 4, 9, FALSE, 'on_pickup', 1, NULL, NULL, NULL, NULL, NULL, NULL, 380, NULL, 12, NULL),
  (17, 'Kobold Ear', 'Proof of a culling. Bren doesn''t ask how you got it.', 'quest', NULL, NULL, 'common', 1, 1, FALSE, 'on_pickup', 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8, NULL),
  (18, 'Miner''s Lamp Charm', 'Still faintly warm. Kobolds swear by them; kobolds swear at everything.', 'armor', 'misc', 'trinket', 'uncommon', 4, 9, FALSE, 'on_pickup', 1, NULL, NULL, NULL, NULL, NULL, NULL, 380, NULL, 9, NULL),
  (19, 'Minor Healing Potion', NULL, 'consumable', NULL, NULL, 'common', 1, 1, FALSE, 'none', 5, NULL, NULL, NULL, NULL, NULL, 1, 38, 150, 11, NULL),
  (20, 'Rusty Pickaxe', 'Generations of kobold thumbs have worn the haft smooth.', 'weapon', 'mace_1h', 'main_hand', 'uncommon', 3, 8, FALSE, 'on_equip', 1, 9, 14, 2600, NULL, NULL, NULL, 425, NULL, 10, 13);

-- item_stat (4 rows)
INSERT INTO item_stat (item_id, stat, amount) VALUES
  (16, 'intellect', 2),
  (16, 'spirit', 2),
  (18, 'stamina', 3),
  (20, 'strength', 2);

-- ability (2 rows)
INSERT INTO ability (id, name, description, school, target, range_m, cast_time_ms, cast_channel_ms, cooldown_ms, triggers_gcd, resource_type, resource_amount, av_cast_anim, av_cast_vfx_id, av_cast_sfx_id, av_impact_vfx_id, av_impact_sfx_id) VALUES
  (1, 'Minor Healing', 'Restores {amount} health.', 'holy', 'self', 0, 0, NULL, 60000, FALSE, NULL, NULL, NULL, 14, 33, NULL, NULL),
  (2, 'Pickaxe Slam', 'Slams the target for {amount} physical damage and leaves them bleeding.', 'physical', 'enemy', 5, 0, NULL, 10000, TRUE, 'energy', 20, 'attack_overhead', NULL, NULL, 15, 32);

-- ability_effect (3 rows)
INSERT INTO ability_effect (ability_id, ordinal, kind, amount_min, amount_max, coefficient, threat_amount, duration_ms, max_stacks, periodic_kind, periodic_amount_min, periodic_amount_max, periodic_tick_ms) VALUES
  (1, 0, 'heal', 40, 60, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (2, 0, 'damage', 8, 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  (2, 1, 'aura', NULL, NULL, NULL, NULL, 9000, NULL, 'damage', 2, 3, 3000);

-- quest_template (2 rows)
INSERT INTO quest_template (id, name, summary, offer_text, completion_text, level, required_level, zone_ref_id, giver_npc_id, turn_in_npc_id, reward_xp, reward_money) VALUES
  (28, 'Culling the Kobolds', 'Kill 8 Kobold Miners in Cinderdeep Mine for Quartermaster Bren.', 'The kobolds crawled out of Cinderdeep like ants from a kicked hill, and every wagon they hit is food that doesn''t reach the village. Thin them out for me — eight ought to make the rest reconsider.', 'Eight fewer thieving hands in the hollow. You''ve earned this, and my thanks.', 4, 2, 37, 27, NULL, 340, 250),
  (29, 'Ears for Evidence', 'Collect 6 Kobold Ears for Quartermaster Bren.', 'The village council thinks I exaggerate the kobold problem. Fine. Bring me ears. Councilors respect ears.', 'Six. Ha! Let''s see the council call that "a modest infestation."', 5, 3, 37, 27, NULL, 420, 400);

-- quest_objective (2 rows)
INSERT INTO quest_objective (quest_id, ordinal, type, target_npc_id, item_id, to_npc_id, zone_ref_id, poi, count) VALUES
  (28, 0, 'kill', 26, NULL, NULL, NULL, NULL, 8),
  (29, 0, 'collect', NULL, 17, NULL, NULL, NULL, 6);

-- quest_prereq (1 rows)
INSERT INTO quest_prereq (quest_id, prereq_quest_id) VALUES
  (29, 28);

-- quest_reward (3 rows)
INSERT INTO quest_reward (quest_id, is_choice, ordinal, item_id, count) VALUES
  (28, FALSE, 0, 19, 3),
  (29, TRUE, 0, 18, 1),
  (29, TRUE, 1, 16, 1);

-- loot_table (1 rows)
INSERT INTO loot_table (id, money_min, money_max) VALUES
  (21, 5, 20);

-- loot_group (1 rows)
INSERT INTO loot_group (loot_table_id, ordinal, name, pick, chance_pct) VALUES
  (21, 0, 'common_drops', 1, 40);

-- loot_entry (4 rows)
INSERT INTO loot_entry (loot_table_id, entry_ordinal, group_ordinal, item_id, nested_table_id, chance_pct, weight, quantity_min, quantity_max, quest_ref_id) VALUES
  (21, 0, NULL, 17, NULL, 80, NULL, NULL, NULL, 29),
  (21, 1, NULL, 20, NULL, 3, NULL, NULL, NULL, NULL),
  (21, 2, 0, 19, NULL, NULL, 30, NULL, NULL, NULL),
  (21, 3, 0, 18, NULL, NULL, 3, NULL, NULL, NULL);

-- vendor_inventory (1 rows)
INSERT INTO vendor_inventory (id) VALUES
  (36);

-- vendor_inventory_item (2 rows)
INSERT INTO vendor_inventory_item (vendor_id, ordinal, item_id, price_override, limited_count, limited_restock_minutes) VALUES
  (36, 0, 19, NULL, NULL, NULL),
  (36, 1, 20, 1700, 1, 180);

-- vendor_inventory_buys (4 rows)
INSERT INTO vendor_inventory_buys (vendor_id, item_class) VALUES
  (36, 'armor'),
  (36, 'consumable'),
  (36, 'trade_good'),
  (36, 'weapon');

-- spawn_point (5 rows)
INSERT INTO spawn_point (id, zone_ref_id, npc_id, pos_x, pos_y, pos_z, orientation_deg, respawn_min, respawn_max, wander_radius_m) VALUES
  (1048575, 37, 27, 126, 8.5, -244, 200, 60, 60, NULL),
  (1048576, 37, 26, -295, 21, 88, 0, 120, 180, 8),
  (1048577, 37, 26, -318, 22.5, 104, 0, 120, 180, 8),
  (1048578, 37, 26, -332, 23, 79, 45, 120, 180, NULL),
  (1048579, 37, 25, -320, 22, 92, 0, 300, 420, NULL);

-- patrol_path (1 rows)
INSERT INTO patrol_path (spawn_point_id, `loop`) VALUES
  (1048579, TRUE);

-- patrol_waypoint (4 rows)
INSERT INTO patrol_waypoint (spawn_point_id, ordinal, pos_x, pos_y, pos_z, wait_seconds) VALUES
  (1048579, 0, -320, 22, 92, 5),
  (1048579, 1, -300, 21.2, 85, 0),
  (1048579, 2, -308, 21.8, 110, 8),
  (1048579, 3, -330, 23, 100, 0);

-- zone (1 rows)
INSERT INTO zone (id, name, level_min, level_max, start_zone, music_explore_id, music_tension_id, music_combat_id, ambience_id) VALUES
  (37, 'Emberfall Hollow', 1, 10, TRUE, 23, 24, 22, 3);

-- area (2 rows)
INSERT INTO area (zone_id, poi, name, pos_x, pos_y, pos_z, discovery_radius_m, discovery_xp) VALUES
  (37, 'cinderdeep_mine', 'Cinderdeep Mine', -310, 22, 95, 45, 110),
  (37, 'emberfall_village', 'Emberfall Village', 120, 8.5, -240, 60, 85);

-- graveyard (1 rows)
INSERT INTO graveyard (zone_id, ordinal, pos_x, pos_y, pos_z, orientation_deg) VALUES
  (37, 0, 140, 9, -255, 180);

-- gossip (1 rows)
INSERT INTO gossip (npc_id, `text`) VALUES
  (27, 'Mind the mine roads, traveler — the kobolds have gotten bold since the foreman stopped coming back. If you''re headed that way, I''ll make it worth your while.');

SET FOREIGN_KEY_CHECKS = 1;
