// SPDX-License-Identifier: Apache-2.0
//
// Project Meridian — engine-agnostic client net core: FlatBuffers codec helpers
// (issue #95).
//
// The wire payloads are FlatBuffers tables (schema/net/auth.fbs IF-1,
// schema/net/world.fbs IF-2), generated by flatc — the SAME codegen authd/worldd
// and the bot use, so client↔server serialization agrees by construction.
//
// This header provides two things:
//   1. Template helpers (verify_and_get / finish_to_bytes) that apply the untrusted-
//      input discipline the whole codebase uses: NEVER GetRoot without first running
//      the FlatBuffers Verifier over the bytes. These are header-only (they need the
//      flatbuffers runtime; a consumer that uses them includes the generated header
//      for T).
//   2. Concrete, POD-in/POD-out encode/decode functions for the messages the client
//      actually sends/consumes (ClientHello IF-1; MovementIntent / MovementState /
//      Disconnect IF-2). These keep the generated FlatBuffers types OUT of the
//      public API so callers (and the test suite) round-trip through plain structs
//      without depending on flatc codegen at their call site.
//
// CLEAN-ROOM: from the .fbs contracts + the FlatBuffers public API. No GPL source
// consulted (CONTRIBUTING.md).

#ifndef MERIDIAN_CLIENTNET_CODEC_H
#define MERIDIAN_CLIENTNET_CODEC_H

#include <cstdint>
#include <optional>
#include <string>

#include "meridian/clientnet/framing.h"  // Bytes

namespace meridian::clientnet::codec {

// ---------------------------------------------------------------------------
// IF-1 (auth.fbs) — ClientHello, the first frame the client sends to authd.
// ---------------------------------------------------------------------------
struct ClientHello {
    std::uint32_t build = 0;
    std::uint16_t proto_ver = 0;
};

Bytes encode_client_hello(const ClientHello& in);
std::optional<ClientHello> decode_client_hello(const Bytes& buf);

// ---------------------------------------------------------------------------
// IF-2 (world.fbs) — MovementIntent (C→S) and MovementState (S→C).
// ---------------------------------------------------------------------------
struct MovementIntent {
    std::uint32_t seq = 0;
    std::uint32_t state_flags = 0;
    float x = 0.0f, y = 0.0f, z = 0.0f;
    float orientation = 0.0f;
    std::uint64_t client_time_ms = 0;
};

Bytes encode_movement_intent(const MovementIntent& in);
std::optional<MovementIntent> decode_movement_intent(const Bytes& buf);

struct MovementState {
    std::uint64_t entity_guid = 0;
    std::uint32_t ack_seq = 0;
    std::uint32_t state_flags = 0;
    float x = 0.0f, y = 0.0f, z = 0.0f;
    float orientation = 0.0f;
    std::uint64_t server_time_ms = 0;
};

Bytes encode_movement_state(const MovementState& in);
std::optional<MovementState> decode_movement_state(const Bytes& buf);

// ---------------------------------------------------------------------------
// IF-2 (world.fbs) — Disconnect (S→C), the grant-reject / server-close payload.
// ---------------------------------------------------------------------------
struct Disconnect {
    std::uint16_t reason = 0;  // world.fbs DisconnectReason
    std::string message;
};

Bytes encode_disconnect(const Disconnect& in);
std::optional<Disconnect> decode_disconnect(const Bytes& buf);

}  // namespace meridian::clientnet::codec

#endif  // MERIDIAN_CLIENTNET_CODEC_H
