// SPDX-License-Identifier: Apache-2.0
//
// Project Meridian — engine-agnostic client net core: FlatBuffers codec helpers
// (issue #95).
//
// The wire payloads are FlatBuffers tables (schema/net/auth.fbs IF-1,
// schema/net/world.fbs IF-2), generated by flatc — the SAME codegen authd/worldd
// and the bot use, so client↔server serialization agrees by construction.
//
// This header provides two things:
//   1. Template helpers (verify_and_get / finish_to_bytes) that apply the untrusted-
//      input discipline the whole codebase uses: NEVER GetRoot without first running
//      the FlatBuffers Verifier over the bytes. These are header-only (they need the
//      flatbuffers runtime; a consumer that uses them includes the generated header
//      for T).
//   2. Concrete, POD-in/POD-out encode/decode functions for the messages the client
//      actually sends/consumes (ClientHello IF-1; MovementIntent / MovementState /
//      Disconnect IF-2). These keep the generated FlatBuffers types OUT of the
//      public API so callers (and the test suite) round-trip through plain structs
//      without depending on flatc codegen at their call site.
//
// CLEAN-ROOM: from the .fbs contracts + the FlatBuffers public API. No GPL source
// consulted (CONTRIBUTING.md).

#ifndef MERIDIAN_CLIENTNET_CODEC_H
#define MERIDIAN_CLIENTNET_CODEC_H

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

#include "meridian/clientnet/framing.h"  // Bytes

namespace meridian::clientnet::codec {

// ---------------------------------------------------------------------------
// IF-1 (auth.fbs) — ClientHello, the first frame the client sends to authd.
// ---------------------------------------------------------------------------
struct ClientHello {
    std::uint32_t build = 0;
    std::uint16_t proto_ver = 0;
};

Bytes encode_client_hello(const ClientHello& in);
std::optional<ClientHello> decode_client_hello(const Bytes& buf);

// ---------------------------------------------------------------------------
// IF-2 (world.fbs) — MovementIntent (C→S) and MovementState (S→C).
// ---------------------------------------------------------------------------
struct MovementIntent {
    std::uint32_t seq = 0;
    std::uint32_t state_flags = 0;
    float x = 0.0f, y = 0.0f, z = 0.0f;
    float orientation = 0.0f;
    std::uint64_t client_time_ms = 0;
};

Bytes encode_movement_intent(const MovementIntent& in);
std::optional<MovementIntent> decode_movement_intent(const Bytes& buf);

struct MovementState {
    std::uint64_t entity_guid = 0;
    std::uint32_t ack_seq = 0;
    std::uint32_t state_flags = 0;
    float x = 0.0f, y = 0.0f, z = 0.0f;
    float orientation = 0.0f;
    std::uint64_t server_time_ms = 0;
};

Bytes encode_movement_state(const MovementState& in);
std::optional<MovementState> decode_movement_state(const Bytes& buf);

// ---------------------------------------------------------------------------
// IF-2 (world.fbs) — Disconnect (S→C), the grant-reject / server-close payload.
// ---------------------------------------------------------------------------
struct Disconnect {
    std::uint16_t reason = 0;  // world.fbs DisconnectReason
    std::string message;
};

Bytes encode_disconnect(const Disconnect& in);
std::optional<Disconnect> decode_disconnect(const Bytes& buf);

// ---------------------------------------------------------------------------
// IF-2 (world.fbs) — the #87 AoI relay: EntityEnter / EntityUpdate / EntityLeave
// (all S→C). These are the frames a client renders OTHER players from: a session
// spawns/enters range (EntityEnter), moves (EntityUpdate), or leaves range
// (EntityLeave). This is the ONE shared decode both the GUI net path
// (net_thread_core / MeridianNetThread) and the headless client-world probe use to
// turn a relay frame into a position for the remote interpolator — the single
// source of truth for the client-side entity-relay codec (the bot's separate
// bot_core.capture_entity_frame mirrors the same schema).
//
// Positions carry the WIRE (Z-UP) frame from world.fbs: x/y = ground plane, z =
// height. The consumer maps to the render frame (the interpolator / Godot node).

// EntityEnter (world.fbs): a full spawn/enter snapshot. attrs are ignored at M0
// (D-11 placeholder carries none); guid + type + pose drive render, and the vitals
// block (#430/#431 HUD contract, UI-01) drives the unit frame. Vitals are additive
// FlatBuffers fields — a pre-#430 EntityEnter decodes them to 0 / empty.
struct EntityEnter {
    std::uint64_t entity_guid = 0;
    std::uint32_t type_id = 0;
    float x = 0.0f, y = 0.0f, z = 0.0f;  // wire coords (z = height)
    float orientation = 0.0f;
    std::uint8_t char_class = 0;  // M0-frozen class id (roster.h Class; #328) — the
                                  // client colors the placeholder capsule by class.
                                  // 0 = unset/unknown.
    // Vitals (#430 HUD contract): server-authoritative; the client DISPLAYS them.
    std::uint32_t health = 0;      // current health at entry
    std::uint32_t max_health = 0;  // health cap
    std::uint32_t power = 0;       // current secondary power at entry
    std::uint32_t max_power = 0;   // secondary-power cap (0 when power_type = NONE)
    std::uint8_t power_type = 0;   // world.fbs PowerType (0=NONE,1=MANA,2=ENERGY,3=RAGE)
    std::uint16_t level = 0;       // unit level (0 = unset/unknown)
    std::string name;              // display name for the unit frame (empty = unnamed)
};

Bytes encode_entity_enter(const EntityEnter& in);
std::optional<EntityEnter> decode_entity_enter(const Bytes& buf);

// VitalsUpdate (world.fbs, #430/#431): a unit's vitals changed — the HUD delta the
// server pushes to the subject's own client + every observer whenever combat / heal
// / death / level-up moves health/power/level (no full re-enter). `name` is NOT here
// (it does not change in-life; it rides EntityEnter). Server-authoritative — the
// client DISPLAYS these, never predicts them (Principle 1).
struct VitalsUpdate {
    std::uint64_t entity_guid = 0;
    std::uint32_t health = 0;      // current health after the change (0 = dead)
    std::uint32_t max_health = 0;  // health cap (may change on level-up)
    std::uint32_t power = 0;       // current secondary power after the change
    std::uint32_t max_power = 0;   // secondary-power cap (0 when power_type = NONE)
    std::uint8_t power_type = 0;   // world.fbs PowerType (0=NONE,1=MANA,2=ENERGY,3=RAGE)
    std::uint16_t level = 0;       // unit level after the change (level-up)
};

Bytes encode_vitals_update(const VitalsUpdate& in);
std::optional<VitalsUpdate> decode_vitals_update(const Bytes& buf);

// EntityUpdate (world.fbs): a delta. Position fields are OPTIONAL (a move delta
// carries them; an attribute-only delta would not), so each is flagged present.
struct EntityUpdate {
    std::uint64_t entity_guid = 0;
    bool has_x = false, has_y = false, has_z = false, has_orientation = false;
    float x = 0.0f, y = 0.0f, z = 0.0f;  // wire coords (z = height)
    float orientation = 0.0f;

    // True when the delta carried a position (any of x/y/z) — i.e. the peer moved.
    bool has_position() const { return has_x || has_y || has_z; }
};

// Encode a move delta (all position fields present — matches worldd's move relay).
Bytes encode_entity_update(const EntityUpdate& in);
std::optional<EntityUpdate> decode_entity_update(const Bytes& buf);

// EntityLeave (world.fbs): the peer left the client's AoI.
struct EntityLeave {
    std::uint64_t entity_guid = 0;
    std::uint16_t reason = 0;  // world.fbs LeaveReason
};

Bytes encode_entity_leave(const EntityLeave& in);
std::optional<EntityLeave> decode_entity_leave(const Bytes& buf);

// ---------------------------------------------------------------------------
// IF-2 (world.fbs) — character management (D-35 / #286) + server-authoritative
// enter-world (D-35 / #341), over the AUTHENTICATED world session (post-HandshakeOk).
// The client lists/creates/deletes its OWN account's characters (worldd scopes
// every op to the session's grant-derived account) and then ENTER_WORLDs one.
// Status fields are the world.fbs enum ordinals (kept as u16 so the codec has no
// generated-enum dependency): CharCreateStatus{OK=0,DUPLICATE_NAME=1,INVALID_NAME=2,
// INVALID_RACE=3,INVALID_CLASS=4,LIMIT_REACHED=5,INTERNAL=6},
// CharDeleteStatus{OK=0,REFUSED=1,INTERNAL=2}, EnterWorldStatus{OK=0,NOT_FOUND=1,
// NO_CHARACTER=2,INTERNAL=3}.
// ---------------------------------------------------------------------------

// One roster row (world.fbs CharListEntry).
struct CharSummary {
    std::uint64_t character_id = 0;
    std::string name;
    std::uint8_t race = 0;
    std::uint8_t char_class = 0;
    std::uint16_t level = 0;
};

// CHAR_LIST_REQUEST carries no fields (the account is the session's).
Bytes encode_char_list_request();

// CHAR_LIST_RESPONSE — the account's roster (0 or 1 at M0, #329).
struct CharListResponse {
    std::vector<CharSummary> characters;
};
std::optional<CharListResponse> decode_char_list_response(const Bytes& buf);

// CHAR_CREATE_REQUEST — name + M0-frozen race/class.
struct CharCreateRequest {
    std::string name;
    std::uint8_t race = 0;
    std::uint8_t char_class = 0;
};
Bytes encode_char_create_request(const CharCreateRequest& in);

// CHAR_CREATE_RESPONSE — typed status + (on OK) the minted id.
struct CharCreateResponse {
    std::uint16_t status = 0;  // CharCreateStatus
    std::uint64_t character_id = 0;
};
std::optional<CharCreateResponse> decode_char_create_response(const Bytes& buf);

// CHAR_DELETE_REQUEST — one owned character id.
Bytes encode_char_delete_request(std::uint64_t character_id);

// CHAR_DELETE_RESPONSE — ok / refused.
struct CharDeleteResponse {
    std::uint16_t status = 0;  // CharDeleteStatus
};
std::optional<CharDeleteResponse> decode_char_delete_response(const Bytes& buf);

// ENTER_WORLD_REQUEST — spawn as this owned character.
Bytes encode_enter_world_request(std::uint64_t character_id);

// ENTER_WORLD_RESPONSE — typed enter result (OK spawns; else no spawn).
struct EnterWorldResponse {
    std::uint16_t status = 0;  // EnterWorldStatus
};
std::optional<EnterWorldResponse> decode_enter_world_response(const Bytes& buf);

// S→C response ENCODERS — the client never sends these, but mocks/tests (the net
// thread's replay harness, #97) build server frames through the SAME POD API rather
// than the generated types. Symmetric with encode_movement_state / encode_entity_*.
Bytes encode_char_list_response(const CharListResponse& in);
Bytes encode_char_create_response(const CharCreateResponse& in);
Bytes encode_char_delete_response(const CharDeleteResponse& in);
Bytes encode_enter_world_response(const EnterWorldResponse& in);

// ---------------------------------------------------------------------------
// IF-2 (world.fbs) — QUEST STATE (M1 QST-01, #371/#433) and NPC GOSSIP (M1
// NPC-01/02, #372/#433). The client is a pure DISPLAY of server-authoritative
// quest/gossip state (Principle 1 "server is law"): it ENCODES intents (accept a
// quest, turn one in, open gossip, request the log) and DECODES the typed results +
// snapshots the server pushes back. It never predicts quest state.
//
// Enum fields ride as u16/u8 ordinals (world.fbs QuestAcceptStatus / QuestTurnInStatus
// / QuestObjectiveType / GossipOptionKind) so this POD API carries no generated-enum
// dependency, exactly like the CharCreateStatus/EnterWorldStatus fields above.
// ---------------------------------------------------------------------------

// --- Gossip (0x52xx) --------------------------------------------------------

// GOSSIP_HELLO (C→S): open gossip on a targeted NPC entity guid. At M1 the guid maps
// 1:1 to the NPC template id (no NPC entities spawn yet — worldd's npc_store lookup).
struct GossipHello {
    std::uint64_t npc_guid = 0;
};
Bytes encode_gossip_hello(const GossipHello& in);
std::optional<GossipHello> decode_gossip_hello(const Bytes& buf);  // test/mock symmetry

// One computed gossip option (a menu row). `kind` is world.fbs GossipOptionKind
// (0=QUEST_AVAILABLE, 1=QUEST_IN_PROGRESS, 2=QUEST_COMPLETE, 3=VENDOR, 4=TRAINER);
// `target_id` is the quest id for the quest kinds, 0 for vendor/trainer.
struct GossipOption {
    std::uint16_t kind = 0;
    std::uint32_t target_id = 0;
};

// GOSSIP_MENU (S→C): the server-computed, state-gated option list for THIS player.
struct GossipMenu {
    std::uint64_t npc_guid = 0;
    std::vector<GossipOption> options;
};
Bytes encode_gossip_menu(const GossipMenu& in);  // test/mock symmetry (client decodes)
std::optional<GossipMenu> decode_gossip_menu(const Bytes& buf);

// --- Quest (0x40xx) ---------------------------------------------------------

// QUEST_ACCEPT (C→S): accept `quest_id` from the targeted `giver_guid` NPC.
struct QuestAccept {
    std::uint32_t quest_id = 0;
    std::uint64_t giver_guid = 0;
};
Bytes encode_quest_accept(const QuestAccept& in);
std::optional<QuestAccept> decode_quest_accept(const Bytes& buf);  // test/mock symmetry

// QUEST_ACCEPT_RESULT (S→C): typed accept outcome. `status` is world.fbs
// QuestAcceptStatus (0=OK; 1..7 = the typed rejections).
struct QuestAcceptResult {
    std::uint32_t quest_id = 0;
    std::uint16_t status = 0;
};
Bytes encode_quest_accept_result(const QuestAcceptResult& in);  // test/mock symmetry
std::optional<QuestAcceptResult> decode_quest_accept_result(const Bytes& buf);

// One objective's live state within a quest-log entry. `type` is world.fbs
// QuestObjectiveType (0=KILL,1=COLLECT,2=DELIVER,3=EXPLORE); `target_id` is the
// subject content id (creature/item/zone) per `type`.
struct QuestObjectiveState {
    std::uint16_t type = 0;
    std::uint32_t target_id = 0;
    std::uint16_t have = 0;
    std::uint16_t need = 0;
    bool complete = false;
};

// QUEST_PROGRESS (S→C): a single objective advanced (kill/collect/deliver/explore).
struct QuestProgress {
    std::uint32_t quest_id = 0;
    std::uint8_t objective_index = 0;
    std::uint16_t type = 0;  // QuestObjectiveType
    std::uint16_t have = 0;
    std::uint16_t need = 0;
    bool complete = false;
};
Bytes encode_quest_progress(const QuestProgress& in);  // test/mock symmetry
std::optional<QuestProgress> decode_quest_progress(const Bytes& buf);

// QUEST_TURN_IN (C→S): turn `quest_id` in at `turn_in_guid`. `choice_index` selects a
// reward for a choice-reward quest (>= 0), or -1 when the quest offers no choice.
struct QuestTurnIn {
    std::uint32_t quest_id = 0;
    std::uint64_t turn_in_guid = 0;
    std::int32_t choice_index = -1;
};
Bytes encode_quest_turn_in(const QuestTurnIn& in);
std::optional<QuestTurnIn> decode_quest_turn_in(const Bytes& buf);  // test/mock symmetry

// A reward item actually granted at turn-in (item template id + count).
struct QuestRewardItem {
    std::uint32_t item_id = 0;
    std::uint16_t count = 1;
};

// QUEST_TURN_IN_RESULT (S→C): typed turn-in outcome. On OK the rewards were granted;
// `status` is world.fbs QuestTurnInStatus (0=OK; 1..6 = the typed rejections).
struct QuestTurnInResult {
    std::uint32_t quest_id = 0;
    std::uint16_t status = 0;
    std::uint32_t reward_xp = 0;
    std::int64_t reward_money = 0;  // copper (ECO-01)
    std::vector<QuestRewardItem> reward_items;
    std::uint16_t new_level = 0;
};
Bytes encode_quest_turn_in_result(const QuestTurnInResult& in);  // test/mock symmetry
std::optional<QuestTurnInResult> decode_quest_turn_in_result(const Bytes& buf);

// One active quest in the log snapshot.
struct QuestLogEntry {
    std::uint32_t quest_id = 0;
    std::uint16_t level = 0;
    bool complete = false;
    std::vector<QuestObjectiveState> objectives;
};

// QUEST_LOG (C↔S): C→S an EMPTY QuestLog is the "send me my log" request; S→C the
// populated QuestLog is the authoritative active-quest snapshot the client renders its
// quest log + tracker from. `encode_quest_log({})` builds the empty request body.
struct QuestLog {
    std::vector<QuestLogEntry> quests;
};
Bytes encode_quest_log(const QuestLog& in);  // C→S request (empty) + S→C mock symmetry
std::optional<QuestLog> decode_quest_log(const Bytes& buf);

}  // namespace meridian::clientnet::codec

#endif  // MERIDIAN_CLIENTNET_CODEC_H
