"""Pure-Python Blender version-pin guard (spec ④ §9).

Every bpy entry point in this repo (``generate_rig.py``, ``generate_blockout.py``,
``tools/meshy/convert_rig.py``, ``tests/fixtures/meshy/build_fixture.py``) builds
artifacts whose export is only byte-deterministic when generated by one exact
Blender build. :data:`PINNED_VERSION` below is the single source of truth for
that build — ``tools/blender/README.md`` documents it for humans, but this
constant is what entry points actually enforce; the doc is not re-parsed at
runtime (a second copy of the value would be one more place to drift).

This module never imports ``bpy`` so :func:`check_pin` is unit-testable without
Blender (see ``tests/test_meridian_rig.py``). Each bpy entry point calls it with
the live ``bpy.app.version`` at startup and hard-errors — naming both the
pinned version and the version found — unless its ``--allow-unpinned-blender``
escape hatch is passed (development only; see each entry point's ``--help``).
"""
from __future__ import annotations

from collections.abc import Sequence

# Canonical pin (spec ④ §9). Keep in lockstep with the "Blender version pin"
# line in tools/blender/README.md, which documents this value for humans.
PINNED_VERSION = "5.0.0"


def check_pin(version_tuple: Sequence[int], pinned: str = PINNED_VERSION) -> str | None:
    """Compare a live ``bpy.app.version`` tuple against the pinned version.

    Returns ``None`` when they match exactly. Otherwise returns a human-readable
    error naming both the pinned version and the version found — or, if
    ``pinned`` or ``version_tuple`` is malformed, an error describing what was
    wrong with the input. Never raises: callers can treat any non-``None``
    return as a hard-error message to print and act on.
    """
    pinned_tuple = _parse_pinned(pinned)
    if pinned_tuple is None:
        return (
            f"blender_pin: malformed pinned version {pinned!r} "
            "(expected 'MAJOR.MINOR.PATCH')"
        )

    found_tuple = _coerce_found(version_tuple)
    if found_tuple is None:
        return (
            f"blender_pin: malformed Blender version {version_tuple!r} from "
            "bpy.app.version (expected a 3-int sequence)"
        )

    if found_tuple != pinned_tuple:
        found_str = ".".join(str(v) for v in found_tuple)
        return (
            f"Blender version mismatch: Project Meridian is pinned to Blender "
            f"{pinned} (tools/blender/README.md), but this session reports "
            f"Blender {found_str}. Regenerated artifacts would not be "
            f"byte-identical to the committed ones. Install the pinned build, "
            f"or pass --allow-unpinned-blender to proceed anyway (development "
            f"only; byte-determinism is not guaranteed)."
        )
    return None


def _parse_pinned(pinned: str) -> tuple[int, int, int] | None:
    try:
        parts = pinned.strip().split(".")
    except AttributeError:
        return None
    if len(parts) != 3 or not all(p.isdigit() for p in parts):
        return None
    a, b, c = (int(p) for p in parts)
    return (a, b, c)


def _coerce_found(version_tuple: Sequence[int]) -> tuple[int, int, int] | None:
    try:
        values = tuple(int(v) for v in version_tuple)
    except (TypeError, ValueError):
        return None
    if len(values) != 3:
        return None
    return values
