# SPDX-License-Identifier: Apache-2.0
# Lets the CD runner rollout-restart the realm daemons so cd.yml can repull the
# moving image tag. ARC runs each scale set under its own SA
# (<scaleset>-gha-rs-no-permission), NOT arc-runners/default — the cd.yml restart
# job runs on meridian-amd64, so bind THAT SA. Least-privilege: get/list/patch on
# Deployments in the realm namespace only. (meridian-ptr Role added in Phase 3.)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: meridian-restarter
  namespace: meridian-dev
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: meridian-restarter
  namespace: meridian-dev
subjects:
  - kind: ServiceAccount
    name: meridian-amd64-gha-rs-no-permission
    namespace: arc-runners
roleRef:
  kind: Role
  name: meridian-restarter
  apiGroup: rbac.authorization.k8s.io
