"""C++20 emitter for the schema-driven struct generator (Tools SAD §2.1).

Emits a single self-contained header `content_types.gen.hpp` in namespace
`mcc::content`: one struct per schema type + nested/union structs, enums as
`enum class`, typed id references as tiny strong-typedef wrappers over
std::string, required scalars as plain members and optional ones as
std::optional<...>, arrays as std::vector<...>.

Header-only, no third-party deps (yaml-cpp decoding is a later mcc task; this is
the typed model the decoder targets). Deterministic byte-for-byte given a schema.
"""

from __future__ import annotations

from .ir import (
    ArrayType,
    EnumType,
    IrModel,
    IrStruct,
    NestedType,
    RefType,
    ScalarType,
    UnionType,
    enum_member_ident,
)

# UnionType is referenced only as a field type (resolved by name in _type_str).

_SCALAR_CPP = {
    "string": "std::string",
    "integer": "std::int64_t",
    "number": "double",
    "boolean": "bool",
    "null": "std::monostate",
}

# Doc names for the id newtypes, keyed by ref kind.
_REF_TYPE_NAME = {
    "content": "ContentId",
    "npc": "NpcRef",
    "item": "ItemRef",
    "quest": "QuestRef",
    "ability": "AbilityRef",
    "loot": "LootRef",
    "vendor": "VendorRef",
    "zone": "ZoneRef",
    "equip_type": "EquipTypeRef",
    "appearance": "AppearanceRef",
    "attribute": "AttributeRef",
    "talent": "TalentRef",
    "asset": "AssetId",
    "art": "ArtRef",
    "mus": "MusRef",
    "sfx": "SfxRef",
    "amb": "AmbRef",
}


def _ref_type_name(kind: str) -> str:
    return _REF_TYPE_NAME[kind]


def _type_str(t) -> str:
    if isinstance(t, ScalarType):
        return _SCALAR_CPP[t.json_type]
    if isinstance(t, RefType):
        return _ref_type_name(t.ref_kind)
    if isinstance(t, EnumType):
        return t.name
    if isinstance(t, NestedType):
        return t.name
    if isinstance(t, UnionType):
        return t.name
    if isinstance(t, ArrayType):
        return f"std::vector<{_type_str(t.element)}>"
    raise TypeError(f"unhandled IR type {t!r}")


def _member_decl(t, required: bool) -> str:
    base = _type_str(t)
    # Arrays are already "empty-able"; keep them plain even when optional.
    if required or isinstance(t, ArrayType):
        return base
    return f"std::optional<{base}>"


def _enum_value(name: str) -> str:
    # C++ enumerators: sanitized PascalCase of the schema value. `None` is a
    # macro-safe keyword-ish token; keep it distinct just in case.
    ident = enum_member_ident(name)
    return "None_" if ident == "None" else ident


def emit(model: IrModel) -> str:
    lines: list[str] = []
    w = lines.append

    w("// content_types.gen.hpp — GENERATED by tools/schema_gen. DO NOT EDIT.")
    w("//")
    w("// Typed content model for mcc/worldd, generated from /schema/content")
    w('// (Tools SAD §2.1: "one C++ struct per schema type"). Regenerate with:')
    w("//     uv run python -m tools.schema_gen.generate")
    w("// A drift guard (tests/schema_gen) fails CI if this file is stale.")
    w("#ifndef MCC_CONTENT_TYPES_GEN_HPP")
    w("#define MCC_CONTENT_TYPES_GEN_HPP")
    w("")
    w("#include <cstdint>")
    w("#include <optional>")
    w("#include <string>")
    w("#include <variant>")
    w("#include <vector>")
    w("")
    w("namespace mcc::content {")
    w("")

    # --- typed id references (strong typedefs over std::string) ---
    w('// Typed id references (schema README: "an `item:` field cannot accept an')
    w('// NPC ID"). Each wraps the fully-qualified string id for its target kind.')
    for kind in model.content_ref_kinds + model.asset_ref_kinds:
        name = _ref_type_name(kind)
        w(f"struct {name} {{ std::string id; }};")
    w("")

    # --- enums ---
    for et in model.enums:
        w(f"enum class {et.name} {{")
        for v in et.values:
            w(f"    {_enum_value(v)},")
        w("};")
        w("")

    # --- structs ---
    # The model list is already dependency-ordered: nested objects, tagged-union
    # structs, and shared $def structs (IntRange, Position) are appended to
    # model.structs as they are encountered, i.e. BEFORE the owner struct that
    # references them. So emitting in list order guarantees C++ define-before-use.
    for st in model.structs:
        _emit_struct(w, st)

    w("}  // namespace mcc::content")
    w("")
    w("#endif  // MCC_CONTENT_TYPES_GEN_HPP")
    return "\n".join(lines) + "\n"


def _emit_struct(w, st: IrStruct) -> None:
    if st.is_union:
        w(
            f"// Tagged union (schema oneOf); `{st.tag_field}` selects the active variant."
        )
    elif st.description:
        w(f"// {st.description}")
    w(f"struct {st.name} {{")
    for f in st.fields:
        member = _member_decl(f.type, f.required)
        comment = ""
        if f.description:
            comment = f"  // {f.description}"
        elif not f.required:
            comment = "  // optional"
        w(f"    {member} {_cpp_field(f.name)};{comment}")
    w("};")
    w("")


def _cpp_field(name: str) -> str:
    # Schema field names are already valid C++ identifiers ([a-z0-9_]); guard the
    # rare reserved word just in case future fields collide.
    reserved = {"class", "namespace", "template", "operator", "delete", "new"}
    return f"{name}_" if name in reserved else name
