"""C# emitter for the schema-driven struct generator (Tools SAD §6.1).

Emits a single file `ContentTypes.g.cs` in namespace `Meridian.Codex.Models`:
one record per schema type + nested/union records, enums as `enum`, typed id
references as readonly-record-struct wrappers over string, required scalars as
non-nullable members and optional ones as nullable (`T?`), arrays as
`IReadOnlyList<T>`.

Records give value equality + `with` expressions, which the Avalonia/MVVM editor
uses for change tracking. No third-party deps. Deterministic given a schema.
"""

from __future__ import annotations

from .ir import (
    ArrayType,
    EnumType,
    IrField,
    IrModel,
    IrStruct,
    NestedType,
    RefType,
    ScalarType,
    UnionType,
    enum_member_ident,
    pascal,
)

_SCALAR_CS = {
    "string": "string",
    "integer": "long",
    "number": "double",
    "boolean": "bool",
    # A schema `type: null` field (reserved keys like quest.script). Base type is
    # `object`; the optional-member logic adds the `?`. Reserved-null fields are
    # always optional in practice, so this surfaces as `object?`.
    "null": "object",
}

_REF_TYPE_NAME = {
    "content": "ContentId",
    "npc": "NpcRef",
    "item": "ItemRef",
    "quest": "QuestRef",
    "ability": "AbilityRef",
    "loot": "LootRef",
    "vendor": "VendorRef",
    "zone": "ZoneRef",
    "equip_type": "EquipTypeRef",
    "appearance": "AppearanceRef",
    "attribute": "AttributeRef",
    "asset": "AssetId",
    "art": "ArtRef",
    "mus": "MusRef",
    "sfx": "SfxRef",
    "amb": "AmbRef",
}


def _ref_type_name(kind: str) -> str:
    return _REF_TYPE_NAME[kind]


def _type_str(t) -> str:
    if isinstance(t, ScalarType):
        return _SCALAR_CS[t.json_type]
    if isinstance(t, RefType):
        return _ref_type_name(t.ref_kind)
    if isinstance(t, EnumType):
        return t.name
    if isinstance(t, NestedType):
        return t.name
    if isinstance(t, UnionType):
        return t.name
    if isinstance(t, ArrayType):
        return f"IReadOnlyList<{_type_str(t.element)}>"
    raise TypeError(f"unhandled IR type {t!r}")


def _member_type(t, required: bool) -> str:
    base = _type_str(t)
    if required:
        return base
    # Nullable value + reference types both use `?`; arrays become nullable lists.
    return f"{base}?"


def _pascal_prop(name: str) -> str:
    return pascal(name)


def _enum_member(name: str) -> str:
    # C# allows an enum member named `None`; keep the sanitized identifier as-is.
    return enum_member_ident(name)


def emit(model: IrModel) -> str:
    lines: list[str] = []
    w = lines.append

    w("// ContentTypes.g.cs — GENERATED by tools/schema_gen. DO NOT EDIT.")
    w("//")
    w("// Typed content model for the Codex editor, generated from /schema/content")
    w('// (Tools SAD §6.1: Models/ "same generator as mcc\'s structs, C# target").')
    w("// Regenerate with: uv run python -m tools.schema_gen.generate")
    w("// A drift guard (tests/schema_gen) fails CI if this file is stale.")
    w("#nullable enable")
    w("using System.Collections.Generic;")
    w("")
    w("namespace Meridian.Codex.Models;")
    w("")

    # --- typed id references ---
    w('// Typed id references (schema README: "an `item:` field cannot accept an')
    w('// NPC ID"). Each wraps the fully-qualified string id for its target kind.')
    for kind in model.content_ref_kinds + model.asset_ref_kinds:
        name = _ref_type_name(kind)
        w(f"public readonly record struct {name}(string Id);")
    w("")

    # --- enums ---
    for et in model.enums:
        w(f"public enum {et.name}")
        w("{")
        for v in et.values:
            w(f"    {_enum_member(v)},")
        w("}")
        w("")

    # --- records ---
    for st in model.structs:
        _emit_record(w, st)

    return "\n".join(lines) + "\n"


def _emit_record(w, st: IrStruct) -> None:
    if st.is_union:
        w(
            f"/// <summary>Tagged union (schema oneOf); {st.tag_field} selects the active variant.</summary>"
        )
    elif st.description:
        w(f"/// <summary>{_xml_escape(st.description)}</summary>")
    w(f"public sealed record {st.name}")
    w("{")
    for f in st.fields:
        _emit_property(w, f)
    w("}")
    w("")


def _emit_property(w, f: IrField) -> None:
    if f.description:
        w(f"    /// <summary>{_xml_escape(f.description)}</summary>")
    cs_type = _member_type(f.type, f.required)
    prop = _pascal_prop(f.name)
    if f.required:
        w(f"    public required {cs_type} {prop} {{ get; init; }}")
    else:
        w(f"    public {cs_type} {prop} {{ get; init; }}")


def _xml_escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
