-- world DB DML — generated by mcc emit-sql (IF-4, Tools SAD §2.6).
-- Deterministic full dump: tables in DDL order, rows by primary key.
-- DO NOT EDIT — rebuild with `mcc emit-sql`.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- world_manifest (boot handshake; worldd reads + verifies this).
INSERT INTO world_manifest
  (pack_namespace, pack_version, id_band, content_hash, schema_version, mcc_version, built_at)
VALUES
  ('itm1', '0.1.0', 0, 'fb081b22c33ddbd84a0a9e183f507dff70259f545e7bed020b1433000d055615', 1, '0.0.0', '2026-07-09 00:00:00');

-- npc_template (2 rows)
INSERT INTO npc_template (id, name, subtitle, level_min, level_max, creature_type, `rank`, faction, stat_health, stat_mana, stat_armor, stat_damage_min, stat_damage_max, stat_attack_speed_ms, ai_behavior, ai_aggro_radius_m, ai_leash_radius_m, ai_call_for_help_radius_m, ai_flee_at_health_pct, move_walk_speed_mps, move_run_speed_mps, vendor_ref_id, loot_table_ref_id, loot_money_min, loot_money_max, visual_model_id, visual_scale, visual_sound_set_id) VALUES
  (6, 'Gray Wolf', NULL, 6, 7, 'beast', 'normal', 'hostile', 120, NULL, NULL, 8, 14, 1600, 'aggressive', 18, NULL, NULL, NULL, NULL, NULL, NULL, 5, 2, 6, 12, NULL, NULL),
  (7, 'Marshal Bren', 'Wardens'' Quartermaster', 8, 8, 'humanoid', 'normal', 'friendly', 700, NULL, 180, 12, 18, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, 11, NULL, NULL);

-- item_template (4 rows)
INSERT INTO item_template (id, name, flavor_text, item_class, subclass, slot, rarity, required_level, item_level, is_unique, binding, stack_size, weapon_damage_min, weapon_damage_max, weapon_speed_ms, weapon_school, armor, effect_on_use_id, price_sell, price_buy, visual_icon_id, visual_model_id) VALUES
  (1, 'Draught of Mending', NULL, 'consumable', NULL, NULL, 'common', 1, 1, FALSE, 'none', 5, NULL, NULL, NULL, NULL, NULL, NULL, 30, 150, 14, NULL),
  (2, 'Ironbound Trinket', NULL, 'armor', NULL, 'trinket', 'uncommon', 3, 1, FALSE, 'none', 1, NULL, NULL, NULL, NULL, NULL, NULL, 200, 800, 16, NULL),
  (3, 'Traveler''s Boots', NULL, 'armor', NULL, 'feet', 'common', 2, 1, FALSE, 'none', 1, NULL, NULL, NULL, NULL, 14, NULL, 100, 400, 13, NULL),
  (4, 'Coarse Wolf Pelt', NULL, 'trade_good', NULL, NULL, 'common', 1, 1, FALSE, 'none', 20, NULL, NULL, NULL, NULL, NULL, NULL, 12, NULL, 15, NULL);

-- item_stat (1 rows)
INSERT INTO item_stat (item_id, stat, amount) VALUES
  (2, 'stamina', 4);

-- quest_template (2 rows)
INSERT INTO quest_template (id, name, summary, offer_text, completion_text, level, required_level, zone_ref_id, giver_npc_id, turn_in_npc_id, reward_xp, reward_money) VALUES
  (8, 'Pelts for Bren', 'Gather 3 Coarse Wolf Pelts and bring them to Marshal Bren.', 'Good work on the culling. Now bring me three of their pelts — the Wardens need winter linings, and you''ve earned first pick of the stores.', 'These will keep a scout warm through the pass. Take your reward.', 7, 4, NULL, 7, NULL, 320, 150),
  (9, 'Thin the Pack', 'Slay 5 Gray Wolves on the north road for Marshal Bren.', 'The wolves have taken three wagons this month. Cull five of them and the rest will think twice before creeping down from the ridge.', 'Five fewer fangs on the road. You''ve a steady hand.', 6, 4, NULL, 7, NULL, 250, 300);

-- quest_objective (2 rows)
INSERT INTO quest_objective (quest_id, ordinal, type, target_npc_id, item_id, to_npc_id, zone_ref_id, poi, count) VALUES
  (8, 0, 'collect', NULL, 4, NULL, NULL, NULL, 3),
  (9, 0, 'kill', 6, NULL, NULL, NULL, NULL, 5);

-- quest_prereq (1 rows)
INSERT INTO quest_prereq (quest_id, prereq_quest_id) VALUES
  (8, 9);

-- quest_reward (3 rows)
INSERT INTO quest_reward (quest_id, is_choice, ordinal, item_id, count) VALUES
  (8, TRUE, 0, 2, 1),
  (8, TRUE, 1, 3, 1),
  (9, FALSE, 0, 1, 2);

-- loot_table (1 rows)
INSERT INTO loot_table (id, money_min, money_max) VALUES
  (5, 4, 10);

-- loot_group (1 rows)
INSERT INTO loot_group (loot_table_id, ordinal, name, pick, chance_pct) VALUES
  (5, 0, 'scraps', 1, 35);

-- loot_entry (3 rows)
INSERT INTO loot_entry (loot_table_id, entry_ordinal, group_ordinal, item_id, nested_table_id, chance_pct, weight, quantity_min, quantity_max, quest_ref_id) VALUES
  (5, 0, NULL, 4, NULL, 60, NULL, 1, 1, 8),
  (5, 1, 0, 1, NULL, NULL, 10, NULL, NULL, NULL),
  (5, 2, 0, 2, NULL, NULL, 1, NULL, NULL, NULL);

-- vendor_inventory (1 rows)
INSERT INTO vendor_inventory (id) VALUES
  (10);

-- vendor_inventory_item (2 rows)
INSERT INTO vendor_inventory_item (vendor_id, ordinal, item_id, price_override, limited_count, limited_restock_minutes) VALUES
  (10, 0, 1, NULL, NULL, NULL),
  (10, 1, 3, 500, NULL, NULL);

-- vendor_inventory_buys (3 rows)
INSERT INTO vendor_inventory_buys (vendor_id, item_class) VALUES
  (10, 'armor'),
  (10, 'consumable'),
  (10, 'trade_good');

-- gossip (1 rows)
INSERT INTO gossip (npc_id, `text`) VALUES
  (7, 'The pack has grown bold on the north road. Thin them, bring me their pelts, and I will see you kitted out.');

SET FOREIGN_KEY_CHECKS = 1;
