# SPDX-License-Identifier: Apache-2.0
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meridian-ptr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kwilliams312/project_meridian.git
    targetRevision: ptr
    path: deploy/helm/meridian
    helm:
      valueFiles:
        - ../../gitops/realms/ptr/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: meridian-ptr
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - '.spec.template.metadata.annotations."kubectl.kubernetes.io/restartedAt"'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
