// SPDX-License-Identifier: Apache-2.0
//
// meridian-proto round-trip proof (Issue #67 deliverable 2).
//
// Proves the /schema/net codegen + flatbuffers runtime linkage end to end:
// build a SessionGrant (IF-1, auth.fbs §5.1) into a buffer with a
// FlatBufferBuilder, verify it, read it back, and assert every field survives
// the serialize/deserialize round trip. This is a linkage + codegen proof — it
// does NOT exercise the wire framing (that lives with the transport layer).
//
// A non-zero exit means a field did not round-trip: the build is broken, not the
// test data. Runnable target: meridian-proto-roundtrip.

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <vector>

// Generated by flatc --cpp from schema/net/auth.fbs at build time, into the
// build tree; exposed via meridian-proto's INTERFACE include dir.
#include "auth_generated.h"

namespace {

// Minimal assert that reports which check failed and returns an error count,
// rather than aborting — so a single run reports its full result.
int check(bool ok, const char* what) {
  if (ok) {
    std::printf("  ok    %s\n", what);
    return 0;
  }
  std::printf("  FAIL  %s\n", what);
  return 1;
}

}  // namespace

int main() {
  using meridian::net::CreateSessionGrant;
  using meridian::net::SessionGrant;
  // auth.fbs declares no `root_type`, so flatc emits no Get<Root>/
  // Verify<Root>Buffer free helpers — we use the generic flatbuffers::GetRoot<>
  // and Verifier::VerifyBuffer<> instead. Each message table is a root by
  // contract (schema/net/README.md: "one root table per message").

  // --- Known input ----------------------------------------------------------
  const std::uint64_t kGrantId = 0xDEADBEEFCAFEF00DULL;
  const std::uint32_t kReconnectWindowMs = 15000;
  const std::vector<std::uint8_t> kSessionKey = {
      0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77,
      0x88, 0x99, 0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF,
      0x0F, 0x1E, 0x2D, 0x3C, 0x4B, 0x5A, 0x69, 0x78,
      0x87, 0x96, 0xA5, 0xB4, 0xC3, 0xD2, 0xE1, 0xF0,
  };  // 32-byte session_key, per auth DB BINARY(32) (server SAD §4.1).

  std::printf("meridian-proto round-trip: SessionGrant (auth.fbs, IF-1)\n");

  // --- Serialize ------------------------------------------------------------
  flatbuffers::FlatBufferBuilder builder;
  auto key_vec = builder.CreateVector(kSessionKey);
  auto grant =
      CreateSessionGrant(builder, kGrantId, key_vec, kReconnectWindowMs);
  builder.Finish(grant);

  const std::uint8_t* buf = builder.GetBufferPointer();
  const std::size_t size = builder.GetSize();
  std::printf("  built %zu-byte buffer\n", size);

  int errors = 0;

  // --- Verify (the same check the gateway runs on inbound frames) -----------
  flatbuffers::Verifier verifier(buf, size);
  errors += check(verifier.VerifyBuffer<SessionGrant>(nullptr),
                  "buffer verifies");

  // --- Deserialize & assert every field survived ----------------------------
  const SessionGrant* got = flatbuffers::GetRoot<SessionGrant>(buf);
  errors += check(got != nullptr, "root table present");

  if (got != nullptr) {
    errors += check(got->grant_id() == kGrantId, "grant_id round-trips");
    errors += check(got->reconnect_window_ms() == kReconnectWindowMs,
                    "reconnect_window_ms round-trips");

    const auto* key = got->session_key();
    errors += check(key != nullptr, "session_key present");
    if (key != nullptr) {
      errors += check(key->size() == kSessionKey.size(),
                      "session_key length round-trips");
      const bool bytes_match =
          key->size() == kSessionKey.size() &&
          std::memcmp(key->data(), kSessionKey.data(), kSessionKey.size()) == 0;
      errors += check(bytes_match, "session_key bytes round-trip");
    }
  }

  if (errors == 0) {
    std::printf(
        "PASS: grant_id=0x%016llX reconnect_window_ms=%u session_key[%zu] all "
        "survived round trip\n",
        static_cast<unsigned long long>(got->grant_id()),
        got->reconnect_window_ms(), kSessionKey.size());
    return 0;
  }

  std::printf("FAIL: %d field(s) did not round-trip\n", errors);
  return 1;
}
