// Project Meridian — engine-free unit test for the client IF-5 pack-manifest
// verify core (issue #107). NO Godot: compiles against the plain-C++ core
// (pack_manifest_core.*), so it runs in any C++17 toolchain (Client SAD §9.2
// engine-agnostic cores). Plain-main style, mirroring the movement / telemetry
// tests.
//
// Proves the #107 test matrix (the client counterpart to worldd's #89 boot
// check):
//   (a) a valid emit-pck manifest -> kOk, exposes the content version + hash
//   (b) unsupported content_schema_version -> kSchemaMismatch (fail fast)
//   (c) malformed manifests -> kMalformed:
//         - missing required field (empty namespace / version)
//         - bad-width content_hash / bad-width entry hash
//         - entry_count != entries.size()
//         - unparseable / wrong manifest schema tag
//   (d) ROUND-TRIP against a REAL manifest produced by `mcc emit-pck` (checked-in
//       fixture generated from content/core) -> the verifier and the emitter
//       agree on the exact JSON shape (the key #107 cross-tool invariant).
// Plus: the engine pin (kEngineMismatch), the realm content-hash pin
// (kHashMismatch), forward-compat (unknown keys ignored), and the optional
// per-entry hash check (verify_entry_hash).
//
// Exit code 0 = all pass; non-zero = at least one failure.

#include "pack_manifest_core.h"

#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>

namespace pk = meridian::pack;

static int g_fail = 0;
static int g_checks = 0;

static void check(const char *name, bool ok, const std::string &detail = "") {
	++g_checks;
	std::printf("  [%s] %s\n", ok ? "PASS" : "FAIL", name);
	if (!ok) {
		++g_fail;
		if (!detail.empty()) std::printf("        %s\n", detail.c_str());
	}
}

// ── The checked-in REAL emit-pck manifest (test/fixtures/), located relative to
// this source file so the test is runnable from any build dir. Generated by:
//   mcc link <content/core copy>  &&  mcc emit-pck <copy> --built-at "…" --godot-version 4.6
// from the repo's content/core pack. This is the round-trip anchor: the verifier
// MUST accept exactly what the emitter produces.
static std::string fixture_dir() {
	std::string f = __FILE__;
	const std::size_t slash = f.find_last_of("/\\");
	const std::string dir = (slash == std::string::npos) ? std::string(".") : f.substr(0, slash);
	return dir + "/fixtures";
}

static bool read_file(const std::string &path, std::string &out) {
	std::ifstream in(path, std::ios::binary);
	if (!in) return false;
	std::ostringstream ss;
	ss << in.rdbuf();
	out = ss.str();
	return true;
}

// A minimal hand-built valid manifest (1 entry) for the mutate-and-check cases,
// so those tests do not depend on the large fixture. Matches emit-pck's key
// order + shape exactly.
static std::string minimal_manifest(std::uint32_t schema_version = 1,
                                    const std::string &godot = "4.6") {
	std::ostringstream j;
	j << "{\n"
	  << "  \"schema\": \"meridian/pack-manifest@1\",\n"
	  << "  \"pack\": \"core\",\n"
	  << "  \"namespace\": \"core\",\n"
	  << "  \"version\": \"1.2.3\",\n"
	  << "  \"content_schema_version\": " << schema_version << ",\n"
	  << "  \"godot_version\": \"" << godot << "\",\n"
	  << "  \"id_band\": 0,\n"
	  << "  \"content_hash\": \"" << std::string(64, 'a') << "\",\n"
	  << "  \"mcc_version\": \"0.0.0\",\n"
	  << "  \"built_at\": \"2026-07-06 12:00:00\",\n"
	  << "  \"entry_count\": 1,\n"
	  << "  \"entries\": [\n"
	  << "    { \"id\": \"core:item.wand\", \"numeric_id\": 1, \"type\": \"item\", "
	  << "\"resource\": \"res://meridian/core/tables/item.bin\", \"hash\": \""
	  << std::string(64, 'b') << "\" }\n"
	  << "  ]\n"
	  << "}\n";
	return j.str();
}

// -- (a) a valid manifest verifies OK and exposes the identity ----------------
static void test_valid_ok() {
	std::printf("test_valid_ok (well-formed manifest -> kOk, identity exposed)\n");
	const pk::PackReport rep = pk::verify_pack_manifest_json(minimal_manifest());
	check("verdict is kOk", rep.verdict == pk::PackVerdict::kOk, rep.reason);
	check("not a hard fail", !rep.hard_fail);
	check("content_version = core@1.2.3", rep.content_version == "core@1.2.3",
	      rep.content_version);
	check("content_hash exposed (64-hex)", rep.content_hash == std::string(64, 'a'),
	      rep.content_hash);
	check("godot_version exposed", rep.godot_version == "4.6", rep.godot_version);
	check("content_schema_version = 1", rep.content_schema_version == 1);
	check("entry_count = 1", rep.entry_count == 1);
}

// -- (b) unsupported content_schema_version -> kSchemaMismatch (fail fast) -----
static void test_schema_mismatch() {
	std::printf("test_schema_mismatch (unsupported schema -> kSchemaMismatch)\n");
	// A future schema (v2) this client does not implement.
	const pk::PackReport rep = pk::verify_pack_manifest_json(minimal_manifest(2));
	check("verdict is kSchemaMismatch", rep.verdict == pk::PackVerdict::kSchemaMismatch,
	      rep.reason);
	check("hard fail (refuse to boot)", rep.hard_fail);
	check("reason names the schema", rep.reason.find("content_schema_version 2") != std::string::npos ||
	      rep.reason.find("schema") != std::string::npos, rep.reason);
	// Identity still resolved (so the boot UX can name what it rejected).
	check("identity resolved despite mismatch", rep.content_version == "core@1.2.3",
	      rep.content_version);

	// schema v0 (an absent/garbage field) is also a mismatch.
	const pk::PackReport rep0 = pk::verify_pack_manifest_json(minimal_manifest(0));
	check("schema v0 -> kSchemaMismatch", rep0.verdict == pk::PackVerdict::kSchemaMismatch);
}

// -- (c) malformed manifests -> kMalformed ------------------------------------
static void test_malformed() {
	std::printf("test_malformed (missing field / bad hash / count / bad JSON)\n");

	// Unparseable bytes.
	check("garbage bytes -> kMalformed",
	      pk::verify_pack_manifest_json("not json at all {[").verdict ==
	          pk::PackVerdict::kMalformed);

	// Truncated JSON (unclosed object).
	check("truncated JSON -> kMalformed",
	      pk::verify_pack_manifest_json("{\"schema\": \"meridian/pack-manifest@1\"").verdict ==
	          pk::PackVerdict::kMalformed);

	// Wrong manifest schema tag.
	{
		std::string m = minimal_manifest();
		const std::string bad = "meridian/pack-manifest@2";
		const std::size_t p = m.find("meridian/pack-manifest@1");
		m.replace(p, std::string("meridian/pack-manifest@1").size(), bad);
		check("wrong manifest schema tag -> kMalformed",
		      pk::verify_pack_manifest_json(m).verdict == pk::PackVerdict::kMalformed);
	}

	// Empty namespace (missing required field).
	{
		std::string m = minimal_manifest();
		const std::size_t p = m.find("\"namespace\": \"core\"");
		m.replace(p, std::string("\"namespace\": \"core\"").size(), "\"namespace\": \"\"");
		const pk::PackReport rep = pk::verify_pack_manifest_json(m);
		check("empty namespace -> kMalformed", rep.verdict == pk::PackVerdict::kMalformed,
		      rep.reason);
	}

	// Bad-width content_hash (63 chars).
	{
		std::string m = minimal_manifest();
		const std::string good = std::string(64, 'a');
		const std::size_t p = m.find(good);
		m.replace(p, good.size(), std::string(63, 'a'));
		const pk::PackReport rep = pk::verify_pack_manifest_json(m);
		check("63-char content_hash -> kMalformed", rep.verdict == pk::PackVerdict::kMalformed,
		      rep.reason);
	}

	// Non-hex char in content_hash.
	{
		std::string m = minimal_manifest();
		const std::string good = std::string(64, 'a');
		const std::size_t p = m.find(good);
		std::string bad = std::string(63, 'a') + "g";  // 'g' is not lower-hex
		m.replace(p, good.size(), bad);
		check("non-hex content_hash -> kMalformed",
		      pk::verify_pack_manifest_json(m).verdict == pk::PackVerdict::kMalformed);
	}

	// entry_count != entries.size().
	{
		std::string m = minimal_manifest();
		const std::size_t p = m.find("\"entry_count\": 1");
		m.replace(p, std::string("\"entry_count\": 1").size(), "\"entry_count\": 5");
		const pk::PackReport rep = pk::verify_pack_manifest_json(m);
		check("entry_count mismatch -> kMalformed", rep.verdict == pk::PackVerdict::kMalformed,
		      rep.reason);
	}

	// Bad-width entry hash.
	{
		std::string m = minimal_manifest();
		const std::string good = std::string(64, 'b');  // the entry hash
		const std::size_t p = m.find(good);
		m.replace(p, good.size(), std::string(10, 'b'));
		const pk::PackReport rep = pk::verify_pack_manifest_json(m);
		check("bad-width entry hash -> kMalformed", rep.verdict == pk::PackVerdict::kMalformed,
		      rep.reason);
	}
}

// -- (d) ROUND-TRIP against a REAL emit-pck manifest --------------------------
static void test_roundtrip_real_manifest() {
	std::printf("test_roundtrip_real_manifest (verifier agrees with mcc emit-pck)\n");
	const std::string path = fixture_dir() + "/pack.manifest.core.json";
	std::string json;
	if (!read_file(path, json)) {
		check("fixture readable", false, "could not read " + path);
		return;
	}
	check("fixture readable", true);

	const pk::PackManifest m = pk::parse_pack_manifest(json);
	check("real manifest parses", m.parse_ok);
	check("parsed schema tag", m.manifest_schema == "meridian/pack-manifest@1",
	      m.manifest_schema);
	check("parsed namespace = core", m.pack_namespace == "core", m.pack_namespace);
	check("parsed content_schema_version = 1", m.content_schema_version == 1);
	check("parsed 37 entries", m.entries.size() == 37,
	      "got " + std::to_string(m.entries.size()));
	check("entry_count field == parsed entries", m.entry_count == m.entries.size());
	// The known content hash emit-pck produced for content/core (byte-stable).
	check("parsed content_hash",
	      m.content_hash == "3866e1af351061e11b918637b92c882ba2141b1feff8e2cbfb4326378f4ed3b8",
	      m.content_hash);
	// A representative entry parsed exactly (first entry).
	check("first entry id", !m.entries.empty() && m.entries[0].id == "core:ability.minor_healing",
	      m.entries.empty() ? "no entries" : m.entries[0].id);
	check("first entry numeric_id = 1", !m.entries.empty() && m.entries[0].numeric_id == 1);
	check("first entry resource", !m.entries.empty() &&
	      m.entries[0].resource == "res://meridian/core/tables/ability.bin",
	      m.entries.empty() ? "" : m.entries[0].resource);

	// The whole point: the verifier ACCEPTS the emitter's output as-is.
	const pk::PackReport rep = pk::verify_pack_manifest(m);
	check("real emit-pck manifest -> kOk", rep.verdict == pk::PackVerdict::kOk, rep.reason);
	check("real manifest content_version = core@0.1.0", rep.content_version == "core@0.1.0",
	      rep.content_version);
	check("real manifest content_hash exposed",
	      rep.content_hash == "3866e1af351061e11b918637b92c882ba2141b1feff8e2cbfb4326378f4ed3b8");

	// And with the matching engine pin + the exact content-hash pin, still OK.
	pk::PackVerifyOptions opts;
	opts.expected_godot_version = "4.6";
	opts.expected_content_hash = m.content_hash;
	const pk::PackReport rep2 = pk::verify_pack_manifest(m, opts);
	check("real manifest OK with matching engine + hash pins",
	      rep2.verdict == pk::PackVerdict::kOk, rep2.reason);
}

// -- engine pin ---------------------------------------------------------------
static void test_engine_pin() {
	std::printf("test_engine_pin (godot_version pin -> kEngineMismatch)\n");
	pk::PackVerifyOptions opts;
	opts.expected_godot_version = "4.7";  // client pinned to a different engine
	const pk::PackReport rep = pk::verify_pack_manifest_json(minimal_manifest(1, "4.6"), opts);
	check("engine mismatch -> kEngineMismatch", rep.verdict == pk::PackVerdict::kEngineMismatch,
	      rep.reason);
	check("engine mismatch hard fails", rep.hard_fail);

	// Matching pin -> OK.
	opts.expected_godot_version = "4.6";
	check("matching engine pin -> kOk",
	      pk::verify_pack_manifest_json(minimal_manifest(1, "4.6"), opts).verdict ==
	          pk::PackVerdict::kOk);
}

// -- realm content-hash pin ---------------------------------------------------
static void test_content_hash_pin() {
	std::printf("test_content_hash_pin (realm hash pin -> kHashMismatch)\n");
	pk::PackVerifyOptions opts;
	opts.expected_content_hash = std::string(64, 'f');  // a different, well-formed hash
	const pk::PackReport rep = pk::verify_pack_manifest_json(minimal_manifest(), opts);
	check("wrong content_hash pin -> kHashMismatch", rep.verdict == pk::PackVerdict::kHashMismatch,
	      rep.reason);
	check("hash mismatch hard fails", rep.hard_fail);

	// Matching pin -> OK.
	opts.expected_content_hash = std::string(64, 'a');  // the manifest's hash
	check("matching content_hash pin -> kOk",
	      pk::verify_pack_manifest_json(minimal_manifest(), opts).verdict == pk::PackVerdict::kOk);

	// A MALFORMED pin is ignored (treated as no pin) rather than failing boot —
	// operator config noise, not a content fault (mirrors worldd #89).
	opts.expected_content_hash = "not-a-hash";
	check("malformed pin ignored (still kOk)",
	      pk::verify_pack_manifest_json(minimal_manifest(), opts).verdict == pk::PackVerdict::kOk);
}

// -- forward compatibility ----------------------------------------------------
static void test_forward_compat_unknown_keys() {
	std::printf("test_forward_compat_unknown_keys (newer emit-pck minor -> still kOk)\n");
	// A manifest with an extra top-level key AND an extra key inside an entry, as a
	// newer emit-pck minor might add. An older client must ignore them, not break.
	std::string m = minimal_manifest();
	// Insert an unknown top-level key after "built_at".
	const std::size_t p = m.find("\"built_at\": \"2026-07-06 12:00:00\",");
	m.insert(p, "\"future_field\": {\"nested\": [1, 2, 3]},\n  ");
	// Add an unknown key inside the entry.
	const std::size_t q = m.find("\"type\": \"item\",");
	m.insert(q, "\"future_entry_field\": 42, ");
	const pk::PackReport rep = pk::verify_pack_manifest_json(m);
	check("unknown keys ignored -> kOk", rep.verdict == pk::PackVerdict::kOk, rep.reason);
	check("still resolves identity", rep.content_version == "core@1.2.3", rep.content_version);
}

// -- optional per-entry hash check --------------------------------------------
static void test_entry_hash_check() {
	std::printf("test_entry_hash_check (verify_entry_hash: match / mismatch / absent)\n");
	const pk::PackManifest m = pk::parse_pack_manifest(minimal_manifest());
	// The entry's declared hash is 64 'b'.
	check("matching entry hash -> kOk",
	      pk::verify_entry_hash(m, "res://meridian/core/tables/item.bin", std::string(64, 'b')) ==
	          pk::PackVerdict::kOk);
	check("wrong entry hash -> kHashMismatch",
	      pk::verify_entry_hash(m, "res://meridian/core/tables/item.bin", std::string(64, 'c')) ==
	          pk::PackVerdict::kHashMismatch);
	check("bad-width actual hash -> kHashMismatch",
	      pk::verify_entry_hash(m, "res://meridian/core/tables/item.bin", "short") ==
	          pk::PackVerdict::kHashMismatch);
	check("unknown resource -> kMalformed",
	      pk::verify_entry_hash(m, "res://meridian/core/nope.bin", std::string(64, 'b')) ==
	          pk::PackVerdict::kMalformed);
}

// -- verdict names ------------------------------------------------------------
static void test_verdict_names() {
	std::printf("test_verdict_names\n");
	check("kOk name", std::string(pk::pack_verdict_name(pk::PackVerdict::kOk)) == "ok");
	check("kSchemaMismatch name",
	      std::string(pk::pack_verdict_name(pk::PackVerdict::kSchemaMismatch)) == "schema-mismatch");
	check("kEngineMismatch name",
	      std::string(pk::pack_verdict_name(pk::PackVerdict::kEngineMismatch)) == "engine-mismatch");
	check("kHashMismatch name",
	      std::string(pk::pack_verdict_name(pk::PackVerdict::kHashMismatch)) == "hash-mismatch");
	check("kMalformed name",
	      std::string(pk::pack_verdict_name(pk::PackVerdict::kMalformed)) == "malformed");
}

int main() {
	std::printf("meridian client IF-5 pack-manifest verify core (#107) unit tests\n\n");
	test_valid_ok();
	test_schema_mismatch();
	test_malformed();
	test_roundtrip_real_manifest();
	test_engine_pin();
	test_content_hash_pin();
	test_forward_compat_unknown_keys();
	test_entry_hash_check();
	test_verdict_names();

	std::printf("\n%d/%d checks passed\n", g_checks - g_fail, g_checks);
	if (g_fail) {
		std::printf("FAIL: %d check(s) failed\n", g_fail);
		return 1;
	}
	std::printf("PASS\n");
	return 0;
}
